import dotenv from 'dotenv';
import { FileshareConfig } from '@ukef/dtfs2-common';

dotenv.config();

const { AZURE_UTILISATION_REPORTS_FILESHARE_NAME, AZURE_PORTAL_STORAGE_ACCOUNT, AZURE_PORTAL_STORAGE_ACCESS_KEY } = process.env;

export const AZURE_UTILISATION_REPORTS_FILESHARE_CONFIG: FileshareConfig = {
  FILESHARE_NAME: String(AZURE_UTILISATION_REPORTS_FILESHARE_NAME),
  STORAGE_ACCOUNT: String(AZURE_PORTAL_STORAGE_ACCOUNT),
  STORAGE_ACCESS_KEY: String(AZURE_PORTAL_STORAGE_ACCESS_KEY),
};
