const BANKS = require('../banks');
const { MAKER, CHECKER, ADMIN, READ_ONLY } = require('./roles');

const UKEF_TEST_BANK_1 = BANKS.find((bank) => bank.name === 'UKEF test bank (Delegated)');
const UKEF_TEST_BANK_2 = BANKS.find((bank) => bank.name === 'UKEF test bank (Delegated) 2');
const UKEF_GEF_ONLY_BANK = BANKS.find((bank) => bank.name === 'GEF Only Bank');

const USERS = [
  {
    username: 'BANK1_MAKER1',
    password: 'AbC!2345',
    firstname: 'First',
    surname: 'Last',
    email: 'maker1@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: [MAKER],
    bank: UKEF_TEST_BANK_1,
  },
  {
    username: 'BANK1_MAKER2',
    password: 'AbC!2345',
    firstname: 'Tamara',
    surname: 'last',
    email: 'maker2@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: [MAKER],
    bank: UKEF_TEST_BANK_1,
  },
  {
    username: 'BANK1_MAKER3',
    password: 'AbC!2345',
    firstname: 'First',
    surname: 'Last',
    email: 'maker33@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: [MAKER],
    bank: UKEF_TEST_BANK_1,
  },
  {
    username: 'BANK1_READ_ONLY',
    password: 'AbC!2345',
    firstname: 'Bank1',
    surname: 'Read-only',
    email: 'readOnly1@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: [READ_ONLY],
    bank: UKEF_TEST_BANK_1,
  },
  {
    username: 'BANK3_GEF_MAKER1',
    password: 'AbC!2345',
    firstname: 'Benito',
    surname: 'Sutton',
    email: 'maker3@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: [MAKER],
    bank: UKEF_GEF_ONLY_BANK,
  },
  {
    username: 'BANK3_GEF_CHECKER1',
    password: 'AbC!2345',
    firstname: 'Tony',
    surname: 'Sheridan',
    email: 'maker4@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: [CHECKER],
    bank: UKEF_GEF_ONLY_BANK,
  },
  {
    username: 'BANK1_CHECKER1',
    password: 'AbC!2345',
    firstname: 'Mister',
    surname: 'Checker',
    email: 'checker1@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: [CHECKER],
    bank: UKEF_TEST_BANK_1,
  },
  {
    username: 'BANK1_MAKER_CHECKER1',
    password: 'AbC!2345',
    firstname: 'Vladimir',
    surname: 'Scorpius',
    email: 'checker2@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: [MAKER, CHECKER],
    bank: UKEF_TEST_BANK_1,
  },
  {
    username: 'BANK1_MAKENCHECK2',
    password: 'AbC!2345',
    firstname: 'Vladimir',
    surname: 'Scorpius',
    email: 'checker3@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: [MAKER, CHECKER],
    bank: UKEF_TEST_BANK_1,
  },
  {
    username: 'BANK1_READ_ONLY1',
    password: 'AbC!2345',
    firstname: 'Reid',
    surname: 'Oakley',
    email: 'readonly1@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: ['read-only'],
    bank: UKEF_TEST_BANK_1,
  },
  {
    username: 'BANK2_MAKER2',
    password: 'AbC!2345',
    firstname: 'Tamara',
    surname: 'last',
    email: 'maker5@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: [MAKER],
    bank: UKEF_TEST_BANK_2,
  },
  {
    username: 'BANK2_MAKER1',
    password: 'AbC!2345',
    firstname: 'First',
    surname: 'Last',
    email: 'maker6@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: [MAKER],
    bank: UKEF_TEST_BANK_2,
  },
  {
    username: 'BANK2_CHECKER1',
    password: 'AbC!2345',
    firstname: 'Mister',
    surname: 'Checker',
    email: 'checker4@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: [CHECKER],
    bank: UKEF_TEST_BANK_2,
  },
  {
    username: 'BANK2_READ_ONLY1',
    password: 'AbC!2345',
    firstname: 'Reid',
    surname: 'Oakley',
    email: 'readonly2@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: ['read-only'],
    bank: UKEF_TEST_BANK_2,
  },
  {
    username: 'NOBODY',
    password: 'AbC!2345',
    firstname: 'first',
    surname: 'Spang',
    email: 'test1@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: [],
    bank: UKEF_TEST_BANK_1,
  },
  {
    username: 'ADMIN',
    password: 'AbC!2345',
    firstname: 'Julius',
    surname: 'No',
    email: 'test2@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: [ADMIN, MAKER],
    bank: {
      id: '*',
    },
  },
  {
    username: 'READ_ONLY',
    password: 'AbC!2345',
    firstname: 'Reid',
    surname: 'Oakley',
    email: 'readonly@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: ['read-only'],
    bank: {
      id: '*',
    },
  },
  {
    username: 'ADMINNOMAKER',
    password: 'AbC!2345',
    firstname: 'Julius',
    surname: 'No',
    email: 'adminnomaker@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: [ADMIN],
    bank: {
      id: '*',
    },
  },
  {
    username: 'TEST_EMAIL_NO_GOV_NOTIFY',
    password: 'AbC!2345',
    firstname: 'Wolfgang',
    surname: 'Weisen',
    email: 'test_no_notify@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    roles: [MAKER],
    bank: {
      id: '*',
    },
  },
];

module.exports = USERS;
