/* eslint-disable global-require */
module.exports = {
  signInLink: require('./login/sign-in-link'),
  aboutExporter: require('./about-exporter'),
  aboutFacility: require('./about-facility'),
  applicationActivities: require('./application-activities'),
  applicationDetails: require('./application-details'),
  applicationPreview: require('./application-preview'),
  applicationStatusBanner: require('./application-status-banner'),
  applicationSubmission: require('./application-submission'),
  automaticCover: require('./automatic-cover'),
  bankReviewDate: require('./bank-review-date'),
  cloneDeal: require('./clone-deal'),
  companiesHouse: require('./companies-house'),
  coverStartDate: require('./cover-start-date'),
  dashboardPage: require('./dashboard-page'),
  enterExportersCorrAddress: require('./enter-exporters-corr-address'),
  exportersAddress: require('./exporters-address'),
  facilities: require('./facilities'),
  facilityConfirmDeletion: require('./facility-confirm-deletion'),
  facilityCurrency: require('./facility-currency'),
  facilityEndDate: require('./facility-end-date'),
  facilityGuarantee: require('./facility-guarantee'),
  facilityValue: require('./facility-value'),
  ineligibleAutomaticCover: require('./ineligible-automatic-cover'),
  ineligibleGef: require('./ineligible-gef'),
  landingPage: require('./landingPage'),
  mandatoryCriteria: require('./mandatory-criteria'),
  nameApplication: require('./name-application'),
  pageBanner: require('./page-banner'),
  providedFacility: require('./provided-facility'),
  returnToMaker: require('./return-to-maker'),
  securityDetails: require('./security-details'),
  selectExportersCorrAddress: require('./select-exporters-corr-address'),
  submitToUkef: require('./submit-to-ukef'),
  unissuedFacilitiesAboutFacility: require('./unissued-facilities-about-facility'),
  unissuedFacilities: require('./unissued-facilities'),
};
