# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include:
    - master

variables:

  # Components
  portal: 'portal'
  dealApi: 'deal-api'

  # Connections
  serviceConnection: 'Digital-Dev-Deployment'
  containerRegistry: 'dtfsdev.azurecr.io'
  
  # Build agent VM image
  vmImageName: 'ubuntu-latest'

stages:
- stage: build
  displayName: Build stage
  jobs:  
  - job: portal
    displayName: 'Portal: build and push container image'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@1
      displayName: Build the image
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: $(serviceConnection)
        azureContainerRegistry: $(containerRegistry)
        command: 'Build an image'
        dockerFile: '$(portal)/Dockerfile'
        imageName: '$(portal):$(Build.BuildId)'
    - task: Docker@1
      displayName: Push the image
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: $(serviceConnection)
        azureContainerRegistry: $(containerRegistry)
        command: 'Push an image'
        imageName: '$(portal):$(Build.BuildId)'

  - job: DealApi
    displayName: 'Deal API: build and push container image'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@1
      displayName: Build the image
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: $(serviceConnection)
        azureContainerRegistry: $(containerRegistry)
        command: 'Build an image'
        dockerFile: '$(dealApi)/Dockerfile'
        imageName: '$(dealApi):$(Build.BuildId)'
    - task: Docker@1
      displayName: Push the image
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: $(serviceConnection)
        azureContainerRegistry: $(containerRegistry)
        command: 'Push an image'
        imageName: '$(dealApi):$(Build.BuildId)'

- stage: deploy
  displayName: Deploy stage
  jobs:
    - job: portal
      displayName: 'Portal: deploy to App Service'
      steps:
      - task: AzureRmWebAppDeployment@4
        displayName: Deploy
        inputs:
          azureSubscription: '$(serviceConnection)'
          appType: 'webAppContainer'
          WebAppName: 'dtfs-$(portal)-dev'
          DockerNamespace: '$(containerRegistry)'
          DockerRepository: '$(portal)'
          DockerImageTag: '$(Build.BuildId)'
    - job: dealApi
      displayName: 'Deal API: deploy to App Service'
      steps:
      - task: AzureRmWebAppDeployment@4
        displayName: Deploy
        inputs:
          azureSubscription: '$(serviceConnection)'
          appType: 'webAppContainer'
          WebAppName: 'dtfs-$(dealApi)-dev'
          DockerNamespace: '$(containerRegistry)'
          DockerRepository: '$(dealApi)'
          DockerImageTag: '$(Build.BuildId)'

