# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  portal: 'portal'
  dealApi: 'deal-api'
  containerRegistry: 'dtfsdev.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/deal-api/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: ContainerImage
    displayName: Build and push container image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@1
      displayName: Build the image
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: 'Digital-Dev-Deployment'
        azureContainerRegistry: $(containerRegistry)
        command: 'Build an image'
        dockerFile: '$(dealApi)/Dockerfile'
        imageName: '$(dealApi):$(Build.BuildId)'
    - task: Docker@1
      displayName: Push the image
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: 'Digital-Dev-Deployment'
        azureContainerRegistry: $(containerRegistry)
        command: 'Push an image'
        imageName: '$(dealApi):$(Build.BuildId)'