version: "3"
services:
  dtfs-submissions-data:
    image: mongo:5.0.5
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=r00t
    ports:
      - "27017-27019:27017-27019"

  dtfs-central-api:
    build: ./dtfs-central-api
    image: dtfs/dtfs-central-api
    restart: always
    depends_on:
      - dtfs-submissions-data
      - reference-data-proxy
    ports:
      - "5005:5005"
    volumes:
      - ./dtfs-central-api/src:/app/src:ro
    environment:
      - PORT=5005
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGODB_URI=mongodb://root:r00t@dtfs-submissions-data:27017/?authMechanism=DEFAULT
      - DTFS_CENTRAL_API=http://localhost:5005
      - TZ=Europe/London
    entrypoint: npx nodemon src/index.js -L

  trade-finance-manager-ui:
    build: ./trade-finance-manager-ui
    image: dtfs/trade-finance-manager-ui
    depends_on:
      - trade-finance-manager-api
    ports:
      - "5003:5003"
    volumes:
      - ./trade-finance-manager-ui/server:/app/server:ro
      - ./trade-finance-manager-ui/public:/app/public:ro
      - ./trade-finance-manager-ui/templates:/app/templates:ro
    environment:
      - PORT=5003
      - TRADE_FINANCE_MANAGER_API_URL=http://trade-finance-manager-api:5004
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - UKEF_TFM_API_SYSTEM_KEY
      - ESTORE_URL=${ESTORE_URL}
      - SESSION_SECRET
      - TZ=Europe/London
    command: npx nodemon server/index.js -L

  trade-finance-manager-api:
    build: ./trade-finance-manager-api
    image: dtfs/trade-finance-manager-api
    restart: always
    depends_on:
      - portal-api
      - dtfs-central-api
      - reference-data-proxy
    ports:
      - "5004:5004"
    volumes:
      - ./trade-finance-manager-api/src:/app/src:ro
    environment:
      - PORT=5004
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGODB_URI=mongodb://root:r00t@dtfs-submissions-data:27017/?authMechanism=DEFAULT
      - DTFS_CENTRAL_API=http://dtfs-central-api:5005
      - AZURE_NUMBER_GENERATOR_FUNCTION_URL=http://number-generator-function
      - AZURE_NUMBER_GENERATOR_FUNCTION_SCHEDULE
      - UKEF_TFM_API_SYSTEM_KEY
      - UKEF_TFM_API_REPORTS_KEY
      - TFM_URI=http://localhost:5003
      - SENTRY_DSN=${SENTRY_DSN}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - DATA_MIGRATION_SCRIPT=true
      - TZ=Europe/London
    entrypoint: npx nodemon src/index.js -L

  portal:
    build: ./portal
    image: dtfs/portal
    restart: always
    depends_on:
      - redis
      - portal-api
    ports:
      - "5000:5000"
    volumes:
      - ./portal/server:/app/server:ro
      - ./portal/public:/app/public:ro
      - ./portal/templates:/app/templates:ro
    environment:
      - DEAL_API_URL=http://portal-api:5001
      - COMPANIES_HOUSE_API_URL=https://api.companieshouse.gov.uk
      - COMPANIES_HOUSE_API_KEY
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - SESSION_SECRET
      - REDIS_HOSTNAME=redis
      - TZ=Europe/London
    command: npx nodemon server/index.js -L

  portal-api:
    build: ./portal-api
    image: dtfs/portal-api
    restart: always
    depends_on:
      - dtfs-central-api
      - reference-data-proxy
    ports:
      - "5001:5001"
    volumes:
      - ./portal-api/src:/app/src:ro
    environment:
      - PORT=5001
      - CORS_ORIGIN=http://localhost:5000
      - JWT_SIGNING_KEY
      - JWT_VALIDATING_KEY
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGODB_URI=mongodb://root:r00t@dtfs-submissions-data:27017/?authMechanism=DEFAULT
      - AZURE_WORKFLOW_STORAGE_ACCOUNT
      - AZURE_WORKFLOW_STORAGE_ACCESS_KEY
      - AZURE_WORKFLOW_FILESHARE_NAME
      - AZURE_WORKFLOW_EXPORT_FOLDER
      - AZURE_WORKFLOW_IMPORT_FOLDER
      - AZURE_PORTAL_STORAGE_ACCOUNT
      - AZURE_PORTAL_STORAGE_ACCESS_KEY
      - AZURE_PORTAL_FILESHARE_NAME
      - AZURE_PORTAL_EXPORT_FOLDER
      - DTFS_PORTAL_SCHEDULER
      - GOV_NOTIFY_API_KEY
      - GOV_NOTIFY_EMAIL_RECIPIENT
      - DTFS_PORTAL_SCHEDULER=true
      - FETCH_WORKFLOW_TYPE_B_SCHEDULE=*/1 * * * * *
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - DTFS_CENTRAL_API=http://dtfs-central-api:5005
      - TFM_API=http://trade-finance-manager-api:5004
      - SENTRY_DSN=${SENTRY_DSN}
      - TZ=Europe/London

    entrypoint: npx nodemon src/index.js -L

  reference-data-proxy:
    build: ./reference-data-proxy
    image: dtfs/reference-data-proxy
    restart: always
    depends_on:
      - dtfs-submissions-data
    ports:
      - "5002:5002"
    volumes:
      - ./reference-data-proxy/src:/app/src:ro
    environment:
      - PORT=5002
      - COMPANIES_HOUSE_API_URL=https://api.companieshouse.gov.uk
      - COMPANIES_HOUSE_API_KEY
      - ORDNANCE_SURVEY_API_URL=https://api.os.co.uk
      - ORDNANCE_SURVEY_API_KEY
      - MULESOFT_API_KEY
      - MULESOFT_API_SECRET
      - MULESOFT_API_NUMBER_GENERATOR_URL
      - MULESOFT_API_PARTY_DB_KEY
      - MULESOFT_API_PARTY_DB_SECRET
      - MULESOFT_API_PARTY_DB_URL
      - MULESOFT_API_ACBS_DEAL_URL
      - MULESOFT_API_ACBS_FACILITY_URL
      - MULESOFT_API_CURRENCY_EXCHANGE_RATE_URL
      - MULESOFT_API_CURRENCY_EXCHANGE_RATE_KEY
      - MULESOFT_API_CURRENCY_EXCHANGE_RATE_SECRET
      - MULESOFT_API_EXPOSURE_PERIOD_URL
      - MULESOFT_API_UKEF_MDM_EA_URL
      - MULESOFT_API_UKEF_MDM_EA_KEY
      - MULESOFT_API_UKEF_MDM_EA_SECRET
      - MULESOFT_API_UKEF_ESTORE_EA_URL
      - MULESOFT_API_UKEF_ESTORE_EA_KEY
      - MULESOFT_API_UKEF_ESTORE_EA_SECRET
      - AZURE_ACBS_FUNCTION_URL=http://host.docker.internal:7071
      - AZURE_NUMBER_GENERATOR_FUNCTION_URL=http://number-generator-function
      - GOV_NOTIFY_API_KEY
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGODB_URI=mongodb://root:r00t@dtfs-submissions-data:27017/?authMechanism=DEFAULT
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - TZ=Europe/London
    entrypoint: npx nodemon src/index.ts -L

  gef-ui:
    build: ./gef-ui
    image: dtfs/gef-ui
    restart: always
    depends_on:
      - redis
      - portal-api
    ports:
      - "5006:5006"
    volumes:
      - ./gef-ui/server:/app/server:ro
      - ./gef-ui/public:/app/public:ro
      - ./gef-ui/templates:/app/templates:ro
    environment:
      - DEAL_API_URL=http://portal-api:5001
      - COMPANIES_HOUSE_API_URL=https://api.companieshouse.gov.uk
      - COMPANIES_HOUSE_API_KEY
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - SESSION_SECRET
      - REDIS_HOSTNAME=redis
      - TZ=Europe/London
    command: npx nodemon server/index.js -L

  # acbs-function:
  #   build: ./azure-functions/acbs-function
  #   image: dtfs/azure-function-acbs
  #   restart: always
  #   ports:
  #     - "7071:80"
  #   environment:
  #     - AzureWebJobsStorage=DefaultEndpointsProtocol=https;AccountName=${AZURE_PORTAL_STORAGE_ACCOUNT};AccountKey=${AZURE_PORTAL_STORAGE_ACCESS_KEY};EndpointSuffix=core.windows.net
  #     - FUNCTIONS_WORKER_RUNTIME=node
  #     - WEBSITE_HOSTNAME=localhost:7071
  #     - MULESOFT_API_KEY
  #     - MULESOFT_API_SECRET
  #     - MULESOFT_API_UKEF_TF_EA_URL
  #     - MULESOFT_API_UKEF_MDM_EA_URL
  #     - MULESOFT_API_UKEF_MDM_EA_KEY
  #     - MULESOFT_API_UKEF_MDM_EA_SECRET
  #     - TZ=Europe/London

  number-generator-function:
    build: ./azure-functions/number-generator-function
    image: dtfs/azure-function-number-generator
    restart: always
    ports:
      - "7072:80"
    environment:
      - AzureWebJobsStorage=DefaultEndpointsProtocol=https;AccountName=${AZURE_PORTAL_STORAGE_ACCOUNT};AccountKey=${AZURE_PORTAL_STORAGE_ACCESS_KEY};EndpointSuffix=core.windows.net
      - FUNCTIONS_WORKER_RUNTIME=node
      - WEBSITE_HOSTNAME=localhost:7072
      - MULESOFT_API_UKEF_TF_EA_URL
      - MULESOFT_API_KEY
      - MULESOFT_API_SECRET
      - TZ=Europe/London

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 300M

  reverse-proxy:
    build: ./reverse-proxy
    image: "dtfs/reverse-proxy"
    depends_on:
      - portal
      - gef-ui
    ports:
      - "80:80"
    environment:
      - PORTAL_UI=portal:5000
      - GEF_UI=gef-ui:5006
    deploy:
      resources:
        limits:
          cpus: "0.01"
          memory: 150M