version: '3'
services:
  clamav:
    image: mkodockx/docker-clamav:alpine
    restart: always
    ports:
      - '3310:3310'

  dtfs-sql:
    build: ./libs/common/src/sql-db-connection
    restart: always
    environment:
      - ACCEPT_EULA
      - MSSQL_SA_PASSWORD
      - SQL_DB_USERNAME
      - SQL_DB_PASSWORD
      - SQL_DB_NAME
    ports:
      - '1433:1433'
    volumes:
      - ./dtfs-sql-volume-dtfs-submissions:/data/db

  dtfs-submissions-data:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    environment:
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=r00t
    ports:
      - '27017-27019:27017-27019'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: "--bind_ip_all --keyFile /mongo-keyfile --replSet rs0"
    volumes:
      - ./dtfs-submissions-data-volume-dtfs-submissions:/data/db

  dtfs-central-api:
    build:
      context: .
      dockerfile: ./dtfs-central-api/Dockerfile
    image: dtfs/dtfs-central-api
    restart: always
    depends_on:
      - dtfs-sql
      - dtfs-submissions-data
      - external-api
    ports:
      - '5005:5005'
    volumes:
      - ./dtfs-central-api/src:/app/dtfs-central-api/src:ro
      - ./libs:/app/libs:ro
    environment:
      - PORT=5005
      - CORS_ORIGIN
      - EXTERNAL_API_URL=http://external-api:5002
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGODB_URI
      - DTFS_CENTRAL_API_URL=http://localhost:5005
      - TZ=Europe/London
      - NODE_ENV
      - PORTAL_API_KEY
      - TFM_API_KEY
      - DTFS_CENTRAL_API_KEY
      - EXTERNAL_API_KEY
      - RATE_LIMIT_THRESHOLD
      - AUDIT_API_URL
      - AUDIT_API_USERNAME
      - AUDIT_API_PASSWORD
      - CHANGE_STREAM_ENABLED='true'
      - UTILISATION_REPORT_CREATION_FOR_BANKS_SCHEDULE
      - SQL_DB_HOST
      - SQL_DB_PORT
      - SQL_DB_USERNAME
      - SQL_DB_PASSWORD
      - SQL_DB_NAME
      - SQL_DB_LOGGING_ENABLED
      - ACBS_DURABLE_FUNCTIONS_LOG_DELETION_SCHEDULE
      - DELETION_AUDIT_LOGS_DELETE_AFTER_SECONDS=600
    entrypoint: npx ts-node dtfs-central-api/src/index.ts

  trade-finance-manager-ui:
    build:
      context: .
      dockerfile: ./trade-finance-manager-ui/Dockerfile
    image: dtfs/trade-finance-manager-ui
    depends_on:
      - trade-finance-manager-api
    ports:
      - '5003:5003'
    volumes:
      - ./trade-finance-manager-ui/server:/app/trade-finance-manager-ui/server:ro
      - ./trade-finance-manager-ui/public:/app/trade-finance-manager-ui/public:ro
      - ./trade-finance-manager-ui/templates:/app/trade-finance-manager-ui/templates:ro
      - ./libs:/app/libs:ro
    environment:
      - PORT=5003
      - PORTAL_API_KEY
      - TFM_API_KEY
      - DTFS_CENTRAL_API_KEY
      - EXTERNAL_API_KEY
      - TFM_API_URL=http://trade-finance-manager-api:5004
      - EXTERNAL_API_URL=http://external-api:5002
      - UKEF_TFM_API_SYSTEM_KEY
      - ESTORE_URL
      - REDIS_HOSTNAME=redis
      - SESSION_SECRET
      - TZ=Europe/London
      - NODE_ENV
      - RATE_LIMIT_THRESHOLD
      - UTILISATION_REPORT_DUE_DATE_BUSINESS_DAYS_FROM_START_OF_MONTH
      - CONTACT_US_SELF_SERVICE_PORTAL_URL
      - CONTACT_US_EMAIL_ADDRESS
      - FF_TFM_PAYMENT_RECONCILIATION_ENABLED

  trade-finance-manager-api:
    build:
      context: .
      dockerfile: ./trade-finance-manager-api/Dockerfile
    image: dtfs/trade-finance-manager-api
    restart: always
    depends_on:
      - portal-api
      - dtfs-central-api
      - external-api
    ports:
      - '5004:5004'
    volumes:
      - ./trade-finance-manager-api/src:/app/trade-finance-manager-api/src:ro
      - ./libs:/app/libs:ro
    environment:
      - PORT=5004
      - CORS_ORIGIN
      - EXTERNAL_API_URL=http://external-api:5002
      - PORTAL_API_KEY
      - TFM_API_KEY
      - DTFS_CENTRAL_API_KEY
      - EXTERNAL_API_KEY
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGODB_URI
      - DTFS_CENTRAL_API_URL=http://dtfs-central-api:5005
      - AZURE_PORTAL_STORAGE_ACCOUNT
      - AZURE_PORTAL_STORAGE_ACCESS_KEY
      - AZURE_UTILISATION_REPORTS_FILESHARE_NAME
      - UKEF_TFM_API_SYSTEM_KEY
      - UKEF_TFM_API_REPORTS_KEY
      - TFM_UI_URL=http://localhost:5003
      - AZURE_ACBS_FUNCTION_URL=http://host.docker.internal:7071
      - SENTRY_DSN=${SENTRY_DSN}
      - JWT_VALIDATING_KEY
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - TZ=Europe/London
      - UKEF_INTERNAL_NOTIFICATION=test
      - NODE_ENV
      - RATE_LIMIT_THRESHOLD
      - CHANGE_STREAM_ENABLED='true'
      - DELETION_AUDIT_LOGS_DELETE_AFTER_SECONDS=600
    entrypoint: npx ts-node trade-finance-manager-api/src/index.ts

  portal:
    build:
      context: .
      dockerfile: ./portal/Dockerfile
    image: dtfs/portal
    restart: always
    depends_on:
      - redis
      - portal-api
      - clamav
    ports:
      - '5000:5000'
    volumes:
      - ./portal/server:/app/portal/server:ro
      - ./portal/public:/app/portal/public:ro
      - ./portal/templates:/app/portal/templates:ro
      - ./libs:/app/libs:ro
    environment:
      - PORTAL_API_URL=http://portal-api:5001
      - COMPANIES_HOUSE_API_URL=https://api.companieshouse.gov.uk
      - COMPANIES_HOUSE_API_KEY
      - EXTERNAL_API_URL=http://external-api:5002
      - PORTAL_API_KEY
      - TFM_API_KEY
      - DTFS_CENTRAL_API_KEY
      - EXTERNAL_API_KEY
      - SESSION_SECRET
      - TZ=Europe/London
      - NODE_ENV
      - REDIS_HOSTNAME=redis
      - RATE_LIMIT_THRESHOLD
      - CLAMAV_PORT=3310
      - CLAMAV_HOST=clamav
      - CLAMAV_DEBUG_MODE_ENABLED=true
      - CLAMAV_SCANNING_ENABLED
      - UTILISATION_REPORT_MAX_FILE_SIZE_BYTES=1048576
      - CONTACT_US_EMAIL_ADDRESS 

  portal-api:
    build:
      context: .
      dockerfile: ./portal-api/Dockerfile
    image: dtfs/portal-api
    restart: always
    depends_on:
      - dtfs-central-api
      - external-api
    ports:
      - '5001:5001'
    volumes:
      - ./portal-api/src:/app/portal-api/src:ro
      - ./libs:/app/libs:ro
    environment:
      - PORT=5001
      - CORS_ORIGIN
      - JWT_SIGNING_KEY
      - JWT_VALIDATING_KEY
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGODB_URI
      - AZURE_PORTAL_STORAGE_ACCOUNT
      - AZURE_PORTAL_STORAGE_ACCESS_KEY
      - AZURE_PORTAL_FILESHARE_NAME
      - AZURE_PORTAL_EXPORT_FOLDER
      - AZURE_UTILISATION_REPORTS_FILESHARE_NAME
      - GOV_NOTIFY_API_KEY
      - GOV_NOTIFY_EMAIL_RECIPIENT
      - EXTERNAL_API_URL=http://external-api:5002
      - PORTAL_API_KEY
      - TFM_API_KEY
      - DTFS_CENTRAL_API_KEY
      - EXTERNAL_API_KEY
      - PORTAL_UI_URL
      - DTFS_CENTRAL_API_URL=http://dtfs-central-api:5005
      - TFM_API_URL=http://trade-finance-manager-api:5004
      - TZ=Europe/London
      - NODE_ENV
      - RATE_LIMIT_THRESHOLD
      - PDC_INPUTTERS_EMAIL_RECIPIENT
      - UTILISATION_REPORT_SUBMISSION_PERIOD_START_EMAIL_SCHEDULE
      - UTILISATION_REPORT_OVERDUE_CHASER_DATE_BUSINESS_DAYS_FROM_START_OF_MONTH
      - UTILISATION_REPORT_DUE_DATE_BUSINESS_DAYS_FROM_START_OF_MONTH
      - UTILISATION_REPORT_DUE_EMAIL_SCHEDULE
      - UTILISATION_REPORT_OVERDUE_EMAIL_SCHEDULE
      - SQL_DB_HOST
      - SQL_DB_PORT
      - SQL_DB_USERNAME
      - SQL_DB_PASSWORD
      - SQL_DB_NAME
      - SQL_DB_LOGGING_ENABLED
    entrypoint: npx ts-node portal-api/src/index.ts

  external-api:
    build:
      context: .
      dockerfile: ./external-api/Dockerfile
    image: dtfs/external-api
    restart: always
    depends_on:
      - dtfs-submissions-data
    ports:
      - '5002:5002'
    volumes:
      - ./external-api/src:/app/external-api/src:ro
      - ./libs:/app/libs:ro
    environment:
      - PORT=5002
      - CORS_ORIGIN
      - PORTAL_API_KEY
      - TFM_API_KEY
      - DTFS_CENTRAL_API_KEY
      - EXTERNAL_API_KEY
      - COMPANIES_HOUSE_API_URL=https://api.companieshouse.gov.uk
      - COMPANIES_HOUSE_API_KEY
      - ORDNANCE_SURVEY_API_URL=https://api.os.co.uk
      - ORDNANCE_SURVEY_API_KEY
      - APIM_TFS_URL
      - APIM_TFS_KEY
      - APIM_TFS_VALUE
      - APIM_MDM_URL
      - APIM_MDM_KEY
      - APIM_MDM_VALUE
      - APIM_ESTORE_URL
      - APIM_ESTORE_KEY
      - APIM_ESTORE_VALUE
      - AZURE_ACBS_FUNCTION_URL=http://host.docker.internal:7071
      - GOV_NOTIFY_API_KEY
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGODB_URI
      - EXTERNAL_API_URL=http://external-api:5002
      - TZ=Europe/London
      - NODE_ENV
      - RATE_LIMIT_THRESHOLD
      - ESTORE_CRON_MANAGER_SCHEDULE
    entrypoint: npx nodemon external-api/src/index.ts -L

  gef-ui:
    build:
      context: .
      dockerfile: ./gef-ui/Dockerfile
    image: dtfs/gef-ui
    restart: always
    depends_on:
      - redis
      - portal-api
    ports:
      - '5006:5006'
    volumes:
      - ./gef-ui/server:/app/gef-ui/server:ro
      - ./gef-ui/public:/app/gef-ui/public:ro
      - ./gef-ui/templates:/app/gef-ui/templates:ro
      - ./libs:/app/libs:ro
    environment:
      - PORTAL_API_URL=http://portal-api:5001
      - COMPANIES_HOUSE_API_URL=https://api.companieshouse.gov.uk
      - COMPANIES_HOUSE_API_KEY
      - EXTERNAL_API_URL=http://external-api:5002
      - SESSION_SECRET
      - TZ=Europe/London
      - NODE_ENV
      - REDIS_HOSTNAME=redis
      - PORTAL_API_KEY
      - TFM_API_KEY
      - DTFS_CENTRAL_API_KEY
      - RATE_LIMIT_THRESHOLD
      - CONTACT_US_EMAIL_ADDRESS

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 300M

  reverse-proxy:
    build: ./reverse-proxy
    image: 'dtfs/reverse-proxy'
    depends_on:
      - portal
      - gef-ui
    ports:
      - '80:80'
    environment:
      - PORTAL_UI=portal:5000
      - GEF_UI=gef-ui:5006
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 150M
