version: "3.8"
services:
  dtfs-submissions-data:
    image: mongo:5.0.5
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=r00t
    volumes:
      - ./dtfs-submissions-data-volume-dtfs-submissions:/data/db
    ports:
      - "27017-27019:27017-27019"

  dtfs-central-api:
    build: ./dtfs-central-api
    image: dtfs/dtfs-central-api
    restart: always
    depends_on:
      - dtfs-submissions-data
      - reference-data-proxy
    ports:
      - "5005:5005" # http
      - "9223:9223" # debug
    volumes:
      - ./dtfs-central-api/src:/app/src:ro
    environment:
      - PORT=5005
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGODB_URI=mongodb://root:r00t@dtfs-submissions-data:27017/?authMechanism=DEFAULT
    command: npx nodemon --inspect=0.0.0.0:9223 src/index.js -L

  trade-finance-manager-ui:
    build: ./trade-finance-manager-ui
    image: dtfs/trade-finance-manager-ui
    depends_on:
      - trade-finance-manager-api
    ports:
      - "5003:5003" # http
      - "9224:9224" # debug
    volumes:
      - ./trade-finance-manager-ui/server:/app/server:ro
      - ./trade-finance-manager-ui/public:/app/public:ro
      - ./trade-finance-manager-ui/templates:/app/templates:ro
    environment:
      - PORT=5003
      - TRADE_FINANCE_MANAGER_API_URL=http://trade-finance-manager-api:5004
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - UKEF_TFM_API_SYSTEM_KEY=${UKEF_TFM_API_SYSTEM_KEY}
      - ESTORE_URL=${ESTORE_URL}
      - DTFS_CENTRAL_API=http://dtfs-central-api:5005
      - SESSION_SECRET
      - TZ=Europe/London
      - REDIS_HOSTNAME=redis
    command: npx nodemon --inspect=0.0.0.0:9224 server/index.js -L

  trade-finance-manager-api:
    build: ./trade-finance-manager-api
    image: dtfs/trade-finance-manager-api
    restart: always
    depends_on:
      - portal-api
      - dtfs-central-api
      - reference-data-proxy
    ports:
      - "5004:5004" # http
      - "9225:9225" # debug
    volumes:
      - ./trade-finance-manager-api/src:/app/src:ro
    environment:
      - PORT=5004
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGODB_URI=mongodb://root:r00t@dtfs-submissions-data:27017/?authMechanism=DEFAULT
      - DTFS_CENTRAL_API=http://dtfs-central-api:5005
      - AZURE_NUMBER_GENERATOR_FUNCTION_URL=http://number-generator-function
      - AZURE_NUMBER_GENERATOR_FUNCTION_SCHEDULE
      - UKEF_TFM_API_SYSTEM_KEY=${UKEF_TFM_API_SYSTEM_KEY}
      - UKEF_TFM_API_REPORTS_KEY
      - TFM_URI=http://localhost:5003
      - AZURE_ACBS_FUNCTION_URL=http://host.docker.internal:7071
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - TZ=Europe/London
    command: npx nodemon --inspect=0.0.0.0:9225 src/index.js -L

  portal:
    build: ./portal
    image: dtfs/portal
    restart: always
    depends_on:
      - redis
      - portal-api
    ports:
      - "5000:5000" # http
      - "9226:9226" # debug
    volumes:
      - ./portal/server:/app/server:ro
      - ./portal/public:/app/public:ro
      - ./portal/templates:/app/templates:ro
    environment:
      - DEAL_API_URL=http://portal-api:5001
      - COMPANIES_HOUSE_API_URL=https://api.companieshouse.gov.uk
      - COMPANIES_HOUSE_API_KEY
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - SESSION_SECRET
      - REDIS_HOSTNAME=redis
      - TZ=Europe/London
    command: npx nodemon --inspect=0.0.0.0:9226 server/index.js -L

  portal-api:
    build: ./portal-api
    image: dtfs/portal-api
    restart: always
    depends_on:
      - dtfs-central-api
      - reference-data-proxy
    ports:
      - "5001:5001" # http
      - "9227:9227" # debug
    volumes:
      - ./portal-api/src:/app/src:ro
    environment:
      - PORT=5001
      - CORS_ORIGIN=http://localhost:5000
      - JWT_SIGNING_KEY
      - JWT_VALIDATING_KEY
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGODB_URI=mongodb://root:r00t@dtfs-submissions-data:27017/?authMechanism=DEFAULT
      - AZURE_WORKFLOW_STORAGE_ACCOUNT
      - AZURE_WORKFLOW_STORAGE_ACCESS_KEY
      - AZURE_WORKFLOW_FILESHARE_NAME
      - AZURE_WORKFLOW_EXPORT_FOLDER
      - AZURE_WORKFLOW_IMPORT_FOLDER
      - AZURE_PORTAL_STORAGE_ACCOUNT
      - AZURE_PORTAL_STORAGE_ACCESS_KEY
      - AZURE_PORTAL_FILESHARE_NAME
      - AZURE_PORTAL_EXPORT_FOLDER
      - GOV_NOTIFY_API_KEY
      - GOV_NOTIFY_EMAIL_RECIPIENT
      - DTFS_PORTAL_SCHEDULER=true
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - DTFS_CENTRAL_API=http://dtfs-central-api:5005
      - TFM_API=http://trade-finance-manager-api:5004
      - V1_FILE_SHARE_SAS=${V1_FILE_SHARE_SAS}
      - V1_FILE_SHARE_ACCOUNT=${V1_FILE_SHARE_ACCOUNT}
      - V1_AZURE_PORTAL_FILESHARE_NAME=${V1_AZURE_PORTAL_FILESHARE_NAME}
      - V1_AZURE_PORTAL_EXPORT_FOLDER=${V1_AZURE_PORTAL_EXPORT_FOLDER}
      - TZ=Europe/London

    command: npx nodemon --inspect=0.0.0.0:9227 src/index.js -L

  reference-data-proxy:
    build: ./reference-data-proxy
    image: dtfs/reference-data-proxy
    restart: always
    depends_on:
      - dtfs-submissions-data
    ports:
      - "5002:5002" # http
      - "9228:9228" # debug
    volumes:
      - ./reference-data-proxy/src:/app/src:ro
    environment:
      - PORT=5002
      - COMPANIES_HOUSE_API_URL=https://api.companieshouse.gov.uk
      - COMPANIES_HOUSE_API_KEY
      - ORDNANCE_SURVEY_API_URL=https://api.os.co.uk
      - ORDNANCE_SURVEY_API_KEY
      - MULESOFT_API_KEY
      - MULESOFT_API_SECRET
      - MULESOFT_API_NUMBER_GENERATOR_URL
      - MULESOFT_API_PARTY_DB_KEY
      - MULESOFT_API_PARTY_DB_SECRET
      - MULESOFT_API_PARTY_DB_URL
      - MULESOFT_API_ACBS_DEAL_URL
      - MULESOFT_API_ACBS_FACILITY_URL
      - MULESOFT_API_CURRENCY_EXCHANGE_RATE_URL
      - MULESOFT_API_CURRENCY_EXCHANGE_RATE_KEY
      - MULESOFT_API_CURRENCY_EXCHANGE_RATE_SECRET
      - MULESOFT_API_EXPOSURE_PERIOD_URL
      - MULESOFT_API_UKEF_MDM_EA_URL
      - MULESOFT_API_UKEF_MDM_EA_KEY
      - MULESOFT_API_UKEF_MDM_EA_SECRET
      - MULESOFT_API_UKEF_ESTORE_EA_URL
      - MULESOFT_API_UKEF_ESTORE_EA_KEY
      - MULESOFT_API_UKEF_ESTORE_EA_SECRET
      - AZURE_ACBS_FUNCTION_URL=http://host.docker.internal:7071
      - AZURE_NUMBER_GENERATOR_FUNCTION_URL=http://number-generator-function
      - GOV_NOTIFY_API_KEY
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGODB_URI=mongodb://root:r00t@dtfs-submissions-data:27017/?authMechanism=DEFAULT
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - TZ=Europe/London
    entrypoint: npx nodemon src/index.ts -L --max-old-space-size=300

  gef-ui:
    build: ./gef-ui
    image: dtfs/gef-ui
    restart: always
    depends_on:
      - redis
      - portal-api
    ports:
      - "5006:5006" # http
      - "9229:9229" # debug
    volumes:
      - ./gef-ui/server:/app/server:ro
      - ./gef-ui/public:/app/public:ro
      - ./gef-ui/templates:/app/templates:ro
    environment:
      - DEAL_API_URL=http://portal-api:5001
      - COMPANIES_HOUSE_API_URL=https://api.companieshouse.gov.uk
      - COMPANIES_HOUSE_API_KEY
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - SESSION_SECRET
      - REDIS_HOSTNAME=redis
      - AZURE_PORTAL_STORAGE_ACCOUNT
      - AZURE_PORTAL_STORAGE_ACCESS_KEY
      - TZ=Europe/London
    command: npx nodemon --inspect=0.0.0.0:9229 server/index.js -L --max_old_space_size=250

  number-generator-function:
    build: ./azure-functions/number-generator-function
    image: dtfs/azure-function-number-generator
    restart: always
    ports:
      - "7072:80"
    environment:
      - AzureWebJobsStorage=DefaultEndpointsProtocol=https;AccountName=${AZURE_PORTAL_STORAGE_ACCOUNT};AccountKey=${AZURE_PORTAL_STORAGE_ACCESS_KEY};EndpointSuffix=core.windows.net
      - FUNCTIONS_WORKER_RUNTIME=node
      - WEBSITE_HOSTNAME=localhost:7072
      - MULESOFT_API_UKEF_TF_EA_URL
      - MULESOFT_API_KEY
      - MULESOFT_API_SECRET
      - TZ=Europe/London

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 300M

  reverse-proxy:
    build: ./reverse-proxy
    image: "dtfs/reverse-proxy"
    depends_on:
      - portal
      - gef-ui
    ports:
      - "80:80"
    environment:
      - PORTAL_UI=portal:5000
      - GEF_UI=gef-ui:5006
    deploy:
      resources:
        limits:
          cpus: "0.01"
          memory: 150M
