import { BOND_FACILITY_TYPE } from '@ukef/dtfs2-common';
import mockDeal from '../../../../fixtures/deal';
import CONSTANTS from '../../../../fixtures/constants';
import { CURRENCY, FEE_FREQUENCY, FEE_TYPE, DAY_COUNT_BASIS } from '../../../../../../e2e-fixtures/constants.fixture';
import { today, tomorrow } from '../../../../../../e2e-fixtures/dateConstants';

const deal = {
  ...mockDeal,
  mockFacilities: [
    {
      type: CONSTANTS.FACILITY.FACILITY_TYPE.BOND,
      createdDate: today.unixMilliseconds,
      bondIssuer: '',
      bondType: BOND_FACILITY_TYPE.BID_BOND,
      facilityStage: CONSTANTS.FACILITY.FACILITY_STAGE.ISSUED,
      hasBeenIssued: true,
      'requestedCoverStartDate-day': '13',
      'requestedCoverStartDate-month': '09',
      'requestedCoverStartDate-year': '2022',
      'coverEndDate-day': '06',
      'coverEndDate-month': '01',
      'coverEndDate-year': '2021',
      requestedCoverStartDate: '1663063419194',
      name: '1234',
      bondBeneficiary: '',
      guaranteeFeePayableByBank: '18.0000',
      updatedAt: Date.now(),
      value: '1234.00',
      currencySameAsSupplyContractCurrency: 'false',
      currency: {
        currencyId: 1,
        id: CURRENCY.AED,
        text: CURRENCY.AED_TEXT,
      },
      conversionRate: '5.5',
      'conversionRateDate-day': '28',
      'conversionRateDate-month': '04',
      'conversionRateDate-year': '2022',
      riskMarginFee: '20',
      coveredPercentage: '30',
      minimumRiskMarginFee: '',
      ukefExposure: '370.20',
      feeType: FEE_TYPE.MATURITY,
      dayCountBasis: DAY_COUNT_BASIS[365],
      status: CONSTANTS.DEALS.DEAL_STATUS.UKEF_ACKNOWLEDGED,
    },
    {
      type: CONSTANTS.FACILITY.FACILITY_TYPE.LOAN,
      createdDate: today.unixMilliseconds,
      facilityStage: CONSTANTS.FACILITY.FACILITY_STAGE.CONDITIONAL,
      hasBeenIssued: false,
      ukefGuaranteeInMonths: '12',
      guaranteeFeePayableByBank: '10.8000',
      value: '123123.00',
      currencySameAsSupplyContractCurrency: 'false',
      interestMarginFee: '12',
      coveredPercentage: '20',
      minimumQuarterlyFee: '20',
      ukefExposure: '24,624.60',
      premiumFrequency: FEE_FREQUENCY.MONTHLY,
      premiumType: FEE_TYPE.ARREAR,
      dayCountBasis: DAY_COUNT_BASIS[360],
      viewedPreviewPage: true,
      currency: {
        currencyId: 1,
        id: CURRENCY.AED,
        text: CURRENCY.AED_TEXT,
      },
      conversionRate: '5.5',
      'conversionRateDate-day': '28',
      'conversionRateDate-month': '04',
      'conversionRateDate-year': '2022',
      issuedDate: tomorrow.unixMilliseconds,
      'coverEndDate-day': '06',
      'coverEndDate-month': '01',
      'coverEndDate-year': '2021',
      nameRequiredForIssuance: true,
      issueFacilityDetailsStarted: true,
      issueFacilityDetailsProvided: true,
      disbursementAmount: '1,234.00',
      name: '5678',
      status: CONSTANTS.DEALS.DEAL_STATUS.UKEF_ACKNOWLEDGED,
      updatedAt: Date.now(),
    },
    {
      type: CONSTANTS.FACILITY.FACILITY_TYPE.LOAN,
      createdDate: today.unixMilliseconds,
      facilityStage: CONSTANTS.FACILITY.FACILITY_STAGE.UNCONDITIONAL,
      hasBeenIssued: true,
      'requestedCoverStartDate-day': '13',
      'requestedCoverStartDate-month': '09',
      'requestedCoverStartDate-year': '2022',
      requestedCoverStartDate: '1663063419194',
      'coverEndDate-day': '06',
      'coverEndDate-month': '01',
      'coverEndDate-year': '2021',
      name: '12345678',
      guaranteeFeePayableByBank: '45.0000',
      updatedAt: Date.now(),
      value: '1234.00',
      currencySameAsSupplyContractCurrency: 'true',
      currency: {
        currencyId: 1,
        id: CURRENCY.AED,
        text: CURRENCY.AED_TEXT,
      },
      conversionRate: '5.5',
      'conversionRateDate-day': '28',
      'conversionRateDate-month': '04',
      'conversionRateDate-year': '2022',
      disbursementAmount: '200.00',
      interestMarginFee: '50',
      coveredPercentage: '60',
      minimumQuarterlyFee: '',
      ukefExposure: '740.40',
      premiumType: FEE_TYPE.MATURITY,
      dayCountBasis: DAY_COUNT_BASIS[365],
      status: CONSTANTS.DEALS.DEAL_STATUS.UKEF_ACKNOWLEDGED,
    },
  ],
};

export default deal;
