const REPORT_PERIOD_DISCRIPTORS = {
  CURRENT: 'Current',
  OPEN: 'Open reports',
} as const;

const REPORTING_PERIOD_END = 'reporting period end';

export const BANK_REPORTS_FOR_PERIOD_TABLE_HEADER_PREFIX = {
  CURRENT_PERIOD: `${REPORT_PERIOD_DISCRIPTORS.CURRENT} ${REPORTING_PERIOD_END}`,
  OPEN_PERIOD: `${REPORT_PERIOD_DISCRIPTORS.OPEN} ${REPORTING_PERIOD_END}`,
} as const;
