const REPORT_PERIOD_DISCRIPTORS = {
  CURRENT: 'Current',
  OPEN: 'Open',
} as const;

const REPORTING_PERIOD_METHOD_OF_DESCRIPTION = {
  BY_END: 'reporting period end',
  BY_FULL_PERIOD: 'reporting period',
} as const;

export const BANK_REPORTS_FOR_PERIOD_TABLE_HEADER_PREFIX = {
  CURRENT_PERIOD: `${REPORT_PERIOD_DISCRIPTORS.CURRENT} ${REPORTING_PERIOD_METHOD_OF_DESCRIPTION.BY_FULL_PERIOD}`,
  CURRENT_PERIOD_END: `${REPORT_PERIOD_DISCRIPTORS.CURRENT} ${REPORTING_PERIOD_METHOD_OF_DESCRIPTION.BY_END}`,
  OPEN_PERIOD: `${REPORT_PERIOD_DISCRIPTORS.OPEN} reports`,
  OPEN_PERIOD_END: `${REPORT_PERIOD_DISCRIPTORS.OPEN} ${REPORTING_PERIOD_METHOD_OF_DESCRIPTION.BY_END}`,
} as const;
