const UNDERWRITING_SUPPORT = 'UNDERWRITING_SUPPORT';
const UNDERWRITER_MANAGERS = 'UNDERWRITER_MANAGERS';
const UNDERWRITERS = 'UNDERWRITERS';
const RISK_MANAGERS = 'RISK_MANAGERS';
const BUSINESS_SUPPORT = 'BUSINESS_SUPPORT';
const PIM = 'PIM';

module.exports = {
  UNDERWRITING_SUPPORT,
  UNDERWRITER_MANAGERS,
  UNDERWRITERS,
  RISK_MANAGERS,
  BUSINESS_SUPPORT,
  PIM,
};
