const PDC_TEAM_IDS = {
  PDC_READ: 'PDC_READ',
  PDC_RECONCILE: 'PDC_RECONCILE',
} as const;

const TEAM_IDS = {
  UNDERWRITING_SUPPORT: 'UNDERWRITING_SUPPORT',
  UNDERWRITER_MANAGERS: 'UNDERWRITER_MANAGERS',
  UNDERWRITERS: 'UNDERWRITERS',
  RISK_MANAGERS: 'RISK_MANAGERS',
  BUSINESS_SUPPORT: 'BUSINESS_SUPPORT',
  PIM: 'PIM',
  ...PDC_TEAM_IDS,
} as const;

module.exports = {
  TEAM_IDS,
  PDC_TEAM_IDS,
};
