const CONSTANTS = require('../../constants');

const CREDIT_RATING = {
  AIN: CONSTANTS.DEALS.CREDIT_RATING.ACCEPTABLE,
};

const FACILITY_RISK_PROFILE = CONSTANTS.FACILITIES.FACILITY_RISK_PROFILE.FLAT;

const LOSS_GIVEN_DEFAULT = CONSTANTS.DEALS.LOSS_GIVEN_DEFAULT['50_PERCENT'];

const PROBABILITY_OF_DEFAULT = CONSTANTS.DEALS.PROBABILITY_OF_DEFAULT.DEFAULT_VALUE;

module.exports = {
  CREDIT_RATING,
  FACILITY_RISK_PROFILE,
  LOSS_GIVEN_DEFAULT,
  PROBABILITY_OF_DEFAULT,
};
