# This GitHub Action is designed to deploy the code bases from specified branch to an Azure WebApp

name: 'Deploy Azure WebApp'
description: 'This custom GitHub Actions module deploys from defined source to defined Azure WebApp microservice'

# Define the inputs required for this action.
inputs:
  credentials:
    description: 'Azure subscription and resource group service principal'
    required: true
  branch:
    description: 'Source Git branch, main if none specified'
    required: false
    default: 'main'
  region:
    description: 'Azure region'
    required: true
  group:
    description: 'Azure resource group'
    required: true
  acr:
    description: 'Azure container registry password'
    required: true
  webapp:
    description: 'Azure WebApp name'
    required: true

# Define the steps to run this action.
runs:
  using: 'composite'
  steps:
    # Step 1: Check out the repository.
    - name: Repository ðŸ—ƒï¸
      uses: actions/checkout@v6
      with:
        ref: ${{ inputs.branch }}

    # Step 2: Set up Azure CLI defaults.
    - name: Defaults âœ¨
      uses: azure/cli@v2
      with:
        inlineScript: |
          # Basic
          az configure --defaults location=${{ inputs.region }}
          az configure --defaults group=${{ inputs.group }}

    # Step 3: Log in to Azure.
    - name: Azure ðŸ”
      uses: azure/login@v2
      with:
        creds: ${{ inputs.credentials }}

    # Step 4: Set environment variables for ACR and WebApp.
    - name: CLI ðŸ“
      run: |
        echo ACR=$(az acr show -n $(az resource list --resource-type 'Microsoft.ContainerRegistry/registries' --query '[0].name' -o tsv) --query loginServer -o tsv) >> $GITHUB_ENV
        echo ACR_USER=$(az acr show -n $(az resource list --resource-type 'Microsoft.ContainerRegistry/registries' --query '[0].name' -o tsv) --query name -o tsv) >> $GITHUB_ENV
        echo WEBAPP=$(az resource list --resource-type 'Microsoft.Web/sites' --query '[?contains(name, `${{ inputs.webapp }}`)].name' -o tsv) >> $GITHUB_ENV
      shell: bash

    # Step 5: Log in to Azure Container Registry.
    - name: ACR ðŸ”
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.ACR }}
        username: ${{ env.ACR_USER }}
        password: ${{ inputs.acr }}

    # Step 6: Build and push Docker images.
    - name: Artefacts ðŸ—ƒï¸
      working-directory: .
      run: |
        # Build images
        docker build -f ./${{ inputs.webapp }}/Dockerfile . \
        -t ${{ env.ACR }}/${{ inputs.webapp }}:${{ github.sha }} \
        -t ${{ env.ACR }}/${{ inputs.webapp }}:latest \
        --build-arg GITHUB_SHA=${{ github.sha }}
        # Push images
        docker push ${{ env.ACR }}/${{ inputs.webapp }}:${{ github.sha }}
        docker push ${{ env.ACR }}/${{ inputs.webapp }}:latest
      shell: bash

    # Step 7: Create and swap deployment slot.
    - name: Slot ðŸ”€
      uses: azure/cli@v2
      with:
        inlineScript: |
          # Create new temporary slot
          az webapp deployment slot create \
          --slot ${{ github.sha }} \
          --name ${{ env.WEBAPP }} \
          --configuration-source ${{ env.WEBAPP }} \
          --deployment-container-image-name ${{ env.ACR }}/${{ inputs.webapp }}:latest \
          --docker-registry-server-user ${{ env.ACR_USER }} \
          --docker-registry-server-password ${{ inputs.acr }}

    # Step 8: Wait for slot to be ready.
    - name: Wait â³
      uses: azure/cli@v2
      with:
        inlineScript: |
          # Wait for container to be ready
          echo "Waiting for slot ${{ github.sha }} to be ready..."

          # First, wait for the slot to be running
          COUNTER=0
          while [ $COUNTER -lt 30 ]; do
            STATE=$(az webapp show --name ${{ env.WEBAPP }} --slot ${{ github.sha }} --query 'state' -o tsv)
            echo "Slot state: $STATE"
            if [ "$STATE" == "Running" ]; then
              echo "Slot is running."
              break
            fi
            let COUNTER=COUNTER+1
            sleep 10
          done

          if [ "$STATE" != "Running" ]; then
            echo "Error: Slot did not start within the timeout period."
            exit 1
          fi

          # Next, wait for the application to respond to HTTP requests
          echo "Waiting for application to respond to HTTP requests..."
          SLOT_URL=$(az webapp show --name ${{ env.WEBAPP }} --slot ${{ github.sha }} --query 'hostNames[0]' -o tsv)
          echo "Slot URL: https://$SLOT_URL"

          HTTP_COUNTER=0
          while [ $HTTP_COUNTER -lt 60 ]; do
            # Use wget to test HTTP connectivity (available in Azure CLI container)
            if wget --quiet --spider --timeout=30 "https://$SLOT_URL" 2>/dev/null; then
              HTTP_STATUS="200"
            else
              # If wget fails, try to get more specific status with Python
              HTTP_STATUS=$(python3 -c "import urllib.request,urllib.error; exec('''try:\n response = urllib.request.urlopen('https://$SLOT_URL', timeout=30)\n print(response.status)\nexcept urllib.error.HTTPError as e:\n print(e.code)\nexcept:\n print('000')''')" 2>/dev/null || echo "000")
            fi
            echo "HTTP Status: $HTTP_STATUS"

            # Accept any 2xx, 3xx, 4xx status codes (avoid only 5xx and connection errors)
            if [ "$HTTP_STATUS" -ge 200 ] && [ "$HTTP_STATUS" -lt 500 ]; then
              echo "Application is responding to HTTP requests."
              break
            fi

            let HTTP_COUNTER=HTTP_COUNTER+1
            sleep 10
          done

          if [ "$HTTP_STATUS" -eq "000" ] || [ "$HTTP_STATUS" -ge 500 ]; then
            echo "Error: Application did not respond to HTTP requests within the timeout period."
            echo "Final HTTP Status: $HTTP_STATUS"
            exit 1
          fi

    # Step 9: Swap deployment slot.
    - name: Swap ðŸ”€
      uses: azure/cli@v2
      with:
        inlineScript: |
          # Swap slot
          az webapp deployment slot swap \
          --slot ${{ github.sha }} \
          --name ${{ env.WEBAPP }} \
          --action swap

    # Step 10: Cleanup temporary slot.
    - name: Cleanup ðŸ§¹
      if: always()
      uses: azure/cli@v2
      with:
        inlineScript: |
          # Delete temporary slot
          az webapp deployment slot delete \
          --slot ${{ github.sha }} \
          --name ${{ env.WEBAPP }}
