const CONSTANTS = require('../../../../constants');

const ABOUT_DEAL = {
  SME_TYPE: {
    [CONSTANTS.ABOUT_DEAL.SME_TYPE.MICRO]: '1',
    [CONSTANTS.ABOUT_DEAL.SME_TYPE.SMALL]: '2',
    [CONSTANTS.ABOUT_DEAL.SME_TYPE.MEDIUM]: '3',
    [CONSTANTS.ABOUT_DEAL.SME_TYPE.NOT_KNOWN]: '4',
    [CONSTANTS.ABOUT_DEAL.SME_TYPE.NON_SME]: '5',
  },

  SUPPLIER_TYPE: {
    [CONSTANTS.ABOUT_DEAL.SUPPLIER_TYPE.EXPORTER]: '1',
    [CONSTANTS.ABOUT_DEAL.SUPPLIER_TYPE.UK_SUPPLIER]: '2',
  },
};

const TRANSACTIONS = {

  FEE_TYPE: {
    [CONSTANTS.TRANSACTIONS.FEE_TYPE.ADVANCE]: '1',
    [CONSTANTS.TRANSACTIONS.FEE_TYPE.ARREAR]: '2',
    [CONSTANTS.TRANSACTIONS.FEE_TYPE.MATURITY]: '3',
  },

  FEE_FREQUENCY: {
    [CONSTANTS.TRANSACTIONS.FEE_FREQUENCY.MONTHLY]: '1',
    [CONSTANTS.TRANSACTIONS.FEE_FREQUENCY.QUARTERLY]: '2',
    [CONSTANTS.TRANSACTIONS.FEE_FREQUENCY.SEMI_ANNUALLY]: '3',
    [CONSTANTS.TRANSACTIONS.FEE_FREQUENCY.ANNUALLY]: '4',
  },

  DAY_COUNT_BASIS: {
    [CONSTANTS.TRANSACTIONS.DAY_COUNT_BASIS[360]]: '1',
    [CONSTANTS.TRANSACTIONS.DAY_COUNT_BASIS[300]]: '2',
  },

  STAGE: {
    [CONSTANTS.TRANSACTIONS.STAGE.UNISSUED]: '2',
    [CONSTANTS.TRANSACTIONS.STAGE.ISSUED]: '3',
  },

  TYPE: {
    [CONSTANTS.TRANSACTIONS.TYPE.ADVANCE_PAYMENT_GUARANTEE]: '1',
    [CONSTANTS.TRANSACTIONS.TYPE.BID_BOND]: '2',
    [CONSTANTS.TRANSACTIONS.TYPE.MAINTENANCE_BOND]: '3',
    [CONSTANTS.TRANSACTIONS.TYPE.PERFORMANCE_BOND]: '5',
    [CONSTANTS.TRANSACTIONS.TYPE.PROGRESS_PAYMENT_BOND]: '6',
    [CONSTANTS.TRANSACTIONS.TYPE.RETENTION_BOND]: '7',
    [CONSTANTS.TRANSACTIONS.TYPE.STANDBY_LETTER_OF_CREDIT]: '8',
    [CONSTANTS.TRANSACTIONS.TYPE.WARRANY_LETTER]: '9',
  },
};

module.exports = {
  TRANSACTIONS,
  ABOUT_DEAL,
};
