const {
  UNDERWRITER_MANAGER_1,
  UNDERWRITER_MANAGER_2,
  UNDERWRITER_1,
  BUSINESS_SUPPORT_USER_1,
  BUSINESS_SUPPORT_USER_2,
  T1_USER_1,
  RISK_MANAGER_1,
  UNDERWRITING_SUPPORT_1,
  PIM_USER_1,
} = require('./users');

module.exports = {
  UNDERWRITER_MANAGER_1,
  UNDERWRITER_MANAGER_2,
  UNDERWRITER_1,
  BUSINESS_SUPPORT_USER_1,
  BUSINESS_SUPPORT_USER_2,
  T1_USER_1,
  RISK_MANAGER_1,
  UNDERWRITING_SUPPORT_1,
  PIM_USER_1,
};
