export const ESTORE_SITE_STATUS = {
  CREATED: 'Created',
  PROVISIONING: 'Provisioning',
};

export const ESTORE_CRON_TYPE = {
  DEAL_FOLDER_CREATION: 'DEAL_FOLDER_CREATION',
  SITE_CREATION: 'SITE_CREATION',
  FACILITY_FOLDER_CREATION: 'FACILITY_FOLDER_CREATION',
};

export const ESTORE_CRON_STATUS = {
  PENDING: 'Pending',
  RUNNING: 'Running',
  COMPLETED: 'Completed',
  FAILED: 'Failed',
};
