version: "3" 
services:

    number-generator-function:
    build: ../azure-functions/number-generator-function
    image: dtfs/azure-function-number-generator
    restart: always
    ports:
      - "7072:80"
    volumes:
      - ../azure-functions/number-generator-function:/home/site/wwwroot
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 150M
        reservations:
          cpus: '0.001'
          memory: 60M
    environment:
      - AzureWebJobsStorage=DefaultEndpointsProtocol=https;AccountName=${AZURE_PORTAL_STORAGE_ACCOUNT};AccountKey=${AZURE_PORTAL_STORAGE_ACCESS_KEY};EndpointSuffix=core.windows.net
      - WEBSITE_HOSTNAME=localhost:7072
      - MULESOFT_API_UKEF_TF_EA_URL
      - MULESOFT_API_KEY
      - MULESOFT_API_SECRET
