version: "3"
services:

  user-api-data-test:
    container_name: user-api-data-test
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - ./mongo_volume:/data/db
    ports:
      - "27017-27019:27017-27019"

networks:
  default:
