version: "3" 
services:

  portal:
    build: ../portal
    image: dtfs/portal
    restart: always
    depends_on:
      - portal-api
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ../portal/scripts:/app/scripts:ro
      - ../portal/styles:/app/styles:ro
      - ../portal/templates:/app/templates:ro
      - ../portal/server:/app/server:ro
    environment:
      - DEAL_API_URL=http://portal-api:5001
      - COMPANIES_HOUSE_API_URL=https://api.companieshouse.gov.uk
      - COMPANIES_HOUSE_API_KEY
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - SESSION_SECRET
      - REDIS_HOSTNAME=redis
    command: node dist/server.js

  dtfs-submissions-data:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=r00t
    volumes:
      - ../dtfs-submissions-data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./dtfs-submissions-data-volume-dtfs-submissions:/data/db
    ports:
      - "27017-27019:27017-27019"

  dtfs-central-api:
    build: ../dtfs-central-api
    image: dtfs/dtfs-central-api
    restart: always
    depends_on:
      - dtfs-submissions-data
      - reference-data-proxy
    ports:
      - "5005:5005"
    volumes:
      - ../dtfs-central-api/src:/app/src:ro
    environment:
      - PORT=5005
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGODB_URI=mongodb://root:r00t@dtfs-submissions-data:27017/?authMechanism=DEFAULT
    entrypoint: npx nodemon src/index.js

  portal-api:
    build: ../portal-api
    image: dtfs/portal-api
    restart: always
    depends_on:
      - dtfs-central-api
      - reference-data-proxy
    ports:
      - "5001:5001"
    volumes:
      - ../portal-api/src:/app/src:ro
    environment:
      - DEBUG=express:*
      - PORT=5001
      - CORS_ORIGIN=http://localhost:5000
      - JWT_SIGNING_KEY
      - JWT_VALIDATING_KEY
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGODB_URI=mongodb://root:r00t@dtfs-submissions-data:27017/?authMechanism=DEFAULT
      - AZURE_WORKFLOW_FILESHARE_NAME
      - AZURE_WORKFLOW_STORAGE_ACCOUNT
      - AZURE_WORKFLOW_STORAGE_ACCESS_KEY
      - AZURE_WORKFLOW_EXPORT_FOLDER
      - AZURE_WORKFLOW_IMPORT_FOLDER
      - AZURE_PORTAL_FILESHARE_NAME
      - AZURE_PORTAL_STORAGE_ACCOUNT
      - AZURE_PORTAL_STORAGE_ACCESS_KEY
      - AZURE_PORTAL_EXPORT_FOLDER
      - GOV_NOTIFY_API_KEY
      - GOV_NOTIFY_EMAIL_RECIPIENT
      - DTFS_PORTAL_SCHEDULER
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - DTFS_CENTRAL_API=http://dtfs-central-api:5005
      - TFM_API=http://trade-finance-manager-api:5004
    entrypoint: npx nodemon src/index.js
  
  trade-finance-manager-api:
    build: ../trade-finance-manager-api
    image: dtfs/trade-finance-manager-api
    restart: always
    depends_on:
      - portal-api
      - dtfs-central-api
      - reference-data-proxy
    ports:
      - "5004:5004"
    volumes:
      - ../trade-finance-manager-api/src:/app/src:ro
    environment:
      - PORT=5004
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - MONGO_INITDB_DATABASE=dtfs-submissions
      - MONGODB_URI=mongodb://root:r00t@dtfs-submissions-data:27017/?authMechanism=DEFAULT
      - DTFS_CENTRAL_API=http://dtfs-central-api:5005
      - UKEF_TFM_API_SYSTEM_KEY
      - UKEF_TFM_API_REPORTS_KEY
    entrypoint: npx nodemon src/index.js

  gef-ui:
    build: ../gef-ui
    image: dtfs/gef-ui
    restart: always
    depends_on:
      - redis
      - portal-api
    ports:
      - "5006:5006"
    volumes:
      - ../gef-ui/scripts:/app/scripts:ro
      - ../gef-ui/styles:/app/styles:ro
      - ../gef-ui/templates:/app/templates:ro
      - ../gef-ui/server:/app/server:ro
    environment:
      - DEAL_API_URL=http://portal-api:5001
      - COMPANIES_HOUSE_API_URL=https://api.companieshouse.gov.uk
      - COMPANIES_HOUSE_API_KEY
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
      - SESSION_SECRET
      - REDIS_HOSTNAME=redis
    command: node dist/server.js
    
  reference-data-proxy:
    build: ../reference-data-proxy
    image: dtfs/reference-data-proxy
    restart: always
    ports:
      - "5002:5002"
    volumes:
      - ../reference-data-proxy/src:/app/src:ro
    environment:
      - PORT=5002
      - COMPANIES_HOUSE_API_URL=https://api.companieshouse.gov.uk
      - COMPANIES_HOUSE_API_KEY
      - ORDNANCE_SURVEY_API_URL=https://api.ordnancesurvey.co.uk
      - ORDNANCE_SURVEY_API_KEY
      - MULESOFT_API_KEY
      - MULESOFT_API_SECRET
      - MULESOFT_API_NUMBER_GENERATOR_URL
      - MULESOFT_API_PARTY_DB_KEY
      - MULESOFT_API_PARTY_DB_SECRET
      - MULESOFT_API_PARTY_DB_URL
      - MULESOFT_API_ACBS_DEAL_URL
      - MULESOFT_API_ACBS_FACILITY_URL
      - MULESOFT_API_CURRENCY_EXCHANGE_RATE_URL
      - MULESOFT_API_CURRENCY_EXCHANGE_RATE_KEY
      - MULESOFT_API_CURRENCY_EXCHANGE_RATE_SECRET
      - MULESOFT_API_EXPOSURE_PERIOD_URL
      - MULESOFT_API_UKEF_MDM_EA_URL
      - MULESOFT_API_UKEF_MDM_EA_KEY
      - MULESOFT_API_UKEF_MDM_EA_SECRET
      - MULESOFT_API_UKEF_ESTORE_EA_URL
      - MULESOFT_API_UKEF_ESTORE_EA_KEY
      - MULESOFT_API_UKEF_ESTORE_EA_SECRET
      - AZURE_ACBS_FUNCTION_URL=http://host.docker.internal:7071
      - GOV_NOTIFY_API_KEY
    entrypoint: npx nodemon src/index.js

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  reverse-proxy:
    build: ../reverse-proxy
    image: "dtfs/reverse-proxy"
    depends_on:
      - portal
    ports:
      - "80:80"
    environment:
      - PORTAL_UI=portal:5000
      - GEF_UI=host.docker.internal:5006

  acbs-function:
    build: ../azure-functions/acbs-function
    image: dtfs/azure-function-acbs
    restart: always
    ports:
      - "7071:80"
    environment:
      - AzureWebJobsStorage=DefaultEndpointsProtocol=https;AccountName=${AZURE_PORTAL_STORAGE_ACCOUNT};AccountKey=${AZURE_PORTAL_STORAGE_ACCESS_KEY};EndpointSuffix=core.windows.net
      - WEBSITE_HOSTNAME=localhost:7071
      - MULESOFT_API_KEY
      - MULESOFT_API_SECRET
      - MULESOFT_API_UKEF_TF_EA_URL
      - MULESOFT_API_UKEF_MDM_EA_URL
      - MULESOFT_API_UKEF_MDM_EA_KEY
      - MULESOFT_API_UKEF_MDM_EA_SECRET

  test-hook-api:
    build: ../test-hook-api
    image: dtfs/test-hook-api
    restart: always
    depends_on:
      - portal-api
    ports:
      - "5069:5069"
    volumes:
      - ../test-hook-api/src:/app/src:ro
    environment:
      - PORT=5069
      - CORS_ORIGIN=http://localhost:5000
      - AZURE_WORKFLOW_STORAGE_ACCOUNT
      - AZURE_WORKFLOW_STORAGE_ACCESS_KEY
      - AZURE_WORKFLOW_FILESHARE_NAME
      - AZURE_WORKFLOW_EXPORT_FOLDER
      - AZURE_WORKFLOW_IMPORT_FOLDER
      - AZURE_PORTAL_STORAGE_ACCOUNT
      - AZURE_PORTAL_STORAGE_ACCESS_KEY
      - AZURE_PORTAL_FILESHARE_NAME
      - AZURE_PORTAL_EXPORT_FOLDER
      - DTFS_PORTAL_SCHEDULER
      - GOV_NOTIFY_API_KEY
      - GOV_NOTIFY_EMAIL_RECIPIENT

    entrypoint: npx nodemon src/index.js
