const MONTHLY_REPORT_PERIOD_SCHEDULE = [
  { startMonth: 1, endMonth: 1 },
  { startMonth: 2, endMonth: 2 },
  { startMonth: 3, endMonth: 3 },
  { startMonth: 4, endMonth: 4 },
  { startMonth: 5, endMonth: 5 },
  { startMonth: 6, endMonth: 6 },
  { startMonth: 7, endMonth: 7 },
  { startMonth: 8, endMonth: 8 },
  { startMonth: 9, endMonth: 9 },
  { startMonth: 10, endMonth: 10 },
  { startMonth: 11, endMonth: 11 },
  { startMonth: 12, endMonth: 12 },
];

export const MOCK_BANKS = {
  TestBank1: {
    id: '956',
    name: 'Test Bank 1',
    mga: ['Test.pdf'],
    emails: ['maker4@ukexportfinance.gov.uk', 'checker4@ukexportfinance.gov.uk'],
    companiesHouseNo: '01026167',
    partyUrn: '00300130',
    hasGefAccessOnly: false,
    paymentOfficerTeam: {
      teamName: 'Test Bank 1 Payment Reporting Team',
      emails: ['payment-officer4@ukexportfinance.gov.uk'],
    },
    utilisationReportPeriodSchedule: MONTHLY_REPORT_PERIOD_SCHEDULE,
    isVisibleInTfmUtilisationReports: true,
  },
  TestBank2: {
    id: '961',
    name: 'Test Bank 2',
    mga: ['Test.pdf'],
    emails: ['checker4@ukexportfinance.gov.uk'],
    companiesHouseNo: '00014259',
    partyUrn: '00300342',
    hasGefAccessOnly: false,
    paymentOfficerTeam: {
      teamName: 'Test Bank 2 Payment Reporting Team',
      emails: ['payment-officer4@ukexportfinance.gov.uk'],
    },
    utilisationReportPeriodSchedule: MONTHLY_REPORT_PERIOD_SCHEDULE,
    isVisibleInTfmUtilisationReports: true,
  },
  NEWABLE: {
    id: '5213',
    name: 'Newable',
    mga: ['Test.pdf'],
    emails: ['checker4@ukexportfinance.gov.uk'],
    companiesHouseNo: '08796862',
    partyUrn: '00319394',
    hasGefAccessOnly: false,
    paymentOfficerTeam: {
      teamName: 'Newable Payment Reporting Team',
      emails: ['payment-officer4@ukexportfinance.gov.uk'],
    },
    utilisationReportPeriodSchedule: MONTHLY_REPORT_PERIOD_SCHEDULE,
    isVisibleInTfmUtilisationReports: true,
  },
  TestBank3: {
    id: '964',
    name: 'Test Bank 3',
    mga: ['Test.pdf'],
    emails: ['checker4@ukexportfinance.gov.uk'],
    companiesHouseNo: '00002065',
    partyUrn: '00300302',
    hasGefAccessOnly: false,
    paymentOfficerTeam: {
      teamName: 'Test Bank 3 Payment Reporting Team',
      emails: ['payment-officer4@ukexportfinance.gov.uk'],
    },
    utilisationReportPeriodSchedule: [
      { startMonth: 12, endMonth: 2 },
      { startMonth: 3, endMonth: 5 },
      { startMonth: 6, endMonth: 8 },
      { startMonth: 9, endMonth: 11 },
    ],
    isVisibleInTfmUtilisationReports: true,
  },
} as const;
