const { mandatoryCriteria, ELIGIBILITY_COMPLETED, SUBMISSION_DETAILS } = require('../../../../../../e2e-fixtures');

const deal = {
  submissionType: 'Manual Inclusion Notice',
  updatedAt: Date.now(),
  bankInternalRefName: 'DTFS2-2815 MIN - pre submit',
  additionalRefName: 'DTFS2-2815 MIN - pre submit',
  status: "Ready for Checker's approval",
  previousStatus: 'Acknowledged',
  bank: {
    id: '9',
    name: 'UKEF test bank (Delegated)',
    emails: [
      'maker@ukexportfinance.gov.uk',
      'checker@ukexportfinance.gov.uk',
    ],
  },
  maker: {
    _id: '5f3ab3f705e6630007dcfb25',
    username: 'maker1@ukexportfinance.gov.uk',
    roles: [
      'maker',
    ],
    bank: {
      id: '9',
      name: 'UKEF test bank (Delegated)',
      emails: [
        'maker@ukexportfinance.gov.uk',
        'checker@ukexportfinance.gov.uk',
      ],
    },
    lastLogin: '1606899737029',
    firstname: 'Hugo',
    surname: 'Drax',
    email: 'maker1@ukexportfinance.gov.uk',
    timezone: 'Europe/London',
    'user-status': 'active',
  },
  details: {
    created: '1606900241023',
    submissionDate: '1606900616651',
    checker: {
      _id: '5f3ab3f705e6630007dcfb29',
      username: 'checker1@ukexportfinance.gov.uk',
      roles: [
        'checker',
      ],
      bank: {
        id: '9',
        name: 'UKEF test bank (Delegated)',
        emails: [
          'maker@ukexportfinance.gov.uk',
          'checker@ukexportfinance.gov.uk',
        ],
      },
      lastLogin: '1606900578887',
      firstname: 'Emilio',
      surname: 'Largo',
      email: 'checker1@ukexportfinance.gov.uk',
      timezone: 'Europe/London',
      'user-status': 'active',
    },
    manualInclusionApplicationSubmissionDate: '1606900616669',
    ukefDealId: '0040004828',
    approvalDate: '1606912140306',
    makerMIN: {
      _id: '5f3ab3f705e6630007dcfb25',
      username: 'maker1@ukexportfinance.gov.uk',
      roles: [
        'maker',
      ],
      bank: {
        id: '9',
        name: 'UKEF test bank (Delegated)',
        emails: [
          'maker@ukexportfinance.gov.uk',
          'checker@ukexportfinance.gov.uk',
        ],
      },
      lastLogin: '1606901020715',
      firstname: 'Hugo',
      surname: 'Drax',
      email: 'maker1@ukexportfinance.gov.uk',
      timezone: 'Europe/London',
      'user-status': 'active',
    },
    manualInclusionNoticeSubmissionDate: '1606912256510',
    checkerMIN: {
      _id: '5f3ab3f705e6630007dcfb29',
      username: 'checker1@ukexportfinance.gov.uk',
      roles: [
        'checker',
      ],
      bank: {
        id: '9',
        name: 'UKEF test bank (Delegated)',
        emails: [
          'maker@ukexportfinance.gov.uk',
          'checker@ukexportfinance.gov.uk',
        ],
      },
      lastLogin: '1606912247772',
      firstname: 'Emilio',
      surname: 'Largo',
      email: 'checker1@ukexportfinance.gov.uk',
      timezone: 'Europe/London',
      'user-status': 'active',
    },
  },
  eligibility: ELIGIBILITY_COMPLETED,
  submissionDetails: SUBMISSION_DETAILS,
  bondTransactions: {
    items: [
      {
        _id: '5f3ab3f705e6630007dcfb21',
        facilityStage: 'Issued',
        hasBeenIssued: true,
        ukefGuaranteeInMonths: '24',
        value: '100000.00',
        currencySameAsSupplyContractCurrency: 'true',
        createdDate: '1606900240957',
        bondIssuer: '',
        bondType: 'Performance bond',
        bondBeneficiary: '',
        guaranteeFeePayableByBank: '1.8000',
        ukefExposure: '80,000.00',
        updatedAt: Date.now(),
        riskMarginFee: '2',
        coveredPercentage: '80',
        minimumRiskMarginFee: '',
        feeFrequency: 'Monthly',
        feeType: 'In arrear',
        dayCountBasis: '365',
        currency: {
          text: 'GBP - UK Sterling',
          id: 'GBP',
        },
        requestedCoverStartDate: '1603292441000',
        ukefFacilityId: '0040004839',
        'issuedDate-day': '02',
        'issuedDate-month': '12',
        'issuedDate-year': '2020',
        'requestedCoverStartDate-day': '02',
        'requestedCoverStartDate-month': '12',
        'requestedCoverStartDate-year': '2020',
        'coverEndDate-day': '02',
        'coverEndDate-month': '12',
        'coverEndDate-year': '2022',
        name: 'Date set',
        issueFacilityDetailsStarted: true,
        nameRequiredForIssuance: true,
        issuedDate: '1606914071515',
        issueFacilityDetailsProvided: true,
        previousFacilityStage: 'Unissued',
        status: 'Ready for check',
      },
      {
        _id: '5f3ab3f705e6630007dcfb22',
        facilityStage: 'Issued',
        hasBeenIssued: true,
        ukefGuaranteeInMonths: '24',
        value: '100000.00',
        currencySameAsSupplyContractCurrency: 'true',
        createdDate: '1606900240907',
        bondIssuer: '',
        bondType: 'Maintenance bond',
        bondBeneficiary: '',
        guaranteeFeePayableByBank: '1.8000',
        ukefExposure: '80,000.00',
        updatedAt: Date.now(),
        riskMarginFee: '2',
        coveredPercentage: '80',
        minimumRiskMarginFee: '',
        feeType: 'At maturity',
        dayCountBasis: '360',
        currency: {
          text: 'GBP - UK Sterling',
          id: 'GBP',
        },
        ukefFacilityId: '0040004846',
        'issuedDate-day': '02',
        'issuedDate-month': '12',
        'issuedDate-year': '2020',
        'requestedCoverStartDate-day': '',
        'requestedCoverStartDate-month': '',
        'requestedCoverStartDate-year': '',
        'coverEndDate-day': '02',
        'coverEndDate-month': '12',
        'coverEndDate-year': '2022',
        name: 'Default date',
        issueFacilityDetailsStarted: true,
        nameRequiredForIssuance: true,
        issuedDate: '1606914091564',
        issueFacilityDetailsProvided: true,
        previousFacilityStage: 'Unissued',
        status: 'Ready for check',
        requestedCoverStartDate: '1603292441000',
      },
    ],
  },
  loanTransactions: {
    items: [
      {
        _id: '5f3ab3f705e6630007dcfb23',
        ukefGuaranteeInMonths: '24',
        name: 'Date set',
        value: '100000.00',
        currencySameAsSupplyContractCurrency: 'true',
        createdDate: '1606900240970',
        facilityStage: 'Unconditional',
        hasBeenIssued: true,
        guaranteeFeePayableByBank: '1.8000',
        ukefExposure: '80,000.00',
        updatedAt: Date.now(),
        interestMarginFee: '2',
        coveredPercentage: '80',
        minimumQuarterlyFee: '',
        premiumType: 'At maturity',
        dayCountBasis: '365',
        currency: {
          text: 'GBP - UK Sterling',
          id: 'GBP',
        },
        requestedCoverStartDate: '1606914111885',
        ukefFacilityId: '0040004833',
        'issuedDate-day': '02',
        'issuedDate-month': '12',
        'issuedDate-year': '2020',
        'requestedCoverStartDate-day': '02',
        'requestedCoverStartDate-month': '12',
        'requestedCoverStartDate-year': '2020',
        'coverEndDate-day': '02',
        'coverEndDate-month': '12',
        'coverEndDate-year': '2022',
        disbursementAmount: '50,000.00',
        issueFacilityDetailsStarted: true,
        nameRequiredForIssuance: true,
        issuedDate: '1606914111885',
        issueFacilityDetailsProvided: true,
        previousFacilityStage: 'Conditional',
        status: 'Ready for check',
      },
      {
        _id: '5f3ab3f705e6630007dcfb24',
        ukefGuaranteeInMonths: '24',
        name: 'Default date',
        value: '100000.00',
        currencySameAsSupplyContractCurrency: 'true',
        createdDate: '1606900241008',
        facilityStage: 'Unconditional',
        hasBeenIssued: true,
        guaranteeFeePayableByBank: '1.8000',
        ukefExposure: '80,000.00',
        updatedAt: Date.now(),
        interestMarginFee: '2',
        coveredPercentage: '80',
        minimumQuarterlyFee: '',
        premiumFrequency: 'Quarterly',
        premiumType: 'In arrear',
        dayCountBasis: '365',
        currency: {
          text: 'GBP - UK Sterling',
          id: 'GBP',
        },
        ukefFacilityId: '0040004838',
        'issuedDate-day': '02',
        'issuedDate-month': '12',
        'issuedDate-year': '2020',
        'requestedCoverStartDate-day': '',
        'requestedCoverStartDate-month': '',
        'requestedCoverStartDate-year': '',
        'coverEndDate-day': '02',
        'coverEndDate-month': '12',
        'coverEndDate-year': '2022',
        disbursementAmount: '50,000.00',
        issueFacilityDetailsStarted: true,
        nameRequiredForIssuance: true,
        issuedDate: '1606914132468',
        issueFacilityDetailsProvided: true,
        previousFacilityStage: 'Conditional',
        status: 'Ready for check',
        requestedCoverStartDate: '1606912250001',
      },
    ],
  },
  comments: [
    {
      user: {
        _id: '5f3ab3f705e6630007dcfb25',
        username: 'maker1@ukexportfinance.gov.uk',
        roles: [
          'maker',
        ],
        bank: {
          id: '9',
          name: 'UKEF test bank (Delegated)',
          emails: [
            'maker@ukexportfinance.gov.uk',
            'checker@ukexportfinance.gov.uk',
          ],
        },
        lastLogin: '1606912269649',
        firstname: 'Hugo',
        surname: 'Drax',
        email: 'maker1@ukexportfinance.gov.uk',
        timezone: 'Europe/London',
        'user-status': 'active',
      },
      timestamp: '1606914139577',
      text: 'test',
    },
    {
      user: {
        _id: '5f3ab3f705e6630007dcfb25',
        username: 'maker1@ukexportfinance.gov.uk',
        roles: [
          'maker',
        ],
        bank: {
          id: '9',
          name: 'UKEF test bank (Delegated)',
          emails: [
            'maker@ukexportfinance.gov.uk',
            'checker@ukexportfinance.gov.uk',
          ],
        },
        lastLogin: '1606901020715',
        firstname: 'Hugo',
        surname: 'Drax',
        email: 'maker1@ukexportfinance.gov.uk',
        timezone: 'Europe/London',
        'user-status': 'active',
      },
      timestamp: '1606912233615',
      text: 'test',
    },
    {
      user: {
        _id: '5f3ab3f705e6630007dcfb25',
        username: 'maker1@ukexportfinance.gov.uk',
        roles: [
          'maker',
        ],
        bank: {
          id: '9',
          name: 'UKEF test bank (Delegated)',
          emails: [
            'maker@ukexportfinance.gov.uk',
            'checker@ukexportfinance.gov.uk',
          ],
        },
        lastLogin: '1606899737029',
        firstname: 'Hugo',
        surname: 'Drax',
        email: 'maker1@ukexportfinance.gov.uk',
        timezone: 'Europe/London',
        'user-status': 'active',
      },
      timestamp: '1606900373442',
      text: 'DTFS2-2815 MIN - pre submit',
    },
  ],
  editedBy: [],
  mandatoryCriteria,
};

module.exports = deal;
