const BANKS = [
  {
    id: '956',
    name: 'Barclays Bank',
    mga: ['Test.pdf'],
    emails: ['maker4@ukexportfinance.gov.uk', 'checker4@ukexportfinance.gov.uk'],
    companiesHouseNo: '01026167',
    partyUrn: '00300130',
    hasGefAccessOnly: false,
  },
  {
    id: '961',
    name: 'HSBC',
    mga: ['Test.pdf'],
    emails: ['checker4@ukexportfinance.gov.uk'],
    companiesHouseNo: '00014259',
    partyUrn: '00300342',
    hasGefAccessOnly: false,
  },
  {
    id: '999',
    name: 'GEF Only Bank',
    mga: ['Test.pdf'],
    emails: ['checker4@ukexportfinance.gov.uk'],
    companiesHouseNo: '00010452',
    partyUrn: '00300312',
    hasGefAccessOnly: true,
  },
  {
    id: '5213',
    name: 'Newable',
    mga: [''],
    emails: ['checker4@ukexportfinance.gov.uk'],
    companiesHouseNo: '08796862',
    partyUrn: '00319394',
    hasGefAccessOnly: false,
  },
  {
    id: '964',
    name: 'LLOYDS',
    mga: ['Test.pdf'],
    emails: ['checker4@ukexportfinance.gov.uk'],
    companiesHouseNo: '00002065',
    partyUrn: '00300302',
    hasGefAccessOnly: false,
  },
  {
    id: '1004',
    name: 'RBS',
    mga: ['Mock.pdf'],
    emails: ['checker4@ukexportfinance.gov.uk'],
    companiesHouseNo: 'SC090312',
    partyUrn: '00307351',
    hasGefAccessOnly: false,
  },
  {
    id: '953',
    name: 'Santander',
    mga: ['Mock.pdf'],
    emails: ['checker4@ukexportfinance.gov.uk'],
    companiesHouseNo: '02294747',
    partyUrn: '00311081',
    hasGefAccessOnly: false,
  },
  {
    id: '9',
    name: 'UKEF test bank (Delegated)',
    mga: ['mga_ukef_1.docx', 'mga_ukef_2.docx'],
    emails: ['maker1@ukexportfinance.gov.uk', 'checker1@ukexportfinance.gov.uk'],
    companiesHouseNo: 'UKEF0001',
    partyUrn: '00318345',
    hasGefAccessOnly: false,
  },
  {
    id: '10',
    name: 'UKEF test bank (Delegated) 2',
    mga: ['mga_ukef_1.docx', 'mga_ukef_2.docx'],
    emails: ['maker4@ukexportfinance.gov.uk', 'checker4@ukexportfinance.gov.uk'],
    companiesHouseNo: 'UKEF0001',
    partyUrn: '00318345',
    hasGefAccessOnly: false,
  },
];

module.exports = BANKS;
