export const API_ERROR_CODE = {
  INVALID_MONGO_ID_PATH_PARAMETER: 'INVALID_MONGO_ID_PATH_PARAMETER',
  INVALID_SQL_ID_PATH_PARAMETER: 'INVALID_SQL_ID_PATH_PARAMETER',
  INVALID_AUDIT_DETAILS: 'INVALID_AUDIT_DETAILS',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  INVALID_USER_SESSION: 'INVALID_USER_SESSION',
} as const;
