export const ERROR_CODE = {
  PAYMENT_HAS_NO_FEE_RECORDS_ERROR: 'PAYMENT_HAS_NO_FEE_RECORDS_ERROR',
  PAYMENT_AND_FEE_RECORD_CURRENCY_DOES_NOT_MATCH: 'PAYMENT_AND_FEE_RECORD_CURRENCY_DOES_NOT_MATCH',
} as const;
