export const FEE_RECORD_STATUS = {
  TO_DO: 'TO_DO',
  MATCH: 'MATCH',
  DOES_NOT_MATCH: 'DOES_NOT_MATCH',
  READY_TO_KEY: 'READY_TO_KEY',
  RECONCILED: 'RECONCILED',
  REPORT_COMPLETED: 'REPORT_COMPLETED',
} as const;
