export const RECORD_CORRECTION_REQUEST_REASON = {
  FACILITY_ID_INCORRECT: 'FACILITY_ID_INCORRECT',
  REPORTED_FEE_INCORRECT: 'REPORTED_FEE_INCORRECT',
  REPORTED_CURRENCY_INCORRECT: 'REPORTED_CURRENCY_INCORRECT',
  UTILISATION_INCORRECT: 'UTILISATION_INCORRECT',
  OTHER: 'OTHER',
} as const;
