export const REPORT_NOT_RECEIVED = 'REPORT_NOT_RECEIVED';

export const PENDING_RECONCILIATION = 'PENDING_RECONCILIATION';

export const RECONCILIATION_IN_PROGRESS = 'RECONCILIATION_IN_PROGRESS';

export const RECONCILIATION_COMPLETED = 'RECONCILIATION_COMPLETED';

export const UTILISATION_REPORT_RECONCILIATION_STATUS = {
  REPORT_NOT_RECEIVED,
  PENDING_RECONCILIATION,
  RECONCILIATION_IN_PROGRESS,
  RECONCILIATION_COMPLETED,
} as const;
