const FACILITY_TYPE = {
  BOND: 'Bond',
  LOAN: 'Loan',
  CASH: 'Cash',
  CONTINGENT: 'Contingent',
};

const FACILITY_PRODUCT_GROUP = {
  LOAN: 'EW',
  BOND: 'BS',
};

const FACILITY_PRODUCT_CODE = {
  BOND: 'BSS',
  LOAN: 'EWCS',
  GEF: 'GEF',
};

const FACILITY_PRODUCT_NAME = {
  BOND: 'Bond Support Scheme',
  LOAN: 'Export Working Capital Scheme',
  CASH: 'Cash',
  CONTINGENT: 'Contingent',
  GEF: 'General export facility',
};

const FACILITY_FEE_TYPE_PORTAL = {
  IN_ADVANCE: 'In advance',
  IN_ARREARS: 'In arrear',
  AT_MATURITY: 'At maturity',
};

const FACILITY_FEE_TYPE_GEF = {
  IN_ARREARS_MONTHLY: 'IN_ARREARS_MONTHLY',
  IN_ARREARS_QUARTLY: 'IN_ARREARS_QUARTLY',
  IN_ARREARS_SEMI_ANNUALLY: 'IN_ARREARS_SEMI_ANNUALLY',
  IN_ARREARS_ANNUALLY: 'IN_ARREARS_ANNUALLY',
  IN_ADVANCE_QUARTERLY: 'IN_ADVANCE_QUARTERLY',
  IN_ADVANCE_MONTHLY: 'IN_ADVANCE_MONTHLY',
  IN_ADVANCE_SEMI_ANNUALLY: 'IN_ADVANCE_SEMI_ANNUALLY',
  IN_ADVANCE_ANNUALLY: 'IN_ADVANCE_ANNUALLY',
  AT_MATURITY: 'AT_MATURITY',
};

const FACILITY_FEE_TYPE = {
  IN_ADVANCE: 'In advance',
  IN_ARREARS: 'In arrear',
  AT_MATURITY: 'At maturity',
};

const FACILITY_FEE_FREQUENCY_PORTAL = {
  MONTHLY: 'Monthly',
  QUARTERLY: 'Quarterly',
  SEMI_ANNUALLY: 'Semi-annually',
  ANNUALLY: 'Annually',
};

const FACILITY_PREMIUM_FREQUENCY_ID = {
  UNDEFINED: 0,
  MONTHLY: 1,
  QUARTERLY: 2,
  SEMI_ANNUALLY: 3,
  ANNUALLY: 4,
};

const FACILITY_PREMIUM_TYPE_ID = {
  UNDEFINED: 0,
  IN_ADVANCE: 1,
  IN_ARREARS: 2,
  AT_MATURITY: 3,
};

const FACILITY_STAGE_PORTAL = {
  UNISSUED: 'Unissued',
  ISSUED: 'Issued',
  CONDITIONAL: 'Conditional',
  UNCONDITIONAL: 'Unconditional',
};

const FACILITY_STAGE = {
  COMMITMENT: 'Commitment',
  ISSUED: 'Issued',
};

const ACBS_FACILITY_STAGE = {
  COMMITMENT: '06',
  ISSUED: '07',
};

const FACILITY_RISK_PROFILE = {
  FLAT: 'Flat',
};

const FACILITY_STATUS_PORTAL = {
  ACKNOWLEDGED: 'Acknowledged by UKEF',
};

module.exports = {
  FACILITY_TYPE,
  FACILITY_PRODUCT_GROUP,
  FACILITY_PRODUCT_CODE,
  FACILITY_PRODUCT_NAME,
  FACILITY_STAGE_PORTAL,
  ACBS_FACILITY_STAGE,
  FACILITY_STAGE,
  FACILITY_RISK_PROFILE,
  FACILITY_STATUS_PORTAL,
  FACILITY_PREMIUM_FREQUENCY_ID,
  FACILITY_PREMIUM_TYPE_ID,
  FACILITY_FEE_TYPE_PORTAL,
  FACILITY_FEE_FREQUENCY_PORTAL,
  FACILITY_FEE_TYPE_GEF,
  FACILITY_FEE_TYPE,
};
