const { MAKER, CHECKER } = require('../../../src/v1/roles/roles');

module.exports = {
  noBankNoRole: {
    username: 'noBankNoRole@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'One',
    email: 'noBankNoRole@ukexportfinance.gov.uk',
    roles: [],
    isTrusted: false,
  },
  barclaysBankMaker1: {
    username: 'barclaysBankMaker1@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Two',
    email: 'barclaysBankMaker1@ukexportfinance.gov.uk',
    roles: [MAKER],
    bank: {
      id: '956',
      name: 'Barclays Bank',
      emails: ['maker4@ukexportfinance.gov.uk', 'checker4@ukexportfinance.gov.uk'],
    },
    isTrusted: false,
  },
  barclaysBankMaker2: {
    username: 'barclaysBankMaker2@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Two',
    email: 'barclaysBankMaker2@ukexportfinance.gov.uk',
    roles: [MAKER],
    bank: {
      id: '956',
      name: 'Barclays Bank',
      emails: ['maker4@ukexportfinance.gov.uk', 'checker4@ukexportfinance.gov.uk'],
    },
    isTrusted: false,
  },
  barclaysBankChecker1: {
    username: 'barclaysBankChecker1@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Three',
    email: 'barclaysBankChecker1@ukexportfinance.gov.uk',
    roles: [CHECKER],
    bank: {
      id: '956',
      name: 'Barclays Bank',
      emails: ['maker4@ukexportfinance.gov.uk', 'checker4@ukexportfinance.gov.uk'],
    },
    isTrusted: false,
  },
  barclaysBankMakerChecker1: {
    username: 'barclaysBankMakerChecker1@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Four',
    email: 'barclaysBankMakerChecker1@ukexportfinance.gov.uk',
    roles: [MAKER, CHECKER],
    bank: {
      id: '956',
      name: 'Barclays Bank',
      emails: ['maker4@ukexportfinance.gov.uk', 'checker4@ukexportfinance.gov.uk'],
    },
    isTrusted: false,
  },
  barclaysBankReader1: {
    username: 'barclaysBankReader1@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Five',
    email: 'barclaysBankReader1@ukexportfinance.gov.uk',
    roles: ['reader'],
    bank: {
      id: '956',
      name: 'Barclays Bank',
      emails: ['maker4@ukexportfinance.gov.uk', 'checker4@ukexportfinance.gov.uk'],
    },
    isTrusted: false,
  },
  hsbcBankMaker1: {
    username: 'hsbcBankMaker1@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Six',
    email: 'hsbcBankMaker1@ukexportfinance.gov.uk',
    roles: [MAKER],
    bank: {
      id: '961',
      name: 'HSBC',
    },
    isTrusted: false,
  },
  hsbcBankChecker1: {
    username: 'hsbcBankChecker1@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Seven',
    email: 'hsbcBankChecker1@ukexportfinance.gov.uk',
    roles: [CHECKER],
    bank: {
      id: '961',
      name: 'HSBC',
    },
    isTrusted: false,
  },
  hsbcBankMakerChecker1: {
    username: 'hsbcBankMakerChecker1@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Eight',
    email: 'hsbcBankMakerChecker1@ukexportfinance.gov.uk',
    roles: [MAKER, CHECKER],
    bank: {
      id: '961',
      name: 'HSBC',
    },
    isTrusted: false,
  },
  hsbcBankReader1: {
    username: 'hsbcBankReader1@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Nine',
    email: 'hsbcBankReader1@ukexportfinance.gov.uk',
    roles: ['reader'],
    bank: {
      id: '961',
      name: 'HSBC',
    },
    isTrusted: false,
  },
};
