const { MAKER, CHECKER } = require('../../../src/v1/roles/roles');

module.exports = {
  noBankNoRole: {
    username: 'noBankNoRole@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'One',
    email: 'noBankNoRole@ukexportfinance.gov.uk',
    roles: [],
    isTrusted: false,
  },
  Testbank1BankMaker1: {
    username: 'Testbank1BankMaker1@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Two',
    email: 'Testbank1BankMaker1@ukexportfinance.gov.uk',
    roles: [MAKER],
    bank: {
      id: '9',
      name: 'Bank 1',
      emails: ['maker4@ukexportfinance.gov.uk', 'checker4@ukexportfinance.gov.uk'],
    },
    isTrusted: false,
  },
  Testbank1BankMaker2: {
    username: 'Testbank1BankMaker2@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Two',
    email: 'Testbank1BankMaker2@ukexportfinance.gov.uk',
    roles: [MAKER],
    bank: {
      id: '9',
      name: 'Bank 1',
      emails: ['maker4@ukexportfinance.gov.uk', 'checker4@ukexportfinance.gov.uk'],
    },
    isTrusted: false,
  },
  Testbank1BankChecker1: {
    username: 'Testbank1BankChecker1@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Three',
    email: 'Testbank1BankChecker1@ukexportfinance.gov.uk',
    roles: [CHECKER],
    bank: {
      id: '9',
      name: 'Bank 1',
      emails: ['maker4@ukexportfinance.gov.uk', 'checker4@ukexportfinance.gov.uk'],
    },
    isTrusted: false,
  },
  Testbank1BankMakerChecker1: {
    username: 'Testbank1BankMakerChecker1@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Four',
    email: 'Testbank1BankMakerChecker1@ukexportfinance.gov.uk',
    roles: [MAKER, CHECKER],
    bank: {
      id: '9',
      name: 'Bank 1',
      emails: ['maker4@ukexportfinance.gov.uk', 'checker4@ukexportfinance.gov.uk'],
    },
    isTrusted: false,
  },
  Testbank1BankReader1: {
    username: 'Testbank1BankReader1@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Five',
    email: 'Testbank1BankReader1@ukexportfinance.gov.uk',
    roles: ['reader'],
    bank: {
      id: '9',
      name: 'Bank 1',
      emails: ['maker4@ukexportfinance.gov.uk', 'checker4@ukexportfinance.gov.uk'],
    },
    isTrusted: false,
  },
  Testbank2BankMaker1: {
    username: 'Testbank2BankMaker1@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Six',
    email: 'Testbank2BankMaker1@ukexportfinance.gov.uk',
    roles: [MAKER],
    bank: {
      id: '961',
      name: 'Bank 2',
    },
    isTrusted: false,
  },
  Testbank2BankChecker1: {
    username: 'Testbank2BankChecker1@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Seven',
    email: 'Testbank2BankChecker1@ukexportfinance.gov.uk',
    roles: [CHECKER],
    bank: {
      id: '961',
      name: 'Bank 2',
    },
    isTrusted: false,
  },
  Testbank2BankMakerChecker1: {
    username: 'Testbank2BankMakerChecker1@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Eight',
    email: 'Testbank2BankMakerChecker1@ukexportfinance.gov.uk',
    roles: [MAKER, CHECKER],
    bank: {
      id: '961',
      name: 'Bank 2',
    },
    isTrusted: false,
  },
  Testbank2BankReader1: {
    username: 'Testbank2BankReader1@ukexportfinance.gov.uk',
    password: '1!aB5678',
    firstname: 'Miss',
    surname: 'Nine',
    email: 'Testbank2BankReader1@ukexportfinance.gov.uk',
    roles: ['reader'],
    bank: {
      id: '961',
      name: 'Bank 2',
    },
    isTrusted: false,
  },
};
