const { nowPlusDays, nowPlusMonths } = require('../../../../support/utils/dateFuncs');
const { ELIGIBILITY_COMPLETED, SUBMISSION_DETAILS } = require('../../../../../../e2e-fixtures');

const date = new Date();
const datePlusDay = nowPlusDays(1);
const datePlusMonth = nowPlusMonths(1);

const deal = {
  submissionType: 'Automatic Inclusion Notice',
  updatedAt: Date.now(),
  bankInternalRefName: 'mock id',
  additionalRefName: 'mock name',
  status: "Ready for Checker's approval",
  previousStatus: 'Acknowledged',
  bank: {
    id: '9',
    name: 'UKEF test bank (Delegated)',
  },
  details: {
    created: date.valueOf(),
    submissionDate: date.valueOf(),
  },
  eligibility: ELIGIBILITY_COMPLETED,
  submissionDetails: SUBMISSION_DETAILS,
  mockFacilities: [
    {
      type: 'Bond',
      createdDate: date.valueOf(),
      bondIssuer: '',
      bondType: 'Bid bond',
      facilityStage: 'Unissued',
      hasBeenIssued: false,
      ukefGuaranteeInMonths: '12',
      bondBeneficiary: '',
      guaranteeFeePayableByBank: '18.0000',
      value: '21313.00',
      currencySameAsSupplyContractCurrency: 'true',
      riskMarginFee: '20',
      coveredPercentage: '30',
      minimumRiskMarginFee: '',
      ukefExposure: '6,393.90',
      feeType: 'At maturity',
      dayCountBasis: '365',
      currency: {
        text: 'GBP - UK Sterling',
        id: 'GBP',
      },
      issuedDate: datePlusDay.valueOf(),
      'coverEndDate-day': (datePlusMonth.getDate()).toString(),
      'coverEndDate-month': (datePlusMonth.getMonth() + 1).toString(),
      'coverEndDate-year': (datePlusMonth.getFullYear()).toString(),
      name: '1234',
      nameRequiredForIssuance: true,
      issueFacilityDetailsStarted: true,
      issueFacilityDetailsProvided: true,
      status: 'Ready for check',
    },
    {
      type: 'Bond',
      createdDate: date.valueOf(),
      bondIssuer: '',
      bondType: 'Bid bond',
      facilityStage: 'Issued',
      hasBeenIssued: true,
      'requestedCoverStartDate-day': '',
      'requestedCoverStartDate-month': '',
      'requestedCoverStartDate-year': '',
      'coverEndDate-day': (datePlusMonth.getDate()).toString(),
      'coverEndDate-month': (datePlusMonth.getMonth() + 1).toString(),
      'coverEndDate-year': (datePlusMonth.getFullYear()).toString(),
      name: '1234',
      bondBeneficiary: '',
      guaranteeFeePayableByBank: '18.0000',
      updatedAt: Date.now(),
      value: '1234.00',
      currencySameAsSupplyContractCurrency: 'true',
      riskMarginFee: '20',
      coveredPercentage: '30',
      minimumRiskMarginFee: '',
      ukefExposure: '370.20',
      feeType: 'At maturity',
      dayCountBasis: '365',
    },
    {
      type: 'Loan',
      createdDate: date.valueOf(),
      facilityStage: 'Conditional',
      hasBeenIssued: false,
      ukefGuaranteeInMonths: '12',
      guaranteeFeePayableByBank: '10.8000',
      value: '123123.00',
      currencySameAsSupplyContractCurrency: 'true',
      interestMarginFee: '12',
      coveredPercentage: '20',
      minimumQuarterlyFee: '20',
      ukefExposure: '24,624.60',
      premiumFrequency: 'Monthly',
      premiumType: 'In arrear',
      dayCountBasis: '360',
      viewedPreviewPage: true,
      currency: {
        text: 'GBP - UK Sterling',
        id: 'GBP',
      },
      issuedDate: datePlusDay.valueOf(),
      'coverEndDate-day': (datePlusMonth.getDate()).toString(),
      'coverEndDate-month': (datePlusMonth.getMonth() + 1).toString(),
      'coverEndDate-year': (datePlusMonth.getFullYear()).toString(),
      nameRequiredForIssuance: true,
      issueFacilityDetailsStarted: true,
      issueFacilityDetailsProvided: true,
      disbursementAmount: '1,234.00',
      name: '5678',
      status: 'Ready for check',
      updatedAt: Date.now(),
    },
    {
      type: 'Loan',
      createdDate: date.valueOf(),
      facilityStage: 'Unconditional',
      hasBeenIssued: true,
      'requestedCoverStartDate-day': '',
      'requestedCoverStartDate-month': '',
      'requestedCoverStartDate-year': '',
      'coverEndDate-day': (datePlusMonth.getDate()).toString(),
      'coverEndDate-month': (datePlusMonth.getMonth() + 1).toString(),
      'coverEndDate-year': (datePlusMonth.getFullYear()).toString(),
      name: '12345678',
      guaranteeFeePayableByBank: '45.0000',
      updatedAt: Date.now(),
      value: '1234.00',
      currencySameAsSupplyContractCurrency: 'true',
      disbursementAmount: '200.00',
      interestMarginFee: '50',
      coveredPercentage: '60',
      minimumQuarterlyFee: '',
      ukefExposure: '740.40',
      premiumType: 'At maturity',
      dayCountBasis: '365',
    },
  ],
};

export default deal;
