/**
 * autoCompleteField
 * "Autocomplete" cypress selector.
 * This field is used for any autocomplete fields, e.g other credit rating field in the edit pricing and risk page.
 * It provides selectors for the input, results and noResults elements.
 * It also provides a selectOption method to select an option from the results list.
 * @param {string} fieldId: Field ID
 * @returns {object} Autocomplete field selectors with bespoke input, result and noResults selectors.
 */
export const autoCompleteField = (fieldId) => ({
  input: () => cy.get(`#${fieldId}`),
  results: () => cy.get(`#${fieldId} + ul li`),
  noResults: () => cy.get('.autocomplete__option--no-results'),
  /**
   * selects an option from the results list by matching the innerText of the option with the provided option string.
   * There is no data-cy attribute on the option elements, so we have to use the id attribute which is generated by the autocomplete component
   */
  selectOption: (option) =>
    cy
      .get(`[id^="${fieldId}__option--"]`)
      .filter((_, el) => el.innerText.trim() === option)
      .first(),
});
