import pages from '../../pages';

export const checkAutocompleteInput = {
  isVisible: (field) => {
    field.input().should('be.visible');
  },
  isNotVisible: (field) => {
    field.input().should('not.be.visible');
  },
  hasWorkingClientSideJS: (field) => {
    cy.checkClassName(field.input(), 'autocomplete__input autocomplete__input--default');
  },
  rendersInput: (field) => {
    field.input().should('exist');
  },
  rendersNoResultsMessage: (field, textValue) => {
    cy.keyboardInput(field.input(), textValue);

    const noResults = field.noResults();

    // this text is generated by external component.
    cy.assertText(noResults, 'No results found');
  },
  rendersSingleResult: (field, input) => {
    // start searching for a country
    cy.keyboardInput(field.input(), input);

    const noResults = field.noResults();
    noResults.should('not.exist');

    const results = field.results();

    cy.assertLength(results, 1);
  },
  rendersMultipleResults: (field) => {
    cy.keyboardInput(field.input(), 'A');

    const noResults = field.noResults();
    noResults.should('not.exist');

    const results = field.results();

    results.should('have.length.greaterThan', 1);
  },
  allowsUserToRemoveEntryAndSearchAgain: (fieldId, entry1, entry2, expectedValue) => {
    cy.autocompleteKeyboardInput(fieldId, entry1);
    // enter the second entry to check that the first entry is removed and the second entry is selected
    cy.autocompleteKeyboardInput(fieldId, entry2);

    cy.assertText(pages.autoCompleteField(fieldId).results(), expectedValue);
  },
  checkInputResults: (fieldId, expectedValue) => {
    cy.assertText(pages.autoCompleteField(fieldId).results(), expectedValue);
  },
  checkEmptyResults: (fieldId) => {
    pages.autoCompleteField(fieldId).results().should('not.exist');
  },
};

export default checkAutocompleteInput;
