name: PR tests - Empty tests for github action config

on:
  pull_request:
    branches: [ main ]
    paths: 
    - '.github/workflows/PR/**'
    - 'README.md'

jobs:
  test:
    name: Run PR tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2