export const SUBMISSION_DETAILS = {
  status: 'Incomplete',
  'indemnifier-address-country': {
    code: 'GBR',
    name: 'United Kingdom',
  },
  'indemnifier-address-line-1': 'Addr 1',
  'indemnifier-address-line-2': 'Addr 2',
  'indemnifier-address-line-3': 'Addr 3',
  'indemnifier-address-postcode': 'test',
  'indemnifier-address-town': 'test town',
  'indemnifier-companies-house-registration-number': '12345678',
  'indemnifier-correspondence-address-country': {
    code: 'GBR',
    name: 'United Kingdom',
  },
  'indemnifier-correspondence-address-line-1': 'Addr 1',
  'indemnifier-correspondence-address-line-2': 'Addr 2',
  'indemnifier-correspondence-address-line-3': 'Addr 3',
  'indemnifier-correspondence-address-postcode': 'test',
  'indemnifier-correspondence-address-town': 'test town',
  'indemnifier-name': 'Mock name',
  'industry-class': {
    code: '56101',
    name: 'Licensed restaurants',
  },
  'industry-sector': {
    code: '1008',
    name: 'Accommodation and food service activities',
  },
  legallyDistinct: 'false',
  'sme-type': 'Micro',
  'supplier-address-country': {
    code: 'GBR',
    name: 'United Kingdom',
  },
  'supplier-address-line-1': 'test',
  'supplier-address-line-2': 'test',
  'supplier-address-line-3': 'test',
  'supplier-address-postcode': 'test',
  'supplier-address-town': 'test',
  'supplier-companies-house-registration-number': '',
  'supplier-correspondence-address-country': {
    code: 'GBR',
    name: 'United Kingdom',
  },
  'supplier-correspondence-address-is-different': 'false',
  'supplier-correspondence-address-line-1': 'Addr 1',
  'supplier-correspondence-address-line-2': 'Addr 2',
  'supplier-correspondence-address-line-3': 'Addr 3',
  'supplier-correspondence-address-postcode': 'test',
  'supplier-correspondence-address-town': 'test town',
  'supplier-type': 'Exporter',
  'supply-contract-description': 'test',
  'buyer-address-country': {
    code: 'GBR',
    name: 'United Kingdom',
  },
  'buyer-address-line-1': 'test',
  'buyer-address-line-2': 'test',
  'buyer-address-line-3': 'test',
  'buyer-address-postcode': 'test',
  'buyer-address-town': 'test',
  'buyer-name': 'test',
  destinationOfGoodsAndServices: {
    code: 'GBR',
    name: 'United Kingdom',
  },
  'supplyContractConversionDate-day': '',
  'supplyContractConversionDate-month': '',
  'supplyContractConversionDate-year': '',
  supplyContractConversionRateToGBP: '',
  supplyContractCurrency: {
    id: 'GBP',
    text: 'GBP - UK Sterling',
  },
  supplyContractValue: '1234.00',
};
