const MOCK_USERS = [
  {
    _id: '6051d94564494924d38ce67c',
    username: 'BUSINESS_SUPPORT_USER_1',
    email: 'test@testing.com',
    teams: ['BUSINESS_SUPPORT'],
    timezone: 'Europe/London',
    firstName: 'John',
    lastName: 'Davies',
    assignedTasks: [],
  },
  {
    _id: '6051d94564494924d38ce123',
    username: 'myUsername',
    email: 'test@testing.com',
    teams: ['BUSINESS_SUPPORT'],
    timezone: 'Europe/London',
    firstName: 'Sarah',
    lastName: 'Walker',
    assignedTasks: [],
  },
  {
    _id: '6051d94564494924d38ce124',
    username: 'myUsername',
    email: 'test@testing.com',
    teams: ['UNDERWRITING_SUPPORT'],
    timezone: 'Europe/London',
    firstName: 'Ben',
    lastName: 'Wilson',
    assignedTasks: [],
  },
  {
    _id: '6051d94564494924d38ce125',
    username: 'UNDERWRITER_MANAGER_1',
    email: 'test@testing.com',
    teams: ['UNDERWRITER_MANAGERS'],
    timezone: 'Europe/London',
    firstName: 'Benjamin',
    lastName: 'Jones',
    assignedTasks: [],
  },
  {
    _id: '6051d94564494924d38ce126',
    username: 'UNDERWRITER_1',
    email: 'test@testing.com',
    teams: ['UNDERWRITERS'],
    timezone: 'Europe/London',
    firstName: 'Olivia',
    lastName: 'Williams',
    assignedTasks: [],
  },
  {
    _id: '6051d94564494924d38ce127',
    username: 'RISK_MANAGER_1',
    email: 'test@testing.com',
    teams: ['RISK_MANAGERS'],
    timezone: 'Europe/London',
    firstName: 'Steven',
    lastName: 'Robinson',
    assignedTasks: [],
  },
];

module.exports = MOCK_USERS;
