name: Production DNS

on:
  push:
    branches: [ dns ]
    paths: 
    - '.github/workflows/Infrastructure/dns.yml'

env:
  credentials: ${{ secrets.AZURE_DIGITAL_PROD }}
  resource_group: ${{ secrets.PROD_RESOURCE_GROUP }}
  domain_name: "get-a-guarantee-for-export-finance.service.gov.uk"
  front_door_name: tfs-prod-fd
  portal_ui: tfs-prod-portal-ui
  gef_ui: tfs-prod-gef-ui

jobs:

  zone:
    name: Create service.gov.uk zone
    runs-on: [self-hosted, linux]
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ env.credentials }}

    - name: Defaults
      uses: azure/cli@v1.0.0
      with:
        inlineScript: |
          az configure --defaults location=uksouth
          az configure --defaults group=${{ env.resource_group }}
          az extension add --name front-door

    - name: Zone
      uses: azure/cli@v1.0.0
      with:
        inlineScript: |
          az network dns zone create --name ${{ env.domain_name }}

    - name: Front Door verification record
      uses: azure/cli@v1.0.0
      with:
        inlineScript: |
          az network dns record-set cname create --zone ${{ env.domain_name }} --name afdverify.${{ env.domain_name }}
          az network dns record-set cname set-record --zone ${{ env.domain_name }} --record-set-name afdverify.${{ env.domain_name }} --cname ${{ env.front_door_name }}.azurefd.net

    - name: Custom domains for web apps
      uses: azure/cli@v1.0.0
      with:
        inlineScript: |
          az network dns record-set cname set-record --zone ${{ env.domain_name }} --record-set-name www --cname ${{ env.portal_ui }}.azurewebsites.net
          # az network dns record-set cname set-record --zone ${{ env.domain_name }} --record-set-name www --cname ${{ env.gef_ui }}.azurewebsites.net

    - name: Custom domains ownership records
      uses: azure/cli@v1.0.0
      with:
        inlineScript: |
          az network dns record-set txt add-record --record-set-name asuid.www --value ${{ secrets.PROD_DNS_VERIFICATION }} --zone-name ${{ env.domain_name }}

    - name: Alias record for service.gov.uk domain
      uses: azure/cli@v1.0.0
      with:
        inlineScript: |
          front_door_id=$(az network front-door show --name ${{ env.front_door_name }} --query id -o tsv)
          az network dns record-set a create --name "@" --zone-name ${{ env.domain_name }} --target-resource $front_door_id

    - name: Add domain name to Prod Front Door
      uses: azure/cli@v1.0.0
      with:
        inlineScript: |
          az network front-door frontend-endpoint create \
            --front-door-name ${{ env.front_door_name }} \
            --name "GOVUK" \
            --host-name ${{ env.domain_name }}

    - name: Enable HTTPS
      uses: azure/cli@v1.0.0
      with:
        inlineScript: |
          az network front-door frontend-endpoint enable-https \
            --front-door-name ${{ env.front_door_name }} \
            --name "service.gov.uk"
          

    - name: Check domain name mapping
      uses: azure/cli@v1.0.0
      with:
        inlineScript: |
          az network front-door check-custom-domain --host-name ${{ env.domain_name }} --name ${{ env.front_door_name }}
