
const AZURE_WORKFLOW_FILESHARE_CONFIG = {
  FILESHARE_NAME: process.env.AZURE_WORKFLOW_FILESHARE_NAME,
  EXPORT_FOLDER: process.env.AZURE_WORKFLOW_EXPORT_FOLDER,
  IMPORT_FOLDER: process.env.AZURE_WORKFLOW_IMPORT_FOLDER,
  STORAGE_ACCOUNT: process.env.AZURE_WORKFLOW_STORAGE_ACCOUNT,
  STORAGE_ACCESS_KEY: process.env.AZURE_WORKFLOW_STORAGE_ACCESS_KEY,
};

module.exports = {
  AZURE_WORKFLOW_FILESHARE_CONFIG,
};
