version: "3" 
services:

  acbs-function:
    build: .
    image: dtfs/azure-function-acbs
    restart: always
    ports:
      - "7071:80"
    environment:
      - AzureWebJobsStorage=DefaultEndpointsProtocol=https;AccountName=${AZURE_PORTAL_STORAGE_ACCOUNT};AccountKey=${AZURE_PORTAL_STORAGE_ACCESS_KEY};EndpointSuffix=core.windows.net
      - WEBSITE_HOSTNAME=localhost:7071
      - MULESOFT_API_KEY
      - MULESOFT_API_SECRET
      - MULESOFT_API_UKEF_TF_EA_URL
      - MULESOFT_API_UKEF_MDM_EA_URL
      - MULESOFT_API_UKEF_MDM_EA_KEY
      - MULESOFT_API_UKEF_MDM_EA_SECRET