version: '3'
services:
  acbs-function:
    build: .
    image: dtfs/azure-function-acbs
    restart: always
    ports:
      - '7071:80'
    environment:
      - TZ=Europe/London
      - AzureWebJobsStorage=DefaultEndpointsProtocol=https;AccountName=${AZURE_PORTAL_STORAGE_ACCOUNT};AccountKey=${AZURE_PORTAL_STORAGE_ACCESS_KEY};EndpointSuffix=core.windows.net
      - FUNCTIONS_WORKER_RUNTIME=node
      - WEBSITE_HOSTNAME=localhost:7071
      - APIM_MDM_URL
      - APIM_MDM_KEY
      - APIM_MDM_VALUE
      - APIM_TFS_URL
      - APIM_TFS_KEY
      - APIM_TFS_VALUE
