# This GitHub Action is designed to execute Azure CLI for infrastructure maintenance

name: 'Deploy Azure WebApp'
description: 'This custom GitHub Actions module will execute AZ CLI for infrastructure maintenance'

# Define the inputs required for this action.
inputs:
  credentials:
    description: 'Azure subscription and resource group service principal'
    required: true
  subscription:
    description: 'Azure subscription ID'
    required: true
  group:
    description: 'Azure resource group'
    required: true
  acr:
    description: 'Azure subscription and resource group service principal'
    required: true
  days:
    description: 'Retention days for ACR artifacts purge i.e images older than x days will be removed.'
    required: true
    default: '30'

# Define the steps to run this action.
runs:
  using: 'composite'
  steps:
    # Step 1: Check out the repository.
    - name: Repository 🗃️
      uses: actions/checkout@v4
      with:
        ref: feat/DTFS2-7846-acr-purge


    # Step 2: Log in to Azure.
    - name: Azure 🔐
      uses: azure/login@v2
      with:
        creds: ${{ inputs.credentials }}

    # Step 3: Purge artifacts
    - name: Artifacts 🗃️
      working-directory: .
      run: |
        az acr run --registry ${{ inputs.acr }} --resource-group ${{ inputs.group }} --subscription ${{ inputs.subscription }} --cmd "acr purge --filter 'portal-ui:.*' --filter 'gef-ui:.*' --filter 'trade-finance-manager-ui:.*' --filter 'portal-api:.*' --filter 'trade-finance-manager-api:.*' --filter 'dtfs-central-api:.*' --filter 'external-api:.*' --filter 'azure-function-acbs:.*' --ago ${{ inputs.days }}d" /dev/null
      shell: bash
