export const ALL_ENTRA_ID_USER_GROUPS = [
  'AZURE_SSO_GROUP_UNDERWRITING_SUPPORT',
  'AZURE_SSO_GROUP_UNDERWRITER_MANAGERS',
  'AZURE_SSO_GROUP_UNDERWRITERS',
  'AZURE_SSO_GROUP_RISK_MANAGERS',
  'AZURE_SSO_GROUP_BUSINESS_SUPPORT',
  'AZURE_SSO_GROUP_PIM',
  'AZURE_SSO_GROUP_PDC_READ',
  'AZURE_SSO_GROUP_PDC_RECONCILE',
] as const;

export type EntraIdUserGroups = (typeof ALL_ENTRA_ID_USER_GROUPS)[number];

export const ENTRA_ID_USER_GROUP = {
  AZURE_SSO_GROUP_UNDERWRITING_SUPPORT: 'AZURE_SSO_GROUP_UNDERWRITING_SUPPORT',
  AZURE_SSO_GROUP_UNDERWRITER_MANAGERS: 'AZURE_SSO_GROUP_UNDERWRITER_MANAGERS',
  AZURE_SSO_GROUP_UNDERWRITERS: 'AZURE_SSO_GROUP_UNDERWRITERS',
  AZURE_SSO_GROUP_RISK_MANAGERS: 'AZURE_SSO_GROUP_RISK_MANAGERS',
  AZURE_SSO_GROUP_BUSINESS_SUPPORT: 'AZURE_SSO_GROUP_BUSINESS_SUPPORT',
  AZURE_SSO_GROUP_PIM: 'AZURE_SSO_GROUP_PIM',
  AZURE_SSO_GROUP_PDC_READ: 'AZURE_SSO_GROUP_PDC_READ',
  AZURE_SSO_GROUP_PDC_RECONCILE: 'AZURE_SSO_GROUP_PDC_RECONCILE',
} as const satisfies Record<EntraIdUserGroups, EntraIdUserGroups>;
