# This GitHub Action is designed to deploy the latest schema migration to a MSSQL database on an AMI.

name: 'MSSQL migration'
description: 'Deploy latest schema migration to MSSQL on an AMI'

# Define the inputs required for this action.
inputs:
  branch:
    description: 'Source Git branch, main if none specified'
    required: false
    default: 'main'
  host:
    description: 'MSSQL host address'
    required: true
  port:
    description: 'MSSQL host port address'
    required: true
  username:
    description: 'MSSQL connection username'
    required: true
  password:
    description: 'MSSQL connection password'
    required: true
  database:
    description: 'MSSQL database name'
    required: true
  log:
    description: 'Enable MSSQL database logging'
    required: false
    default: false
  node:
    description: 'Node.js setup version'
    required: true

# Define the steps to run this action.
runs:
  using: 'composite'
  steps:
    # Step 1: Check out the repository.
    - name: Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    # Step 2: Set up Node.js.
    - name: Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node }}

    # Step 3: Install dependencies.
    - name: Dependencies
      working-directory: ./libs/common
      run: npm ci
      shell: bash

    # Step 4: Run database migrations.
    - name: Migrate
      working-directory: ./libs/common
      env:
        SQL_DB_HOST: ${{ inputs.host }}
        SQL_DB_PORT: ${{ inputs.port }}
        SQL_DB_USERNAME: ${{ inputs.username }}
        SQL_DB_PASSWORD: ${{ inputs.password }}
        SQL_DB_NAME: ${{ inputs.database }}
        SQL_DB_LOGGING_ENABLED: ${{ inputs.log }}
      run: npm run db:migrate
      shell: bash
