# Composite function to retry a command for a maximum of 3 times
# Used in the test.yml workflow to retry the steps that may fail due to network issues
# If a step fails, it will add one to run counter until the limit reached
# If the step passes, it will break from the until loop and pass the step
# Consumes command, working-directory and env variables
# command and env can be multiline
# In do loop, if the run is 1, then should cd to working directory
# If not 1, then already in working directory so does not need to cd
name: "Retry Steps"
inputs:
  command:
    required: true
  working-directory:
    required: false
    default: "./"
  env:
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - run: |
        limit=3
        run=1
        env=${{ inputs.env }}
        until [ $run -gt $limit ]
        do
          if [ $run -eq 1 ]; then
            cd ${{ inputs.working-directory }} && eval "$env" && bash -c "${{ inputs.command }}" && break
          else
            eval "$env" && bash -c "${{ inputs.command }}" && break
          fi
          run=$((run + 1))
        done
        if [ $run -gt $limit ]; then
          exit 1
        fi
      shell: bash