name: "Retry Steps"
inputs:
  command:
    required: true
  working-directory:
    required: false
    default: "./"
  env-vars:
    required: false
    default: "{}"
runs:
  using: "composite"
  steps:
    - run: |
        limit=3
        run=1
        env_vars=${{ inputs.env-vars }}
        env_vars=$(echo $env_vars | jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | .[]')
        until [ $run -gt $limit ]
        do
          cd ${{ inputs.working-directory }} && ${{ inputs.command }} && break
          run=$((run + 1))
        done
        if [ $run -gt $limit ]; then
          exit 1
        fi
      shell: bash
      env:
        env-vars: ${{ inputs.env-vars }}