version: "3" 
services:
  portal-api:
    build: ../portal-api
    image: dtfs/portal-api
    restart: always
    depends_on:
      - portal-api-data
      - reference-data-proxy
    ports:
      - "5001:5001"
    volumes:
      - ../portal-api/src:/app/src:ro
    environment:
      - DEBUG=express:*
      - PORT=5001
      - CORS_ORIGIN=http://localhost:5000
      - JWT_SIGNING_KEY
      - JWT_VALIDATING_KEY
      - MONGO_INITDB_DATABASE=test
      - MONGODB_URI=mongodb://root:r00t@portal-api-data:27017/?authMechanism=DEFAULT
      - AZURE_WORKFLOW_FILESHARE_NAME
      - AZURE_WORKFLOW_STORAGE_ACCOUNT
      - AZURE_WORKFLOW_STORAGE_ACCESS_KEY
      - AZURE_WORKFLOW_EXPORT_FOLDER
      - AZURE_WORKFLOW_IMPORT_FOLDER
      - AZURE_PORTAL_FILESHARE_NAME
      - AZURE_PORTAL_STORAGE_ACCOUNT
      - AZURE_PORTAL_STORAGE_ACCESS_KEY
      - AZURE_PORTAL_EXPORT_FOLDER
      - GOV_NOTIFY_API_KEY
      - GOV_NOTIFY_EMAIL_RECIPIENT
      - DTFS_PORTAL_SCHEDULER
      - REFERENCE_DATA_PROXY_URL=http://reference-data-proxy:5002
    entrypoint: npx nodemon src/index.js

  portal-api-data:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=r00t
    volumes:
      - ../portal-api-data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./portal-api-data-volume:/data/db
    ports:
      - "27017-27019:27017-27019"
    
  reference-data-proxy:
    build: ../reference-data-proxy
    image: dtfs/reference-data-proxy
    restart: always
    ports:
      - "5002:5002"
    volumes:
      - ../reference-data-proxy/src:/app/src:ro
    environment:
      - PORT=5002
      - MULESOFT_API
    entrypoint: npx nodemon src/index.js

  test-hook-api:
    build: ../test-hook-api
    image: dtfs/test-hook-api
    restart: always
    depends_on:
      - portal-api
    ports:
      - "5069:5069"
    volumes:
      - ../test-hook-api/src:/app/src:ro
    environment:
      - PORT=5069
      - CORS_ORIGIN=http://localhost:5000
      - AZURE_WORKFLOW_STORAGE_ACCOUNT
      - AZURE_WORKFLOW_STORAGE_ACCESS_KEY
      - AZURE_WORKFLOW_FILESHARE_NAME
      - AZURE_WORKFLOW_EXPORT_FOLDER
      - AZURE_WORKFLOW_IMPORT_FOLDER
      - AZURE_PORTAL_STORAGE_ACCOUNT
      - AZURE_PORTAL_STORAGE_ACCESS_KEY
      - AZURE_PORTAL_FILESHARE_NAME
      - AZURE_PORTAL_EXPORT_FOLDER
      - DTFS_PORTAL_SCHEDULER
      - GOV_NOTIFY_API_KEY
      - GOV_NOTIFY_EMAIL_RECIPIENT

    entrypoint: npx nodemon src/index.js
