module.exports = {
  landingPage: require('./landingPage'),
  startNow: require('./startNow'),
  beforeYouStart: require('./beforeYouStart'),
  unableToProceed: require('./unableToProceed'),
  bankDetails: require('./bankDetails'),
  contract: require('./contract'),
  contractAboutSupplier: require('./contract/contract-about-supplier'),
  contractAboutBuyer: require('./contract/contract-about-buyer'),
  contractDelete: require('./contract/contract-delete'),
  contractReadyForReview: require('./contract/contract-readyForReview'),
  contractReturnToMaker: require('./contract/contract-returnToMaker'),
  contractConfirmSubmission: require('./contract/contract-confirmSubmission'),
  editDealName: require('./contract/contract-edit-name'),
  dashboard: require('./dashboard'),
  cloneDeal: require('./cloneDeal'),
  eligibilityCriteria: require('./eligibilityCriteria'),
  eligibilityDocumentation: require('./eligibilityDocumentation'),
  header: require('./header'),
  bondDetails: require('./bondDetails'),
  bondFinancialDetails: require('./bondFinancialDetails'),
  bondFeeDetails: require('./bondFeeDetails'),
  bondPreview: require('./bondPreview'),
};
