module.exports = {
  landingPage: require('./landingPage'),
  startNow: require('./startNow'),
  beforeYouStart: require('./beforeYouStart'),
  unableToProceed: require('./unableToProceed'),
  bankDetails: require('./bankDetails'),
  contract: require('./contract'),
  contractDelete: require('./contract/contract-delete'),
  contractReadyForReview: require('./contract/contract-readyForReview'),
  editDealName: require('./editDealName'),
  dashboard: require('./dashboard'),
  cloneDeal: require('./cloneDeal'),
  eligibilityCriteria: require('./eligibilityCriteria'),
  header: require('./header'),
};
