# Infrastructure Deployment Workflow
#
# This GitHub Actions workflow automates the deployment of Azure infrastructure
# for the DTFS project. It performs the following main tasks:
#
# 1. Sets up the environment and variables
# 2. Logs in to Azure
# 3. Creates or updates the resource group
# 4. Replaces placeholders in the parameters.json file with actual values from GitHub secrets
# 5. Deploys Azure resources using the Bicep template
#
# The workflow is triggered on pushes to the target branch and uses environment
# variables and secrets for configuration. It's designed to work with the
# main.bicep and parameters.json files in the infrastructure directory.
#
# Note: Ensure all required secrets and variables are set in the GitHub repository
# settings before running this workflow.

name: Infrastructure 🔨
run-name: DTFS base infrastructure build from ${{ github.repository }}

on:
  push:
    branches:
      - dev
      - main
      - staging
      - production
    paths:
      - '.github/workflows/bicep_infrastructure.yml'
      - 'infrastructure/**'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Target deployment environment'
        required: true
        type: environment

env:
  PRODUCT: dtfs2
  ENVIRONMENT: dev
  TIMEZONE: '${{ vars.TIMEZONE }}'
  # Deployment environment target i.e., `development`, `staging`, `production`
  TARGET: ${{ vars.TARGET }}

jobs:
# 1. Setup infrastructure variables
  setup:
    name: Setup 🔧
    runs-on: [self-hosted, linux, deployment]
    outputs:
      environment: ${{ env.ENVIRONMENT }}
      timezone: ${{ env.TIMEZONE }}
    steps:
      - name: Repository 🗃️
        uses: actions/checkout@v6

      - name: Environment 🧪
        run: echo "Environment set to ${{ env.ENVIRONMENT }}"

      - name: Timezone 🌐
        run: echo "Timezone set to ${{ env.TIMEZONE }}"

      - name: Login 🔐
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_DEV_CREDENTIALS }}

      - name: Azure defaults ✨
        uses: azure/cli@v3
        with:
          inlineScript: |
            # Basic
            az configure --defaults location=${{ vars.REGION }}
            az configure --defaults group=rg-${{ env.PRODUCT }}-${{ env.TARGET }}-${{ vars.VERSION }}

      - name: Create Resource group 🏗️
        uses: azure/cli@v3
        with:
          inlineScript: |
            az group create \
            --location ${{ vars.REGION }} \
            --name rg-${{ env.PRODUCT }}-${{ env.TARGET }}-${{ vars.VERSION }}

      - name: Set Resource Group Name
        run: echo "RESOURCE_GROUP_NAME=rg-${{ env.PRODUCT }}-${{ env.TARGET }}-${{ vars.VERSION }}" >> $GITHUB_ENV

# 2. Validate infrastructure resources
  Resource-Deploy:
    name: Deploy Resources 📊
    needs: setup
    runs-on: [self-hosted, linux, deployment]
    steps:
      - name: Repository 🗃️
        uses: actions/checkout@v6

      - name: Login 🔐
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_DEV_CREDENTIALS }}

      - name: Set bicep properties ✨
        run: |
          BICEP_PARAMETERS="environment=${{ vars.ENVIRONMENT }} \
          product=${{ vars.PRODUCT }} \
          target=${{ vars.TARGET }} \
          version=${{ vars.VERSION || 'v1' }} \
          peeringRemoteVnetSubscriptionId=${{ secrets.PEERING_REMOTE_VNET_SUBSCRIPTION_ID }} \
          azDevVnetAddressPrefix=${{ secrets.AZ_DEV_VNET_ADDRESS_PREFIX }} \
          azDevSnetAppgwCidrPrefix=${{ secrets.AZ_DEV_SNET_APPGW_CIDR_PREFIX }} \
          azDevSnetAspEgressPrefixCidr=${{ secrets.AZ_DEV_SNET_ASP_EGRESS_PREFIX_CIDR }} \
          azDevSnetAcaClamavCidr=${{ secrets.AZ_DEV_SNET_ACA_CLAMAV_CIDR }} \
          azDevSnetPrivateEpCidr=${{ secrets.AZ_DEV_SNET_PRIVATE_EP_CIDR }} \
          prodSubnetCidr=${{ secrets.PROD_SUBNET_CIDR }} \
          routeTblNextHopAddress=${{ secrets.ROUTE_TBL_NEXT_HOP_ADDRESS }} \
          ukefVpnIps=${{ secrets.UKEF_VPN_IPS }} \
          azPortalIps=${{ secrets.AZ_PORTAL_IPS }} \
          apimTfsKey=${{ secrets.APIM_TFS_KEY }} \
          apimTfsValue=${{ secrets.APIM_TFS_VALUE }} \
          apimTfsUrl=${{ secrets.APIM_TFS_URL }} \
          apimMdmKey=${{ secrets.APIM_MDM_KEY }} \
          apimMdmUrl=${{ secrets.APIM_MDM_URL }} \
          apimMdmValue=${{ secrets.APIM_MDM_VALUE }} \
          apimMdmKeyVaultName=${{ secrets.APIM_MDM_KEY_VAULT_NAME }} \
          companiesHouseApiUrl=${{ secrets.COMPANIES_HOUSE_API_URL }} \
          ordnanceSurveyApiUrl=${{ secrets.ORDNANCE_SURVEY_API_URL }} \
          rateLimitThreshold=${{ secrets.RATE_LIMIT_THRESHOLD }} \
          apimEstoreUrl=${{ secrets.APIM_ESTORE_URL }} \
          corsOrigin=${{ secrets.CORS_ORIGIN }} \
          apimEstoreKey=${{ secrets.APIM_ESTORE_KEY }} \
          apimEstoreValue=${{ secrets.APIM_ESTORE_VALUE }} \
          companiesHouseApiKey=${{ secrets.COMPANIES_HOUSE_API_KEY }} \
          govNotifyEmailRecipient=${{ secrets.GOV_NOTIFY_EMAIL_RECIPIENT }} \
          govNotifyApiKey=${{ secrets.GOV_NOTIFY_API_KEY }} \
          externalApiKey=${{ secrets.EXTERNAL_API_KEY }} \
          ordnanceSurveyApiKey=${{ secrets.ORDNANCE_SURVEY_API_KEY }} \
          utilisationReportCreationForBanksSchedule=${{ secrets.UTILISATION_REPORT_CREATION_FOR_BANKS_SCHEDULE }} \
          dtfsCentralApiKey=${{ secrets.DTFS_CENTRAL_API_KEY }} \
          portalUiUrl=${{ vars.PORTAL_UI_URL }} \
          utilisationReportDueDateBusinessDaysFromStartOfMonth=${{ vars.UTILISATION_REPORT_DUE_DATE_BUSINESS_DAYS_FROM_START_OF_MONTH }} \
          utilisationReportOverdueChaserDateBusinessDaysFromStartOfMonth=${{ vars.UTILISATION_REPORT_OVERDUE_CHASER_DATE_BUSINESS_DAYS_FROM_START_OF_MONTH }} \
          utilisationReportReportingPeriodStartEmailSchedule=${{ vars.UTILISATION_REPORT_REPORTING_PERIOD_START_EMAIL_SCHEDULE }} \
          utilisationReportOverdueEmailSchedule=${{ vars.UTILISATION_REPORT_OVERDUE_EMAIL_SCHEDULE }} \
          azureUtilisationReportsFileshareName=${{ vars.AZURE_UTILISATION_REPORTS_FILESHARE_NAME }} \
          pdcInputtersEmailRecipient=${{ secrets.PDC_INPUTTERS_EMAIL_RECIPIENT }} \
          azurePortalExportFolder=${{ secrets.AZURE_PORTAL_EXPORT_FOLDER }} \
          azurePortalFileshareName=${{ secrets.AZURE_PORTAL_FILESHARE_NAME }} \
          jwtValidatingKey=${{ secrets.JWT_VALIDATING_KEY }} \
          portalApiKey=${{ secrets.PORTAL_API_KEY }} \
          utilisationReportDueEmailSchedule=${{ vars.UTILISATION_REPORT_DUE_EMAIL_SCHEDULE }} \
          tfmApiKey=${{ secrets.TFM_API_KEY }} \
          utilisationReportMaxFileSizeBytes=${{ vars.UTILISATION_REPORT_MAX_FILE_SIZE_BYTES }} \
          sessionSecret=${{ secrets.SESSION_SECRET }} \
          ukefTfmApiSystemKey=${{ secrets.UKEF_TFM_API_SYSTEM_KEY }} \
          estoreUrl=${{ secrets.ESTORE_URL }} \
          ukefTfmApiReportsKey=${{ secrets.UKEF_TFM_API_REPORTS_KEY }} \
          azureNumberGeneratorFunctionSchedule=${{ secrets.AZURE_NUMBER_GENERATOR_FUNCTION_SCHEDULE }} \
          ukefInternalNotification=${{ secrets.UKEF_INTERNAL_NOTIFICATION }} \
          azureDnsServerIp=${{ secrets.AZURE_DNS_SERVER_IP }} \
          nsgSourceAddressPrefix=${{ vars.NSG_SOURCE_ADDRESS_PREFIX }} \
          ukefSourceAddressPrefix=${{ vars.UKEF_SOURCE_ADDRESS_PREFIX }} \
          testSourceAddressPrefix=${{ vars.TEST_SOURCE_ADDRESS_PREFIX }} \
          websiteHttploggingRetentionDays=${{ vars.WEBSITE_HTTPLOGGING_RETENTION_DAYS }} \
          websiteDynamicCache=${{ vars.WEBSITE_DYNAMIC_CACHE }} \
          websiteNodeDefaultVersion=${{ vars.WEBSITE_NODE_DEFAULT_VERSION }} \
          websiteHealthcheckingMax=${{ vars.WEBSITE_HEALTHCHECKING_MAX }} \
          timezone=${{ vars.TIMEZONE }} \
          peeringVnetName=${{ secrets.AZ_DEV_VNET_ADDRESS_PREFIX }} \
          redirectUrl=${{ vars.REDIRECT_URL }} \
          aspSku=${{ vars.ASP_SKU }} \
          jwtSigningKey=${{ secrets.JWT_SIGNING_KEY }} \
          azurePortalStorageAccessKey=${{ secrets.AZURE_PORTAL_ACCESS_KEY }} \
          azurePortalStorageAccount=${{ secrets.AZURE_PORTAL_STORAGE_ACCOUNT }} \
          changeStreamEnabled=${{ vars.CHANGE_STREAM_ENABLED }} \
          deletionAuditLogsTtlSeconds=${{ vars.DELETION_AUDIT_LOGS_TTLSCONDS }} \
          dockerEnableCi=${{ vars.DOCKER_ENABLE_CI }} \
          dtfsCentralApiKeyUrl=${{ vars.DTFS_CENTRAL_API_KEY_URL }} \
          externalApiUrl=${{ vars.EXTERNAL_API_URL }} \
          ffPortal2faEnabled=${{ vars.FF_PORTAL_2FA_ENABLED }} \
          ffPortalFacilityAmendmentsEnabled=${{ vars.FF_PORTAL_FACILITY_AMENDMENTS_ENABLED }} \
          gefDealVersion=${{ vars.GEF_DEAL_VERSION }} \
          log4jFormatMsgNoLookups=${{ vars.LOG4J_FORMAT_MSG_NO_LOOKUPS }} \
          maintenanceActive=${{ vars.MAINTENANCE_ACTIVE }} \
          maintenanceTimestamp=${{ vars.MAINTENANCE_TIMESTAMP }} \
          mongoInitdbDatabase=${{ secrets.MONGO_INITDB_DATABASE }} \
          nodeEnv=${{ secrets.NODE_ENV }} \
          tfmApiUrl=${{ vars.TFM_API_URL }} \
          tfmUiUrl=${{ vars.TFM_UI_URL }} \
          tz=${{ vars.TZ }} \
          ukefGefReportingEmailRecipient=${{ secrets.UKEF_GEF_REPORTING_EMAIL_RECIPIENT }} \
          utilisationReportSubmissionPeriodStartEmailSchedule=${{ vars.UTILISATION_REPORT_SUBMISSION_PERIOD_START_EMAIL_SCHEDULE }} \
          websiteDynamicCache=${{ vars.WEBSITE_DYNAMIC_CACHE }} \
          websiteHealthcheckMaxpingfailures=${{ vars.WEBSITE_HEALTHCHECKING_MAX }} \
          websiteHttploggingRetentionDays=${{ vars.WEBSITE_HTTPLOGGING_RETENTION_DAYS }} \
          websiteLocalCacheOptions=${{ vars.WEBSITE_LOCAL_CACHE_OPTIONS }} \
          websiteNodeDefaultVersion=${{ vars.WEBSITE_NODE_DEFAULT_VERSION }} \
          websiteVnetRouteAll=${{ vars.WEBSITE_VNET_ROUTE_ALL }} \
          websitesEnableAppServiceStorage=${{ vars.WEBSITES_ENABLE_APP_SERVICE_STORAGE }} \
          websitesPort=${{ vars.WEBSITES_PORT }} \
          acbsDurableFunctionsLogDeletionSchedule=${{ secrets.ACBS_DURABLE_FUNCTIONS_LOG_DELETION_SCHEDULE }} \
          auditApiPassword=${{ secrets.AUDIT_API_PASSWORD }} \
          auditApiUrl=${{ secrets.AUDIT_API_URL }} \
          auditApiUsername=${{ secrets.AUDIT_API_USERNAME }} \
          dealCancellationSchedule=${{ vars.DEAL_CANCELLATION_SCHEDULE }} \
          ffTfmDealCancellationEnabled=${{ vars.FF_TFM_DEAL_CANCELLATION_ENABLED }} \
          recordCorrectionTransientFormDataDeleteSchedule=${{ vars.RECORD_CORRECTION_TRANSIENT_FORM_DATA_DELETE_SCHEDULE }} \
          sqlDbHost=${{ secrets.SQL_DB_HOST }} \
          sqlDbLoggingEnabled=${{ vars.SQL_DB_LOGGING_ENABLED }} \
          sqlDbName=${{ secrets.SQL_DB_NAME }} \
          sqlDbPassword=${{ secrets.SQL_DB_PASSWORD }} \
          sqlDbPort=${{ secrets.SQL_DB_PORT }} \
          sqlDbUsername=${{ secrets.SQL_DB_USERNAME }} \"

          echo "BICEP_PARAMETERS=$BICEP_PARAMETERS" >> $GITHUB_ENV

      - name: Install Bicep
        run: |
          az config set bicep.use_binary_from_path=False
          az bicep install
          az bicep upgrade
          az bicep version

      - name: Deploy Azure Resources
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_DEV_SUBSCRIPTION_ID }}
          resourceGroupName: rg-${{ env.PRODUCT }}-${{ env.TARGET }}-${{ vars.VERSION }}
          template: ./infrastructure/resource_group_level/main.bicep
          parameters: ${{ env.BICEP_PARAMETERS }}
          scope: resourcegroup

