name: Demo environment deployment

on:
  push:
    branches: [ demo ]

jobs:

  portal-ui:
    name: Tag Portal UI
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_DEV_REGISTRY }}
        username: ${{ secrets.ACR_DEV_USERNAME }}
        password: ${{ secrets.ACR_DEV_PASSWORD }}
    - run: |
        docker pull ${{ secrets.ACR_DEV_REGISTRY }}/portal-ui:latest
        docker tag ${{ secrets.ACR_DEV_REGISTRY }}/portal-ui:latest ${{ secrets.ACR_DEV_REGISTRY }}/portal-ui:demo
        docker push ${{ secrets.ACR_DEV_REGISTRY }}/portal-ui:demo

  portal-api:
    name: Tag Portal API
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_DEV_REGISTRY }}
        username: ${{ secrets.ACR_DEV_USERNAME }}
        password: ${{ secrets.ACR_DEV_PASSWORD }}
    - run: |
        docker pull ${{ secrets.ACR_DEV_REGISTRY }}/portal-api:latest
        docker tag ${{ secrets.ACR_DEV_REGISTRY }}/portal-api:latest ${{ secrets.ACR_DEV_REGISTRY }}/portal-api:demo
        docker push ${{ secrets.ACR_DEV_REGISTRY }}/portal-api:demo
