name: Deploy Demo environment

on:
  push:
    branches: [ demo ]

jobs:

  demo-portal-data:
    name: Refresh Demo database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Re-insert mocks
        run: |
          cd utils/mock-data-loader 
          echo "DEAL_API_URL=https://dtfs-demo-deal-api.azurewebsites.net" > .env
          npm install
          node re-insert-mocks.js

  demo-portal-ui:
    name: Promote Portal UI from Dev to Demo
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_DEV_REGISTRY }}
        username: ${{ secrets.ACR_DEV_USERNAME }}
        password: ${{ secrets.ACR_DEV_PASSWORD }}
    - run: |
        docker pull ${{ secrets.ACR_DEV_REGISTRY }}/portal-ui:latest
        docker tag ${{ secrets.ACR_DEV_REGISTRY }}/portal-ui:latest ${{ secrets.ACR_DEV_REGISTRY }}/portal-ui:demo
        docker push ${{ secrets.ACR_DEV_REGISTRY }}/portal-ui:demo

  demo-portal-api:
    name: Promote Portal API from Dev to Demo
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_DEV_REGISTRY }}
        username: ${{ secrets.ACR_DEV_USERNAME }}
        password: ${{ secrets.ACR_DEV_PASSWORD }}
    - run: |
        docker pull ${{ secrets.ACR_DEV_REGISTRY }}/portal-api:latest
        docker tag ${{ secrets.ACR_DEV_REGISTRY }}/portal-api:latest ${{ secrets.ACR_DEV_REGISTRY }}/portal-api:demo
        docker push ${{ secrets.ACR_DEV_REGISTRY }}/portal-api:demo
