name: dev

on:
  push:
    branches: [ github-actions ]
  # schedule: add e.g. a montly patch update for the container
    
env:
  ENVIRONMENT: dev
  TAG: latest

jobs:

  portal:
    name: Build and push Portal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        registry: ${{ secrets.ACR_DEV_REGISTRY }}
        username: ${{ secrets.ACR_DEV_USERNAME }}
        password: ${{ secrets.ACR_DEV_PASSWORD }}
        repository: portal
        path: portal
        tags: ${{ env.TAG }}
        add_git_labels: true
        
  deal-api:
    name: Build and push Deal API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        registry: ${{ secrets.ACR_DEV_REGISTRY }}
        username: ${{ secrets.ACR_DEV_USERNAME }}
        password: ${{ secrets.ACR_DEV_PASSWORD }}
        repository: deal-api
        path: deal-api
        tags: ${{ env.TAG }}
        add_git_labels: true
  
  test:
    needs: [portal, deal-api]
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
    - run: echo "Testing... for now let's imagine this passes cleanly."

  promote:
    needs: test
    name: Promote from Dev to Test environment
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_DEV_REGISTRY }}
        username: ${{ secrets.ACR_DEV_USERNAME }}
        password: ${{ secrets.ACR_DEV_PASSWORD }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_TEST_REGISTRY }}
        username: ${{ secrets.ACR_TEST_USERNAME }}
        password: ${{ secrets.ACR_TEST_PASSWORD }}
    - run: |
        echo "Promoting portal..."
        docker pull ${{ secrets.ACR_DEV_REGISTRY }}/portal:${{ env.TAG }}
        docker tag ${{ secrets.ACR_DEV_REGISTRY }}/portal:${{ env.TAG }} ${{ secrets.ACR_TEST_REGISTRY }}/portal:${{ env.TAG }}
        docker push ${{ secrets.ACR_TEST_REGISTRY }}/portal:${{ env.TAG }}
        echo "Promoting deal-api..."
        docker pull ${{ secrets.ACR_DEV_REGISTRY }}/deal-api:${{ env.TAG }}
        docker tag ${{ secrets.ACR_DEV_REGISTRY }}/deal-api:${{ env.TAG }} ${{ secrets.ACR_TEST_REGISTRY }}/deal-api:${{ env.TAG }}
        docker push ${{ secrets.ACR_TEST_REGISTRY }}/deal-api:${{ env.TAG }}
        echo "Done."
