name: Build

on:
  push:
    branches: [ master ]
  schedule:
    # A weekly run to roll up any base image patches,
    # in office hours, avoiding bank holiday Mondays:
    # "At 12:00 on Tuesday." - https://crontab.guru/
    - cron: '0 12 * * 2'
    
env:
  TAG: latest

jobs:

  portal:
    name: Build and push Portal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        registry: ${{ secrets.ACR_DEV_REGISTRY }}
        username: ${{ secrets.ACR_DEV_USERNAME }}
        password: ${{ secrets.ACR_DEV_PASSWORD }}
        repository: portal
        path: portal
        tags: ${{ env.TAG }}
        add_git_labels: true
        
  deal-api:
    name: Build and push Deal API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        registry: ${{ secrets.ACR_DEV_REGISTRY }}
        username: ${{ secrets.ACR_DEV_USERNAME }}
        password: ${{ secrets.ACR_DEV_PASSWORD }}
        repository: deal-api
        path: deal-api
        tags: ${{ env.TAG }}
        add_git_labels: true
  
  test:
    needs: [portal, deal-api]
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
    - run: echo "Testing... for now let's imagine this passes cleanly."

  promote-portal:
    needs: test
    name: Promote Portal from Dev to Test
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_DEV_REGISTRY }}
        username: ${{ secrets.ACR_DEV_USERNAME }}
        password: ${{ secrets.ACR_DEV_PASSWORD }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_TEST_REGISTRY }}
        username: ${{ secrets.ACR_TEST_USERNAME }}
        password: ${{ secrets.ACR_TEST_PASSWORD }}
    - run: |
        docker pull ${{ secrets.ACR_DEV_REGISTRY }}/portal:${{ env.TAG }}
        docker tag ${{ secrets.ACR_DEV_REGISTRY }}/portal:${{ env.TAG }} ${{ secrets.ACR_TEST_REGISTRY }}/portal:${{ env.TAG }}
        docker push ${{ secrets.ACR_TEST_REGISTRY }}/portal:${{ env.TAG }}

  promote-deal-api:
    needs: test
    name: Promote Deal API from Dev to Test
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_DEV_REGISTRY }}
        username: ${{ secrets.ACR_DEV_USERNAME }}
        password: ${{ secrets.ACR_DEV_PASSWORD }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_TEST_REGISTRY }}
        username: ${{ secrets.ACR_TEST_USERNAME }}
        password: ${{ secrets.ACR_TEST_PASSWORD }}
    - run: |
        docker pull ${{ secrets.ACR_DEV_REGISTRY }}/deal-api:${{ env.TAG }}
        docker tag ${{ secrets.ACR_DEV_REGISTRY }}/deal-api:${{ env.TAG }} ${{ secrets.ACR_TEST_REGISTRY }}/deal-api:${{ env.TAG }}
        docker push ${{ secrets.ACR_TEST_REGISTRY }}/deal-api:${{ env.TAG }}
