on:
  push:
    branches: [ github-actions ]

jobs:
     
  portal:
    name: Build and push Portal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        registry: ${{ secrets.ACR_DEV_REGISTRY }}
        username: ${{ secrets.ACR_DEV_USERNAME }}
        password: ${{ secrets.ACR_DEV_PASSWORD }}
        repository: portal
        path: portal
        tags: github
        add_git_labels: true
    - name: Deal API image

  deal-api:
    name: Build and push Deal API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        registry: ${{ secrets.ACR_DEV_REGISTRY }}
        username: ${{ secrets.ACR_DEV_USERNAME }}
        password: ${{ secrets.ACR_DEV_PASSWORD }}
        repository: deal-api
        path: deal-api
        tags: github
        add_git_labels: true
