name: Lint Code Base

on:
  push:
    - branches: [ master ]

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: docker://github/super-linter
