name: Notify Teams on Push
on:
  push:
    branches:
      - chore/setup-push-alerts

env:
  environment: dev

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Commit Information
        id: commit_info
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          COMMIT_SHA=$(git log --format=%H --abbrev=7 -n 1 ${{ github.sha }})
          COMMIT_TIMESTAMP=$(git log --format=%ci -n 1 ${{ github.sha }})
          COMMIT_AUTHOR=${{ github.actor }}

          echo "Commit Message: $COMMIT_MESSAGE"
          echo "Commit SHA: $COMMIT_SHA"
          echo "Commit Author: $COMMIT_AUTHOR"
          echo "Commit Timestamp: $COMMIT_TIMESTAMP"

          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV
          echo "COMMIT_TIMESTAMP=$COMMIT_TIMESTAMP" >> $GITHUB_ENV

      - name: Notify Teams
        env:
          MICROSOFT_TEAMS_WEBHOOK: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK  }}
        run: |
          curl -g -X POST -H 'Content-Type: application/json' -d '{
            "type":"message",
            "attachments":[
                {
                  "contentType":"application/vnd.microsoft.card.adaptive",
                  "contentUrl":null,
                  "content": {
                    "type": "AdaptiveCard",
                    "body": [
                      {
                        "type": "FactSet",
                        "facts": [
                          { "title": "By", "value": "'"${COMMIT_AUTHOR}"'" },
                          { "title": "At", "value": "'"${COMMIT_TIMESTAMP}"'" },
                          { "title": "Change", "value": "'"${COMMIT_MESSAGE}"'" },
                          { "title": "SHA", "value": "'"${COMMIT_SHA}"'" }
                        ]
                      }
                    ],
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "version": "1.2"
                  }
                }
            ]
          }' "${MICROSOFT_TEAMS_WEBHOOK}"
