name: Notify Teams on Push
on:
  push:
    branches:
      - chore/setup-push-alerts

env:
  environment: dev

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Extract Commit Information
        id: commit_info
        run: |
          echo "::set-output name=message::$(git log --format='%s' -n 1 ${{ github.sha }}) - ${{ github.sha }} by ${{ github.actor }}"
          echo "${{ github.event.inputs.message }}"

      - name: Notify Teams
        env:
          MICROSOFT_TEAMS_WEBHOOK: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK  }}
          MESSAGE: ${{ github.event.inputs.message }}
        run: |
          curl -g -X POST -H 'Content-Type: application/json' -d "{
            \"type\":\"message\",
            \"attachments\":[
                {
                  \"contentType\":\"application/vnd.microsoft.card.adaptive\",
                  \"contentUrl\":null,
                  \"content\":{
                      \"\$schema\":\"http://adaptivecards.io/schemas/adaptive-card.json\",
                      \"type\":\"AdaptiveCard\",
                      \"version\":\"1.2\",
                      \"body\":[
                          {
                          \"type\": \"TextBlock\",
                          \"text\": \"${MESSAGE}\"
                          }
                      ]
                  }
                }
            ]
          }" "${MICROSOFT_TEAMS_WEBHOOK}"
