name: Notify Teams on Push
on:
  push:
    branches:
      - chore/setup-push-alerts

env:
  environment: dev

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Commit Information
        id: commit_info
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          COMMIT_SHA=${{ github.sha }}
          COMMIT_AUTHOR=${{ github.actor }}

          echo "Commit Message: $COMMIT_MESSAGE"
          echo "Commit SHA: $COMMIT_SHA"
          echo "Commit Author: $COMMIT_AUTHOR"

          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV

      - name: Notify Teams
        env:
          MICROSOFT_TEAMS_WEBHOOK: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK  }}
        run: |
          curl -g -X POST -H 'Content-Type: application/json' -d "{
            \"type\":\"message\",
            \"attachments\":[
                {
                  \"contentType\":\"application/vnd.microsoft.card.adaptive\",
                  \"contentUrl\":null,
                  \"content\":{
                      \"\$schema\":\"http://adaptivecards.io/schemas/adaptive-card.json\",
                      \"type\":\"AdaptiveCard\",
                      \"version\":\"1.2\",
                      \"body\":[
                          {
                          \"type\": \"TextBlock\",
                          \"text\": \"${COMMIT_SHA} - ${COMMIT_MESSAGE} by ${COMMIT_AUTHOR}\"
                          }
                      ]
                  }
                }
            ]
          }" "${MICROSOFT_TEAMS_WEBHOOK}"
