name: Development environment deployment

on:
  pull_request:
    branches: [ main ]
    paths:
    - 'portal/**'
    - 'portal-api/**'
    - 'gef-ui/**'
    - 'dtfs-central-api/**'
    - 'reference-data-proxy/**'
    - 'trade-finance-manager-ui/**'
    - 'trade-finance-manager-api/**'
    - 'azure-functions/number-generator-function/**'
    - 'azure-functions/acbs-function/**'
  
env:
  environment: dev
  credentials: ${{ secrets.AZURE_DIGITAL_DEV }}
  from: latest
  acr: ${{ secrets.ACR_REGISTRY_DEV }}
  acr_username: ${{ secrets.ACR_USERNAME_DEV }}
  acr_password: ${{ secrets.ACR_PASSWORD_DEV }}

jobs:
  set-environment:
    name: Environment setup
    runs-on: [self-hosted, linux, deployment]
    outputs:
      environment: ${{ env.environment }}
    steps:
    - name: Initialise Environment
      run: "echo Setting environment to ${{ env.environment }}"

  #################### 1. PORTAL UI ####################
  deploy-portal-ui:
    needs: set-environment
    name: Portal UI
    runs-on: [self-hosted, linux, deployment]
    environment:
      name: ${{ needs.set-environment.outputs.environment }}
    env:
      repository: portal-ui

    steps:
    - name: 1. Latest commit hash
      uses: actions/checkout@v3

    - name: 2. Build and push
      uses: docker/build-push-action@v1
      with:
        registry: ${{ env.acr }}
        username: ${{ env.acr_username }}
        password: ${{ env.acr_password }}
        repository: ${{ env.repository }}
        path: portal
        tags: latest
        build_args: GITHUB_SHA=${{ github.sha }}
        add_git_labels: true

    - name: 3. ACR login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.acr }}
        username: ${{ env.acr_username }}
        password: ${{ env.acr_password }}

    - name: 4. Tag images
      run: |
        from=${{ env.from }}
        to=${{ env.environment }}
        docker pull ${{ env.acr }}/${{ env.repository }}:$from
        docker tag ${{ env.acr }}/${{ env.repository }}:$from ${{ env.acr }}/${{ env.repository }}:$to
        docker push ${{ env.acr }}/${{ env.repository }}:$to

    - name: 5. Azure login
      uses: azure/login@v1
      with:
        creds: ${{ env.credentials }}

    - name: 6. CLI - Set defaults
      uses: azure/cli@v1
      with:
        inlineScript: |
          az configure --defaults location=${{ secrets.AZURE_REGION }}
          az configure --defaults group=${{ secrets.RESOURCE_GROUP }}

    - name: 7. CLI Slot - Create
      uses: azure/cli@v1
      with:
        inlineScript: |
          az webapp deployment slot create --name tfs-${{ env.environment }}-${{ env.repository }} --slot ${{ github.sha }} --configuration-source tfs-${{ env.environment }}-${{ env.repository }}
  
    - name: 8. CLI Slot - Swap
      uses: azure/cli@v1
      with:
        inlineScript: |
          az webapp deployment slot swap --name tfs-${{ env.environment }}-${{ env.repository }} --slot ${{ github.sha }} --action swap

    - name: 9. CLI Slot - Delete
      if: ${{ always() }}
      uses: azure/cli@v1
      with:
        inlineScript: |          
          az webapp deployment slot delete --name tfs-${{ env.environment }}-${{ env.repository }} --slot ${{ github.sha }}
