name: Trade Finance Manager UI

on:
  push:
    branches: [ master ]
    paths: 
    - 'trade-finance-manager-ui/**'
    - 'e2e-tests/trade-finance-manager/cypress/**'
  schedule:
    # A weekly run to roll up any base image patches,
    # in office hours, avoiding bank holiday Mondays:
    # "At 12:00 on Tuesday." - https://crontab.guru/
    - cron: '0 12 * * 2'

env:
  environment: dev
  # Credentials for accessing Azure
  credentials: ${{ secrets.AZURE_DIGITAL_DEV }}
  resource_group: ${{ secrets.DEV_RESOURCE_GROUP }}

jobs:

  build:
    name: Build and push TFM UI
    environment:
      name: ${{ env.environment }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Commit hash
      run: "echo GITHUB_SHA=${{ github.sha }}"
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        registry: ${{ secrets.DEV_ACR_REGISTRY }}
        username: ${{ secrets.DEV_ACR_USERNAME }}
        password: ${{ secrets.DEV_ACR_PASSWORD }}
        repository: trade-finance-manager-ui
        path: trade-finance-manager-ui
        tags: latest
        build_args: GITHUB_SHA=${{ github.sha }}
        add_git_labels: true

  test:
    name: "Run end-to-end tests in Compose"
    environment:
      name: ${{ env.environment }}
    needs: build
    runs-on: ubuntu-latest
    env:
      AZURE_WORKFLOW_STORAGE_ACCOUNT: ${{ secrets.E2ETEST_AZURE_WORKFLOW_STORAGE_ACCOUNT }}
      AZURE_WORKFLOW_STORAGE_ACCESS_KEY: ${{ secrets.E2ETEST_AZURE_WORKFLOW_STORAGE_ACCESS_KEY }}
      AZURE_WORKFLOW_FILESHARE_NAME: ${{ secrets.E2ETEST_AZURE_WORKFLOW_FILESHARE_NAME }}
      AZURE_WORKFLOW_EXPORT_FOLDER: ${{ secrets.E2ETEST_AZURE_WORKFLOW_EXPORT_FOLDER }}
      AZURE_WORKFLOW_IMPORT_FOLDER: ${{ secrets.E2ETEST_AZURE_WORKFLOW_IMPORT_FOLDER }}

      AZURE_PORTAL_STORAGE_ACCOUNT: ${{ secrets.E2ETEST_AZURE_PORTAL_STORAGE_ACCOUNT }}
      AZURE_PORTAL_STORAGE_ACCESS_KEY: ${{ secrets.E2ETEST_AZURE_PORTAL_STORAGE_ACCESS_KEY }}
      AZURE_PORTAL_FILESHARE_NAME: ${{ secrets.E2ETEST_AZURE_PORTAL_FILESHARE_NAME }}
      AZURE_PORTAL_EXPORT_FOLDER: ${{ secrets.E2ETEST_AZURE_PORTAL_EXPORT_FOLDER }}

      GOV_NOTIFY_API_KEY: ${{ secrets.E2ETEST_GOV_NOTIFY_API_KEY }}

      MULESOFT_API_KEY: ${{ secrets.E2ETEST_MULESOFT_API_KEY }}
      MULESOFT_API_SECRET: ${{ secrets.E2ETEST_MULESOFT_API_SECRET }}
      MULESOFT_API_NUMBER_GENERATOR_URL: ${{ secrets.E2ETEST_MULESOFT_API_NUMBER_GENERATOR_URL }}
      MULESOFT_API_ACBS_DEAL_URL: ${{ secrets.E2ETEST_MULESOFT_API_ACBS_DEAL_URL }}
      MULESOFT_API_ACBS_FACILITY_URL: ${{ secrets.E2ETEST_MULESOFT_API_ACBS_FACILITY_URL }}
      MULESOFT_API_PARTY_DB_KEY: ${{ secrets.E2ETEST_MULESOFT_API_PARTY_DB_KEY }}
      MULESOFT_API_PARTY_DB_SECRET: ${{ secrets.E2ETEST_MULESOFT_API_PARTY_DB_SECRET }}
      MULESOFT_API_PARTY_DB_URL: ${{ secrets.E2ETEST_MULESOFT_API_PARTY_DB_URL }}
      MULESOFT_API_CURRENCY_EXCHANGE_RATE_URL: ${{ secrets.E2ETEST_MULESOFT_API_CURRENCY_EXCHANGE_RATE_URL }}
      MULESOFT_API_CURRENCY_EXCHANGE_RATE_KEY: ${{ secrets.E2ETEST_MULESOFT_API_CURRENCY_EXCHANGE_RATE_KEY }}
      MULESOFT_API_CURRENCY_EXCHANGE_RATE_SECRET: ${{ secrets.E2ETEST_MULESOFT_API_CURRENCY_EXCHANGE_RATE_SECRET }}
      MULESOFT_API_EXPOSURE_PERIOD_URL: ${{ secrets.E2ETEST_MULESOFT_API_EXPOSURE_PERIOD_URL }}
    
    steps:
    - uses: actions/checkout@v2
    # Pull the latest images to run with so we don't need to build them
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DEV_ACR_REGISTRY }}
        username: ${{ secrets.DEV_ACR_USERNAME }}
        password: ${{ secrets.DEV_ACR_PASSWORD }}
    - name: Pull trade-finance-manager-api
      run: |
        docker pull ${{ secrets.DEV_ACR_REGISTRY }}/trade-finance-manager-api
        docker tag ${{ secrets.DEV_ACR_REGISTRY }}/trade-finance-manager-api dtfs/trade-finance-manager-api
    - name: Pull portal
      run: |
        docker pull ${{ secrets.DEV_ACR_REGISTRY }}/trade-finance-manager-ui
        docker tag ${{ secrets.DEV_ACR_REGISTRY }}/trade-finance-manager-ui dtfs/trade-finance-manager-ui
    - name: Start Docker Compose
      run: |
        source secrets/set_jwt_keypair.sh
        docker-compose up --build -d
        echo "waiting 10 seconds to ensure mongo db has started before we run integration tests against it.."
        sleep 10
    - name: Load mock data
      run: |
        cd utils/mock-data-loader
        npm install
        node ./re-insert-mocks.js
        pwd
    - name: Run e2e tests
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      run: |
        pwd
        cd $GITHUB_WORKSPACE
        npm install
        cd e2e-tests/trade-finance-manager
        npx cypress run --config video=false # --record
    - name: Save Cypress screenshots
      if: ${{ failure() }}
      uses: actions/upload-artifact@main
      with:
        name: screenshots
        path: './cypress/screenshots'
    - uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#dtfs2-dev'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: failure()

  promote:
    name: Promote container images to Dev
    environment:
      name: ${{ env.environment }}
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Dev container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DEV_ACR_REGISTRY }}
        username: ${{ secrets.DEV_ACR_USERNAME }}
        password: ${{ secrets.DEV_ACR_PASSWORD }}
    - name: Tag images
      run: |
        from=latest
        to=dev
        docker pull ${{ secrets.DEV_ACR_REGISTRY }}/trade-finance-manager-ui:$from
        docker tag ${{ secrets.DEV_ACR_REGISTRY }}/trade-finance-manager-ui:$from ${{ secrets.DEV_ACR_REGISTRY }}/trade-finance-manager-ui:$to
        docker push ${{ secrets.DEV_ACR_REGISTRY }}/trade-finance-manager-ui:$to

  deploy:
    name: Deploy container images to Dev
    environment:
      name: ${{ env.environment }}
    needs: promote
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ env.credentials }}

    - name: Defaults
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az configure --defaults location=uksouth
          az configure --defaults group=${{ env.resource_group }}

    - name: Create slot ${{ github.sha }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot create --name tfs-${{ env.environment }}-trade-finance-manager-ui --slot ${{ github.sha }} --configuration-source tfs-${{ env.environment }}-trade-finance-manager-ui

    - name: Swap slot ${{ github.sha }} into production
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot swap   --name tfs-${{ env.environment }}-trade-finance-manager-ui --slot ${{ github.sha }} --action swap

    - name: Delete slot ${{ github.sha }}
      # Clean up the slot regardless of errors
      if: ${{ always() }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot delete --name tfs-${{ env.environment }}-trade-finance-manager-ui --slot ${{ github.sha }}
