name: Deploy ACBS Number Generator Function App

on:
  push:
    branches: [ main ]
    paths: 
    - 'azure-functions/number-generator-function/**'
  schedule:
    # A weekly run to roll up any base image patches, 
    # in office hours, avoiding bank holiday Mondays:
    # "At 12:00 on Tuesday." - https://crontab.guru/
    - cron: '0 12 * * 2'

env:
  environment: dev
  credentials: ${{ secrets.AZURE_DIGITAL_DEV }}

jobs:
  set-environment:
    name: Set Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.environment }}
    steps:
    - name: Initialise Environment
      run: |
        echo Setting environment to ${{ env.environment }}
        
  build:
    name: Build and push ACBS Azure Function
    runs-on: ubuntu-latest
    needs: set-environment
    environment:
      name: ${{ needs.set-environment.outputs.environment }}
    steps:
    - uses: actions/checkout@v2
    - name: Commit hash
      run: "echo GITHUB_SHA=${{ github.sha }}"
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        registry: ${{ secrets.ACR_REGISTRY_DEV }}
        username: ${{ secrets.ACR_USERNAME_DEV }}
        password: ${{ secrets.ACR_PASSWORD_DEV }}
        repository: azure-function-number-generator
        path: azure-functions/number-generator-function
        tags: latest
        build_args: GITHUB_SHA=${{ github.sha }}
        add_git_labels: true

  test:
    name: Test ACBS Azure Functions
    needs: [set-environment, build]
    environment:
      name: ${{ needs.set-environment.outputs.environment }}
    runs-on: ubuntu-latest
    env:
      UKEF_TFM_API_SYSTEM_KEY: ${{ secrets.UKEF_TFM_API_SYSTEM_KEY }}
      UKEF_TFM_API_REPORTS_KEY: ${{ secrets.UKEF_TFM_API_REPORTS_KEY }}
    steps:
    - uses: actions/checkout@v2
    # Pull the latest images to run with so we don't need to build them
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY_DEV }}
        username: ${{ secrets.ACR_USERNAME_DEV }}
        password: ${{ secrets.ACR_PASSWORD_DEV }}
    - name: Pull ACBS Function
      run: |
        docker pull ${{ secrets.ACR_REGISTRY_DEV }}/azure-function-number-generator
        docker tag ${{ secrets.ACR_REGISTRY_DEV }}/azure-function-number-generator dtfs/azure-function-number-generator
        
  promote:
    name: Promote container images to Dev
    runs-on: ubuntu-latest
    needs: [set-environment, test]
    environment:
      name: ${{ needs.set-environment.outputs.environment }}
    steps:
    - name: Log in to Dev container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY_DEV }}
        username: ${{ secrets.ACR_USERNAME_DEV }}
        password: ${{ secrets.ACR_PASSWORD_DEV }}
    - name: Tag images
      run: |
        from=latest
        to=dev
        docker pull ${{ secrets.ACR_REGISTRY_DEV }}/azure-function-number-generator:$from
        docker tag ${{ secrets.ACR_REGISTRY_DEV }}/azure-function-number-generator:$from ${{ secrets.ACR_REGISTRY_DEV }}/azure-function-number-generator:$to
        docker push ${{ secrets.ACR_REGISTRY_DEV }}/azure-function-number-generator:$to

  deploy:
    name: Deploy container images to Dev
    needs: [set-environment, promote]
    environment:
      name: ${{ needs.set-environment.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ env.credentials }}

    - name: Defaults
      uses: azure/CLI@v1.0.0
      with:
        inlineScript: |
          az configure --defaults location=uksouth
          az configure --defaults group=${{ secrets.resource_group }}

    - name: Create slot ${{ github.sha }}
      uses: azure/CLI@v1.0.0
      with:
        inlineScript: |
          az functionapp deployment slot create --name tfs-${{ env.environment }}-function-number-generator --slot ${{ github.sha }} --configuration-source tfs-${{ env.environment }}-function-number-generator

    - name: Swap slot ${{ github.sha }}
      uses: azure/CLI@v1.0.0
      with:
        inlineScript: |
          az functionapp deployment slot swap --name tfs-${{ env.environment }}-function-number-generator --slot ${{ github.sha }} --action swap

    - name: Delete slot ${{ github.sha }}
      # Clean up the slot regardless of errors
      if: ${{ always() }}
      uses: azure/CLI@v1.0.0
      with:
        inlineScript: |
          az functionapp deployment slot delete --name tfs-${{ env.environment }}-function-number-generator --slot ${{ github.sha }}

