name: PR - Integration tests

on:
  pull_request:
    branches: [ main ]
    paths:
    - 'portal/**'
    - 'gef-ui/**'
    - 'trade-finance-manager-ui/**'
    - 'portal-api/**'
    - 'trade-finance-manager-api/**'
    - 'reference-data-proxy/**'
    - 'dtfs-central-api/**'
    - 'e2e-tests/**'
    - 'utils/mock-data-loader/**'

env:
  environment: dev
  credentials: ${{ secrets.AZURE_DIGITAL_DEV }}

jobs:
  set-environment:
    name: Set Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.environment }}
    steps:
    - name: Initialise Environment
      run: echo Setting environment to ${{ env.environment }}

  portal-tests:
    name: Portal integration tests
    needs: set-environment

    # Cancel Previous runs
    concurrency:
      group: portal-integration-tests-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    environment:
      name: ${{ needs.set-environment.outputs.environment }}
    defaults:
      run:
        working-directory: portal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 'latest'
        cache: 'npm'
    - run: npm ci --legacy-peer-deps
    - run: npm run lint
    - run: npm t
    - uses: act10ns/slack@v2
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#dtfs-github-actions'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: failure()

  gef-tests:
    name: GEF integration tests
    needs: set-environment

    # Cancel Previous runs
    concurrency:
      group: gef-integration-tests-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    environment:
      name: ${{ needs.set-environment.outputs.environment }}
    defaults:
      run:
        working-directory: gef-ui
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 'latest'
        cache: 'npm'
    - run: npm ci --legacy-peer-deps
    - run: npm run lint
    - run: npm t
    - uses: act10ns/slack@v2
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#dtfs-github-actions'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: failure()

  tfm-tests:
    name: TFM integration tests
    needs: set-environment

    # Cancel Previous runs
    concurrency:
      group: tfm-integration-tests-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    environment:
      name: ${{ needs.set-environment.outputs.environment }}
    defaults:
      run:
        working-directory: trade-finance-manager-ui
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 'latest'
        cache: 'npm'
    - run: npm ci --legacy-peer-deps
    - run: npm run lint
    - run: npm t
    - uses: act10ns/slack@v2
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#dtfs-github-actions'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: failure()