name: PR - Portal API

on:
  pull_request:
    branches: [main]
    paths:
      - "portal-api/**"
      - "e2e-tests/submit-to-trade-finance-manager/cypress/**"
      - "utils/mock-data-loader/**"

env:
  environment: dev
  credentials: ${{ secrets.AZURE_DIGITAL_DEV }}

jobs:
  lint:
    name: Linting
    defaults:
      run:
        working-directory: portal-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - run: npm run lint
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#dtfs2-dev"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  workflow-build-portal-api:
    uses: uk-export-finance/dtfs/.github/workflows/build_portal-api.yml@main
    needs: [lint]
    with:
      sha: ${{ github.sha }}
    secrets:
      AZURE_DIGITAL_DEV: ${{ secrets.AZURE_DIGITAL_DEV }}
      ACR_REGISTRY_DEV: ${{ secrets.ACR_REGISTRY_DEV }}
      ACR_USERNAME_DEV: ${{ secrets.ACR_USERNAME_DEV }}
      ACR_PASSWORD_DEV: ${{ secrets.ACR_PASSWORD_DEV }}

  workflow-build-portal-ui:
    uses: uk-export-finance/dtfs/.github/workflows/build_portal-ui.yml@main
    needs: [lint]
    with:
      sha: ${{ github.sha }}
    secrets:
      AZURE_DIGITAL_DEV: ${{ secrets.AZURE_DIGITAL_DEV }}
      ACR_REGISTRY_DEV: ${{ secrets.ACR_REGISTRY_DEV }}
      ACR_USERNAME_DEV: ${{ secrets.ACR_USERNAME_DEV }}
      ACR_PASSWORD_DEV: ${{ secrets.ACR_PASSWORD_DEV }}

  workflow-build-tfm-api:
    uses: uk-export-finance/dtfs/.github/workflows/build_tfm-api.yml@main
    needs: [lint]
    with:
      sha: ${{ github.sha }}
    secrets:
      AZURE_DIGITAL_DEV: ${{ secrets.AZURE_DIGITAL_DEV }}
      ACR_REGISTRY_DEV: ${{ secrets.ACR_REGISTRY_DEV }}
      ACR_USERNAME_DEV: ${{ secrets.ACR_USERNAME_DEV }}
      ACR_PASSWORD_DEV: ${{ secrets.ACR_PASSWORD_DEV }}

  workflow-build-tfm-ui:
    uses: uk-export-finance/dtfs/.github/workflows/build_tfm-ui.yml@main
    needs: [lint]
    with:
      sha: ${{ github.sha }}
    secrets:
      AZURE_DIGITAL_DEV: ${{ secrets.AZURE_DIGITAL_DEV }}
      ACR_REGISTRY_DEV: ${{ secrets.ACR_REGISTRY_DEV }}
      ACR_USERNAME_DEV: ${{ secrets.ACR_USERNAME_DEV }}
      ACR_PASSWORD_DEV: ${{ secrets.ACR_PASSWORD_DEV }}

  workflow-build-third-party-api:
    uses: uk-export-finance/dtfs/.github/workflows/build_third-party-api.yml@main
    needs: [lint]
    with:
      sha: ${{ github.sha }}
    secrets:
      AZURE_DIGITAL_DEV: ${{ secrets.AZURE_DIGITAL_DEV }}
      ACR_REGISTRY_DEV: ${{ secrets.ACR_REGISTRY_DEV }}
      ACR_USERNAME_DEV: ${{ secrets.ACR_USERNAME_DEV }}
      ACR_PASSWORD_DEV: ${{ secrets.ACR_PASSWORD_DEV }}

  workflow-build-number-generator:
    uses: uk-export-finance/dtfs/.github/workflows/build_azure-function-number-generator.yml@main
    needs: [lint]
    with:
      sha: ${{ github.sha }}
    secrets:
      AZURE_DIGITAL_DEV: ${{ secrets.AZURE_DIGITAL_DEV }}
      ACR_REGISTRY_DEV: ${{ secrets.ACR_REGISTRY_DEV }}
      ACR_USERNAME_DEV: ${{ secrets.ACR_USERNAME_DEV }}
      ACR_PASSWORD_DEV: ${{ secrets.ACR_PASSWORD_DEV }}

  test:
    name: "Run PR tests"
    needs:
      [
        workflow-build-portal-api,
        workflow-build-portal-ui,
        workflow-build-tfm-api,
        workflow-build-tfm-ui,
        workflow-build-third-party-api,
        workflow-build-number-generator,
      ]
    runs-on: ubuntu-latest
    env:
      AZURE_WORKFLOW_STORAGE_ACCOUNT: ${{ secrets.AZURE_WORKFLOW_STORAGE_ACCOUNT }}
      AZURE_WORKFLOW_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_WORKFLOW_STORAGE_ACCESS_KEY }}
      AZURE_WORKFLOW_FILESHARE_NAME: ${{ secrets.AZURE_WORKFLOW_FILESHARE_NAME }}
      AZURE_WORKFLOW_EXPORT_FOLDER: ${{ secrets.AZURE_WORKFLOW_EXPORT_FOLDER }}
      AZURE_WORKFLOW_IMPORT_FOLDER: ${{ secrets.AZURE_WORKFLOW_IMPORT_FOLDER }}

      AZURE_PORTAL_STORAGE_ACCOUNT: ${{ secrets.AZURE_PORTAL_STORAGE_ACCOUNT }}
      AZURE_PORTAL_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_PORTAL_STORAGE_ACCESS_KEY }}
      AZURE_PORTAL_FILESHARE_NAME: ${{ secrets.AZURE_PORTAL_FILESHARE_NAME }}
      AZURE_PORTAL_EXPORT_FOLDER: ${{ secrets.AZURE_PORTAL_EXPORT_FOLDER }}

      GOV_NOTIFY_API_KEY: ${{ secrets.GOV_NOTIFY_API_KEY }}
      GOV_NOTIFY_EMAIL_RECIPIENT: ${{ secrets.GOV_NOTIFY_EMAIL_RECIPIENT }}

      JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}
      JWT_VALIDATING_KEY: ${{ secrets.JWT_VALIDATING_KEY }}

      COMPANIES_HOUSE_API_URL: "https://api.companieshouse.gov.uk"
      COMPANIES_HOUSE_API_KEY: ${{ secrets.COMPANIES_HOUSE_API_KEY }}

      UKEF_TFM_API_SYSTEM_KEY: ${{ secrets.UKEF_TFM_API_SYSTEM_KEY }}
      UKEF_TFM_API_REPORTS_KEY: ${{ secrets.UKEF_TFM_API_REPORTS_KEY }}

    steps:
      - uses: actions/checkout@v2
      # Pull the latest images to run with so we don't need to build them
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY_DEV }}
          username: ${{ secrets.ACR_USERNAME_DEV }}
          password: ${{ secrets.ACR_PASSWORD_DEV }}
      - name: Pull portal-api
        run: |
          docker pull ${{ secrets.ACR_REGISTRY_DEV }}/portal-api:${{ github.sha }}
          docker tag ${{ secrets.ACR_REGISTRY_DEV }}/portal-api:${{ github.sha }} dtfs/portal-api
      - name: Start Docker Compose
        run: |
          source secrets/set_jwt_keypair.sh && docker-compose up -d portal-api
          echo "waiting 10 seconds to ensure mongo db has started before we run integration tests against it.."
          sleep 10
      - name: Load mock data
        run: |
          cd utils/mock-data-loader
          npm install
          node ./re-insert-mocks.js
      - name: Run API tests
        run: |
          docker-compose exec -T portal-api npm run api-test
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#dtfs2-dev"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
