name: PR - TFM UI

on:
  pull_request:
    branches: [ main ]
    paths:
    - 'trade-finance-manager-ui/**'
    - 'e2e-tests/trade-finance-manager/cypress/**'
    - 'utils/mock-data-loader/**'

env:
  environment: dev
  credentials: ${{ secrets.AZURE_DIGITAL_DEV }}

jobs:
  lint:
    name: Linting
    defaults:
      run:
        working-directory: portal-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - run: npm run lint
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#dtfs2-dev"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  workflow-build-tfm-ui:
    uses: uk-export-finance/dtfs/.github/workflows/build_tfm-ui.yml@main
    needs: [lint]
    with:
      sha: ${{ github.sha }}
    secrets:
      AZURE_DIGITAL_DEV: ${{ secrets.AZURE_DIGITAL_DEV }}
      ACR_REGISTRY_DEV: ${{ secrets.ACR_REGISTRY_DEV }}
      ACR_USERNAME_DEV: ${{ secrets.ACR_USERNAME_DEV }}
      ACR_PASSWORD_DEV: ${{ secrets.ACR_PASSWORD_DEV }}

  workflow-build-tfm-api:
    uses: uk-export-finance/dtfs/.github/workflows/build_tfm-api.yml@main
    needs: [lint]
    with:
      sha: ${{ github.sha }}
    secrets:
      AZURE_DIGITAL_DEV: ${{ secrets.AZURE_DIGITAL_DEV }}
      ACR_REGISTRY_DEV: ${{ secrets.ACR_REGISTRY_DEV }}
      ACR_USERNAME_DEV: ${{ secrets.ACR_USERNAME_DEV }}
      ACR_PASSWORD_DEV: ${{ secrets.ACR_PASSWORD_DEV }}

  workflow-build-portal-api:
    uses: uk-export-finance/dtfs/.github/workflows/build_portal-api.yml@main
    needs: [lint]
    with:
      sha: ${{ github.sha }}
    secrets:
      AZURE_DIGITAL_DEV: ${{ secrets.AZURE_DIGITAL_DEV }}
      ACR_REGISTRY_DEV: ${{ secrets.ACR_REGISTRY_DEV }}
      ACR_USERNAME_DEV: ${{ secrets.ACR_USERNAME_DEV }}
      ACR_PASSWORD_DEV: ${{ secrets.ACR_PASSWORD_DEV }}

  workflow-build-third-party-api:
    uses: uk-export-finance/dtfs/.github/workflows/build_third-party-api.yml@main
    needs: [lint]
    with:
      sha: ${{ github.sha }}
    secrets:
      AZURE_DIGITAL_DEV: ${{ secrets.AZURE_DIGITAL_DEV }}
      ACR_REGISTRY_DEV: ${{ secrets.ACR_REGISTRY_DEV }}
      ACR_USERNAME_DEV: ${{ secrets.ACR_USERNAME_DEV }}
      ACR_PASSWORD_DEV: ${{ secrets.ACR_PASSWORD_DEV }}

  workflow-build-number-generator:
    uses: uk-export-finance/dtfs/.github/workflows/build_azure-function-number-generator.yml@main
    needs: [lint]
    with:
      sha: ${{ github.sha }}
    secrets:
      AZURE_DIGITAL_DEV: ${{ secrets.AZURE_DIGITAL_DEV }}
      ACR_REGISTRY_DEV: ${{ secrets.ACR_REGISTRY_DEV }}
      ACR_USERNAME_DEV: ${{ secrets.ACR_USERNAME_DEV }}
      ACR_PASSWORD_DEV: ${{ secrets.ACR_PASSWORD_DEV }}
