name: Pipeline

on:
  push:
    branches: [ master ]
    
env:
  TAG: latest

  COMPANIES_HOUSE_API_KEY: ${{ secrets.COMPANIES_HOUSE_API_KEY }}

  AZURE_WORKFLOW_STORAGE_ACCOUNT: ${{ secrets.AZURE_WORKFLOW_STORAGE_ACCOUNT }}
  AZURE_WORKFLOW_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_WORKFLOW_STORAGE_ACCESS_KEY }}
  AZURE_WORKFLOW_FILESHARE_NAME: ${{ secrets.AZURE_WORKFLOW_FILESHARE_NAME }}
  AZURE_WORKFLOW_EXPORT_FOLDER: ${{ secrets.AZURE_WORKFLOW_EXPORT_FOLDER }}
  AZURE_WORKFLOW_IMPORT_FOLDER: ${{ secrets.AZURE_WORKFLOW_IMPORT_FOLDER }}

  AZURE_PORTAL_STORAGE_ACCOUNT: ${{ secrets.AZURE_PORTAL_STORAGE_ACCOUNT }}
  AZURE_PORTAL_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_PORTAL_STORAGE_ACCESS_KEY }}
  AZURE_PORTAL_FILESHARE_NAME: ${{ secrets.AZURE_PORTAL_FILESHARE_NAME }}
  AZURE_PORTAL_EXPORT_FOLDER: ${{ secrets.AZURE_PORTAL_EXPORT_FOLDER }}

  GOV_NOTIFY_API_KEY: ${{ secrets.GOV_NOTIFY_API_KEY }}
  GOV_NOTIFY_EMAIL_RECIPIENT: ${{ secrets.GOV_NOTIFY_EMAIL_RECIPIENT }}

jobs:

  promote-portal-ui-prod:
    name: Promote Portal from Test to Prod
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_TEST_REGISTRY }}
        username: ${{ secrets.ACR_TEST_USERNAME }}
        password: ${{ secrets.ACR_TEST_PASSWORD }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_PROD_REGISTRY }}
        username: ${{ secrets.ACR_PROD_USERNAME }}
        password: ${{ secrets.ACR_PROD_PASSWORD }}
    - run: |
        docker pull ${{ secrets.ACR_TEST_REGISTRY }}/portal-ui:${{ env.TAG }}
        docker tag ${{ secrets.ACR_TEST_REGISTRY }}/portal-ui:${{ env.TAG }} ${{ secrets.ACR_PROD_REGISTRY }}/portal-ui:${{ env.TAG }}
        docker push ${{ secrets.ACR_PROD_REGISTRY }}/portal-ui:${{ env.TAG }}

  promote-portal-api-prod:
    name: Promote Portal API from Test to Prod
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_TEST_REGISTRY }}
        username: ${{ secrets.ACR_TEST_USERNAME }}
        password: ${{ secrets.ACR_TEST_PASSWORD }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_PROD_REGISTRY }}
        username: ${{ secrets.ACR_PROD_USERNAME }}
        password: ${{ secrets.ACR_PROD_PASSWORD }}
    - run: |
        docker pull ${{ secrets.ACR_TEST_REGISTRY }}/portal-api:${{ env.TAG }}
        docker tag ${{ secrets.ACR_TEST_REGISTRY }}/portal-api:${{ env.TAG }} ${{ secrets.ACR_PROD_REGISTRY }}/portal-api:${{ env.TAG }}
        docker push ${{ secrets.ACR_PROD_REGISTRY }}/portal-api:${{ env.TAG }}
