name: Deploy demo

on:
  push:
    branches: [ demo ]

env:
  environment: demo
  credentials: ${{ secrets.AZURE_DIGITAL_DEV }}
  resource_group: ${{ secrets.DEMO_RESOURCE_GROUP }}

jobs:

  promote:
    name: Promote container images
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DEV_ACR_REGISTRY }}
        username: ${{ secrets.DEV_ACR_USERNAME }}
        password: ${{ secrets.DEV_ACR_PASSWORD }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DEMO_ACR_REGISTRY }}
        username: ${{ secrets.DEMO_ACR_USERNAME }}
        password: ${{ secrets.DEMO_ACR_PASSWORD }}
    - name: Tag images
      run: |
        from=dev
        to=demo

        docker pull ${{ secrets.DEV_ACR_REGISTRY }}/portal-ui:$from
        docker tag ${{ secrets.DEV_ACR_REGISTRY }}/portal-ui:$from ${{ secrets.DEMO_ACR_REGISTRY }}/portal-ui:$to
        docker push ${{ secrets.DEMO_ACR_REGISTRY }}/portal-ui:$to

        docker pull ${{ secrets.DEV_ACR_REGISTRY }}/portal-api:$from
        docker tag ${{ secrets.DEV_ACR_REGISTRY }}/portal-api:$from ${{ secrets.DEMO_ACR_REGISTRY }}/portal-api:$to
        docker push ${{ secrets.DEMO_ACR_REGISTRY }}/portal-api:$to

  deploy:
    # The App Service seems to need to be restarted to trigger a redeploy
    name: Deploy container images
    needs: promote
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ env.credentials }}
    - name: Restart app services
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp restart --name tfs-${{ env.environment }}-portal-ui --resource-group ${{ env.resource_group }}
          az webapp restart --name tfs-${{ env.environment }}-portal-api --resource-group ${{ env.resource_group }}

  refresh-data:
    needs: deploy
    name: Refresh environment data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Re-insert mocks
        run: |
          cd utils/mock-data-loader 
          echo "DEAL_API_URL=https://tfs-${{ env.environment }}-portal-api.azurewebsites.net" > .env
          cat .env
          npm install
          node re-insert-mocks.js