name: Deploy demo

on:
  push:
    branches: [ demo ]

env:
  environment: demo
  credentials: ${{ secrets.AZURE_DIGITAL_DEV }}
  resource_group: ${{ secrets.DEMO_RESOURCE_GROUP }}

  # From
  registry_from: ${{ secrets.DEV_ACR_REGISTRY }}
  registry_from_username: ${{ secrets.DEV_ACR_USERNAME }}
  registry_from_password: ${{ secrets.DEV_ACR_PASSWORD }}
  tag_from: dev

  # To
  registry_to: ${{ secrets.DEMO_ACR_REGISTRY }}
  registry_to_username: ${{ secrets.DEMO_ACR_USERNAME }}
  registry_to_password: ${{ secrets.DEMO_ACR_PASSWORD }}
  tag_to: demo

jobs:

  portal-ui:
    name: Promote Portal UI
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ env.credentials }}

    - name: Defaults
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az configure --defaults location=uksouth
          az configure --defaults group=${{ env.resource_group }}

    - name: Log in to source container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registry_from }}
        username: ${{ env.registry_from_username }}
        password: ${{ env.registry_from_password }}

    - name: Log in to destination container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registry_to }}
        username: ${{ env.registry_to_username }}
        password: ${{ env.registry_to_password }}

    - name: Promote container image
      run: |
        docker pull ${{ env.registry_from }}/portal-ui:${{ env.tag_from }}
        docker tag ${{ env.registry_from }}/portal-ui:${{ env.tag_from }} ${{ env.registry_to }}/portal-ui:${{ env.tag_to }}
        docker push ${{ env.registry_to }}/portal-ui:${{ env.tag_to }}

    - name: Create slot
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot create --name tfs-${{ env.environment }}-portal-ui --slot ${{ github.sha }} --configuration-source tfs-${{ env.environment }}-portal-ui

    - name: Swap slot
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot swap --name tfs-${{ env.environment }}-portal-ui --slot ${{ github.sha }} --action swap
          
    - name: Delete slot
      # Clean up the slot regardless of errors
      if: ${{ always() }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot delete --name tfs-${{ env.environment }}-portal-ui --slot ${{ github.sha }}
        
  portal-api:
    name: Promote Portal API
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ env.credentials }}

    - name: Defaults
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az configure --defaults location=uksouth
          az configure --defaults group=${{ env.resource_group }}

    - name: Log in to source container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registry_from }}
        username: ${{ env.registry_from_username }}
        password: ${{ env.registry_from_password }}

    - name: Log in to destination container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registry_to }}
        username: ${{ env.registry_to_username }}
        password: ${{ env.registry_to_password }}

    - name: Promote container image
      run: |
        docker pull ${{ env.registry_from }}/portal-api:${{ env.tag_from }}
        docker tag ${{ env.registry_from }}/portal-api:${{ env.tag_from }} ${{ env.registry_to }}/portal-api:${{ env.tag_to }}
        docker push ${{ env.registry_to }}/portal-api:${{ env.tag_to }}

    - name: Create slot
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot create --name tfs-${{ env.environment }}-portal-api --slot ${{ github.sha }} --configuration-source tfs-${{ env.environment }}-portal-api

    - name: Swap slot
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot swap --name tfs-${{ env.environment }}-portal-api --slot ${{ github.sha }} --action swap
          
    - name: Delete slot
      # Clean up the slot regardless of errors
      if: ${{ always() }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot delete --name tfs-${{ env.environment }}-portal-api --slot ${{ github.sha }}
  
  reference-data-proxy:
    name: Promote Reference Data Proxy
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ env.credentials }}

    - name: Defaults
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az configure --defaults location=uksouth
          az configure --defaults group=${{ env.resource_group }}

    - name: Log in to source container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registry_from }}
        username: ${{ env.registry_from_username }}
        password: ${{ env.registry_from_password }}

    - name: Log in to destination container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registry_to }}
        username: ${{ env.registry_to_username }}
        password: ${{ env.registry_to_password }}

    - name: Promote container image
      run: |
        docker pull ${{ env.registry_from }}/reference-data-proxy:${{ env.tag_from }}
        docker tag ${{ env.registry_from }}/reference-data-proxy:${{ env.tag_from }} ${{ env.registry_to }}/reference-data-proxy:${{ env.tag_to }}
        docker push ${{ env.registry_to }}/reference-data-proxy:${{ env.tag_to }}

    - name: Create slot
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot create --name tfs-${{ env.environment }}-reference-data-proxy --slot ${{ github.sha }} --configuration-source tfs-${{ env.environment }}-reference-data-proxy

    - name: Swap slot
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot swap --name tfs-${{ env.environment }}-reference-data-proxy --slot ${{ github.sha }} --action swap
          
    - name: Delete slot
      # Clean up the slot regardless of errors
      if: ${{ always() }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot delete --name tfs-${{ env.environment }}-reference-data-proxy --slot ${{ github.sha }}

  trade-finance-manager-ui:
    name: Promote TFM UI
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ env.credentials }}

    - name: Defaults
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az configure --defaults location=uksouth
          az configure --defaults group=${{ env.resource_group }}

    - name: Log in to source container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registry_from }}
        username: ${{ env.registry_from_username }}
        password: ${{ env.registry_from_password }}

    - name: Log in to destination container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registry_to }}
        username: ${{ env.registry_to_username }}
        password: ${{ env.registry_to_password }}

    - name: Promote container image
      run: |
        docker pull ${{ env.registry_from }}/trade-finance-manager-ui:${{ env.tag_from }}
        docker tag ${{ env.registry_from }}/trade-finance-manager-ui:${{ env.tag_from }} ${{ env.registry_to }}/trade-finance-manager-ui:${{ env.tag_to }}
        docker push ${{ env.registry_to }}/trade-finance-manager-ui:${{ env.tag_to }}

    - name: Create slot
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot create --name tfs-${{ env.environment }}-trade-finance-manager-ui --slot ${{ github.sha }} --configuration-source tfs-${{ env.environment }}-trade-finance-manager-ui

    - name: Swap slot
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot swap --name tfs-${{ env.environment }}-trade-finance-manager-ui --slot ${{ github.sha }} --action swap
          
    - name: Delete slot
      # Clean up the slot regardless of errors
      if: ${{ always() }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot delete --name tfs-${{ env.environment }}-trade-finance-manager-ui --slot ${{ github.sha }}
        
  trade-finance-manager-api:
    name: Promote TFM API
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ env.credentials }}

    - name: Defaults
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az configure --defaults location=uksouth
          az configure --defaults group=${{ env.resource_group }}

    - name: Log in to source container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registry_from }}
        username: ${{ env.registry_from_username }}
        password: ${{ env.registry_from_password }}

    - name: Log in to destination container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registry_to }}
        username: ${{ env.registry_to_username }}
        password: ${{ env.registry_to_password }}

    - name: Promote container image
      run: |
        docker pull ${{ env.registry_from }}/trade-finance-manager-api:${{ env.tag_from }}
        docker tag ${{ env.registry_from }}/trade-finance-manager-api:${{ env.tag_from }} ${{ env.registry_to }}/trade-finance-manager-api:${{ env.tag_to }}
        docker push ${{ env.registry_to }}/trade-finance-manager-api:${{ env.tag_to }}

    - name: Create slot
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot create --name tfs-${{ env.environment }}-trade-finance-manager-api --slot ${{ github.sha }} --configuration-source tfs-${{ env.environment }}-trade-finance-manager-api

    - name: Swap slot
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot swap --name tfs-${{ env.environment }}-trade-finance-manager-api --slot ${{ github.sha }} --action swap
          
    - name: Delete slot
      # Clean up the slot regardless of errors
      if: ${{ always() }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot delete --name tfs-${{ env.environment }}-trade-finance-manager-api --slot ${{ github.sha }}

  dtfs-central-api:
    name: Promote DTFS Central API
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ env.credentials }}

    - name: Defaults
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az configure --defaults location=uksouth
          az configure --defaults group=${{ env.resource_group }}

    - name: Log in to source container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registry_from }}
        username: ${{ env.registry_from_username }}
        password: ${{ env.registry_from_password }}

    - name: Log in to destination container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registry_to }}
        username: ${{ env.registry_to_username }}
        password: ${{ env.registry_to_password }}

    - name: Promote container image
      run: |
        docker pull ${{ env.registry_from }}/dtfs-central-api:${{ env.tag_from }}
        docker tag ${{ env.registry_from }}/dtfs-central-api:${{ env.tag_from }} ${{ env.registry_to }}/dtfs-central-api:${{ env.tag_to }}
        docker push ${{ env.registry_to }}/dtfs-central-api:${{ env.tag_to }}

    - name: Create slot
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot create --name tfs-${{ env.environment }}-dtfs-central-api --slot ${{ github.sha }} --configuration-source tfs-${{ env.environment }}-dtfs-central-api

    - name: Swap slot
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot swap --name tfs-${{ env.environment }}-dtfs-central-api --slot ${{ github.sha }} --action swap
          
    - name: Delete slot
      # Clean up the slot regardless of errors
      if: ${{ always() }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp deployment slot delete --name tfs-${{ env.environment }}-dtfs-central-api --slot ${{ github.sha }}