name: Deploy prod

on:
  push:
    branches: [ prod ]

env:
  environment: prod
  credentials: ${{ secrets.AZURE_DIGITAL_PROD }}
  resource_group: ${{ secrets.PROD_RESOURCE_GROUP }}

jobs:

  promote:
    name: Promote container images
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.TEST_ACR_REGISTRY }}
        username: ${{ secrets.TEST_ACR_USERNAME }}
        password: ${{ secrets.TEST_ACR_PASSWORD }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.PROD_ACR_REGISTRY }}
        username: ${{ secrets.PROD_ACR_USERNAME }}
        password: ${{ secrets.PROD_ACR_PASSWORD }}
    - name: Tag images
      run: |
        from=test
        to=prod

        docker pull ${{ secrets.TEST_ACR_REGISTRY }}/portal-ui:$from
        docker tag ${{ secrets.TEST_ACR_REGISTRY }}/portal-ui:$from ${{ secrets.PROD_ACR_REGISTRY }}/portal-ui:$to
        docker push ${{ secrets.PROD_ACR_REGISTRY }}/portal-ui:$to

        docker pull ${{ secrets.TEST_ACR_REGISTRY }}/portal-api:$from
        docker tag ${{ secrets.TEST_ACR_REGISTRY }}/portal-api:$from ${{ secrets.PROD_ACR_REGISTRY }}/portal-api:$to
        docker push ${{ secrets.PROD_ACR_REGISTRY }}/portal-api:$to

  deploy:
    # The App Service seems to need to be restarted to trigger a redeploy
    name: Deploy container images
    needs: promote
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ env.credentials }}
    - name: Restart app services
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp restart --name tfs-${{ env.environment }}-portal-ui --resource-group ${{ env.resource_group }}
          az webapp restart --name tfs-${{ env.environment }}-portal-api --resource-group ${{ env.resource_group }}