on: [push]

name: AzureCLISample

# We want to delete only untagged manifests because we're using moveable tags, so we specify a tag that doesn't exist
env: PURGE_CMD="acr purge --filter 'portal:untagged' --filter 'deal-api:untagged' --untagged --ago 1d"

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_DIGITAL_DEV }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az acr run \
            --cmd "$PURGE_CMD" \
            --registry dtfs-dev \
            /dev/null