name: Purge
run-name: 🧹Azure purge

on:
  schedule:
    - cron: '0 1 * * *'

env:
  APPLICATION: ${{ vars.APPLICATION }}
  ENVIRONMENT: infrastructure
  TIMEZONE: ${{ vars.TIMEZONE }}

jobs:
  # 1. Base actions configrations
  setup:
    name: Setup 🔧
    runs-on: [self-hosted, linux, deployment]
    outputs:
      application: ${{ env.APPLICATION }}
      environment: ${{ steps.environment.outputs.environment }}
      timezone: ${{ env.TIMEZONE }}

    steps:
      - name: Environment 🧪
        id: environment
        run: |
          echo "environment=dev" >> "$GITHUB_OUTPUT"

      - name: Timezone 🌐
        run: echo "Timezone set to ${{ env.TIMEZONE }}"

  # 2. Azure purge
  purge:
    name: Purge 🗑️
    needs: [setup]
    environment: ${{ needs.setup.outputs.environment }}
    runs-on: [self-hosted, DTFS, deployment]
    env:
      ENVIRONMENT: ${{ needs.setup.outputs.environment }}

    strategy:
      max-parallel: 1
      # Do not cancel in-progress jobs upon failure
      fail-fast: false
      # Single dimension matrix
      matrix:
        acr: ['tfsdev', 'tfsstaging']
        rg: ['Digital-Dev', 'Digital-Test']
        subscription: ['']

    concurrency:
      group: acr-purge-${{ github.workflow }}-${{ github.workflow_ref }}-${{ matrix.acr }}
      cancel-in-progress: true

    steps:
      - name: Repository 🗂️
        uses: actions/checkout@v4

      - name: Execute ⚡
        uses: ./.github/actions/acr
        with:
          acr: ${{ matrix.acr }}
          rg: ${{ matrix.rg }}
          days: ${{ vars.ACR_PURGE_NONPROD_DAYS }}

      - name: Notification  🔔
        uses: ./.github/actions/notify
        with:
          webhook: ${{ secrets.MSTEAMS_WEBHOOK }}
          content: '{"@type": "MessageCard","@context": "http://schema.org/extensions","themeColor": "00703c","title": "🗑️ ${{ matrix.acr }} purge","summary": "Purged artifacts from ''${{ matrix.acr }}'' Azure container registry","sections": [{"activityTitle": "ACR Purge","activitySubtitle": "Purged artifacts from **${{ matrix.acr }}** Azure container registry","facts": [{"name": "ACR","value": "${{ matrix.acr }}"},{  "name": "Resource group",  "value": "${{ matrix.rg }}"},{"name": "Commit","value": "${{ github.sha }}"}],"markdown": true}],"potentialAction": [{"@type": "OpenUri","name": "Workflow","targets": [{"os": "default","uri": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}]}]}'
