name: Pipeline

on:
  push:
    branches: [ master ]
  schedule:
    # A weekly run to roll up any base image patches,
    # in office hours, avoiding bank holiday Mondays:
    # "At 12:00 on Tuesday." - https://crontab.guru/
    - cron: '0 12 * * 2'

jobs:

  portal:
    name: Test pipeline
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Environment
      # NB this relies on Docker Compose being available on the build agent (it seems it is)
      run: |
        export COMPANIES_HOUSE_API_KEY=${{ secrets.COMPANIES_HOUSE_API_KEY }}

        export AZURE_WORKFLOW_STORAGE_ACCOUNT=${{ secrets.AZURE_WORKFLOW_STORAGE_ACCOUNT }}
        export AZURE_WORKFLOW_STORAGE_ACCESS_KEY=${{ secrets.AZURE_WORKFLOW_STORAGE_ACCESS_KEY }}
        export AZURE_WORKFLOW_FILESHARE_NAME=${{ secrets.AZURE_WORKFLOW_FILESHARE_NAME }}
        export AZURE_WORKFLOW_EXPORT_FOLDER=${{ secrets.AZURE_WORKFLOW_EXPORT_FOLDER }}
        export AZURE_WORKFLOW_IMPORT_FOLDER=${{ secrets.AZURE_WORKFLOW_IMPORT_FOLDER }}
        
        export AZURE_PORTAL_STORAGE_ACCOUNT=${{ secrets.AZURE_PORTAL_STORAGE_ACCOUNT }}
        export AZURE_PORTAL_STORAGE_ACCESS_KEY=${{ secrets.AZURE_PORTAL_STORAGE_ACCESS_KEY }}
        export AZURE_PORTAL_FILESHARE_NAME=${{ secrets.AZURE_PORTAL_FILESHARE_NAME }}
        export AZURE_PORTAL_EXPORT_FOLDER=${{ secrets.AZURE_PORTAL_EXPORT_FOLDER }}

        env
    - name: Run pipeline
      # NB this relies on Docker Compose being available on the build agent (it seems it is)
      run: |
        export COMPANIES_HOUSE_API_KEY=${{ secrets.COMPANIES_HOUSE_API_KEY }}

        export AZURE_WORKFLOW_STORAGE_ACCOUNT=${{ secrets.AZURE_WORKFLOW_STORAGE_ACCOUNT }}
        export AZURE_WORKFLOW_STORAGE_ACCESS_KEY=${{ secrets.AZURE_WORKFLOW_STORAGE_ACCESS_KEY }}
        export AZURE_WORKFLOW_FILESHARE_NAME=${{ secrets.AZURE_WORKFLOW_FILESHARE_NAME }}
        export AZURE_WORKFLOW_EXPORT_FOLDER=${{ secrets.AZURE_WORKFLOW_EXPORT_FOLDER }}
        export AZURE_WORKFLOW_IMPORT_FOLDER=${{ secrets.AZURE_WORKFLOW_IMPORT_FOLDER }}
        
        export AZURE_PORTAL_STORAGE_ACCOUNT=${{ secrets.AZURE_PORTAL_STORAGE_ACCOUNT }}
        export AZURE_PORTAL_STORAGE_ACCESS_KEY=${{ secrets.AZURE_PORTAL_STORAGE_ACCESS_KEY }}
        export AZURE_PORTAL_FILESHARE_NAME=${{ secrets.AZURE_PORTAL_FILESHARE_NAME }}
        export AZURE_PORTAL_EXPORT_FOLDER=${{ secrets.AZURE_PORTAL_EXPORT_FOLDER }}

        npm run pipeline
