const express = require('express');
const sessionUserToLocals = require('../middleware/sessionUserToLocals');
const mandatoryCriteriaRoutes = require('./mandatory-criteria');
const nameApplicationRoutes = require('./name-application');
const applicationDetailsRoutes = require('./application-details');
const supportingInformationRoutes = require('./supporting-information');
const applicationSubmissionRoutes = require('./application-submission');
const applicationAbandonRoutes = require('./application-abandon');
const submitToUkefRoutes = require('./submit-to-ukef');
const eligibleAutomaticCoverRoutes = require('./eligible-automatic-cover');
const automaticCoverRoutes = require('./automatic-cover');
const companiesHouseRoutes = require('./companies-house');
const exportersAddressRoutes = require('./exporters-address');
const selectExportersCorrespondenceAddressRoutes = require('./select-exporters-correspondence-address');
const enterExportersCorrespondenceAddressRoutes = require('./enter-exporters-correspondence-address');
const aboutExporterRoutes = require('./about-exporter');
const facilitiesRoutes = require('./facilities/facilities');
const aboutFacilityRoutes = require('./facilities/about-facility');
const providedFacilityRoutes = require('./facilities/provided-facility');
const facilityCurrencyRoutes = require('./facilities/facility-currency');
const facilityValueRoutes = require('./facilities/facility-value');
const facilityGuaranteeRoutes = require('./facilities/facility-guarantee');
const facilityConfirmDeletionRoutes = require('./facilities/facility-confirm-deletion');
const returnToMaker = require('./return-to-maker');
const securityDetails = require('./security-details');
const file = require('./downloadFile');
const reviewUkefDecision = require('./review-decision');
const coverStartDate = require('./facilities/cover-start-date');
const confirmCoverStartDate = require('./facilities/confirm-cover-start-date');
const portalActivities = require('./application-activities');
const cloneGefDeal = require('./clone-gef-deal');
const unissuedFacilities = require('./unissued-facilities');
const { default: bankReviewDate } = require('./facilities/bank-review-date');
const { default: facilityEndDate } = require('./facilities/facility-end-date');
const { default: amendments } = require('./facilities/amendments/index');

const router = express.Router();

router.use('*', sessionUserToLocals);

router.use(mandatoryCriteriaRoutes);
router.use(nameApplicationRoutes);
router.use(eligibleAutomaticCoverRoutes);
router.use(applicationDetailsRoutes);
router.use(supportingInformationRoutes);
router.use(applicationSubmissionRoutes);
router.use(applicationAbandonRoutes);
router.use(submitToUkefRoutes);
router.use(automaticCoverRoutes);
router.use(companiesHouseRoutes);
router.use(exportersAddressRoutes);
router.use(selectExportersCorrespondenceAddressRoutes);
router.use(enterExportersCorrespondenceAddressRoutes);
router.use(aboutExporterRoutes);
router.use(facilitiesRoutes);
router.use(bankReviewDate);
router.use(facilityEndDate);
router.use(amendments);
router.use(aboutFacilityRoutes);
router.use(providedFacilityRoutes);
router.use(facilityCurrencyRoutes);
router.use(facilityValueRoutes);
router.use(facilityGuaranteeRoutes);
router.use(facilityConfirmDeletionRoutes);
router.use(returnToMaker);
router.use(securityDetails);
router.use(file);
router.use(cloneGefDeal);
router.use(reviewUkefDecision);
router.use(confirmCoverStartDate);
router.use(coverStartDate);
router.use(portalActivities);
router.use(unissuedFacilities);

module.exports = router;
